type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

const LAST_VERIFIED_AT = "2026-07-26";

const CA_DENTIST_URL =
  "https://www.dbc.ca.gov/licensees/dentist_continuing_education.shtml";
const CA_DENTAL_HYGIENIST_URL =
  "https://www.dhbc.ca.gov/licensees/ce_course_requirement.shtml";
const FL_DENTIST_URL = "https://floridasdentistry.gov/dentist-renewal/";
const FL_DENTAL_HYGIENIST_URL =
  "https://floridasdentistry.gov/dental-hygienist-renewal/";
const NJ_DENTAL_URL =
  "https://www.njconsumeraffairs.gov/den/Documents/CE-Requirements0424.pdf";
const NY_DENTAL_URL =
  "https://www.op.nysed.gov/professions/dentists/continuing-education-q-a";
const PA_DENTIST_URL =
  "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter33/s33.401.html";
const PA_DENTAL_HYGIENIST_URL =
  "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter33/s33.402.html";
const TX_DENTIST_URL =
  "https://tsbde.texas.gov/laws-rules/dental-practice-act-tsbde-rules/";
const TX_DENTAL_HYGIENIST_URL =
  "https://tsbde.texas.gov/licensing/hygienists/hygienist-continuing-education/";

export const DENTAL_RULE_SET_SEED_BINDINGS = [
  [
    "ca-dentist-2026-v1",
    "ca-dentist",
    1,
    "Dental",
    "Dentist — standard full-cycle active renewal",
    "California",
    "Dental Board of California",
    50,
    "CE units",
    24,
    CA_DENTIST_URL,
    "Dental Board of California continuing-education and renewal guidance for a standard active dentist renewal after the first renewal. Complete 50 approved units in the most recent two-year renewal period, including two units each in California infection control, the California Dental Practice Act, and responsibilities and requirements for prescribing Schedule II opioid drugs. Maintain a qualifying current Basic Life Support course with live, in-person skills practice and testing; the course is mandatory, but no more than four BLS units may count. No more than 25 units may be non-live or correspondence study, no more than 10 units may be courses primarily benefiting the licensee rather than patient care, and no more than eight units may be credited in one day. Interactive live webinars are live instruction. Hours do not carry forward. Retain certificates for three renewal periods and attest through BreEZe. The first renewal, inactive status, reduced-fee uncompensated-only practice, disability, military, hardship, and permit-specific paths are outside this standard template; when multiple licenses or permits are renewed, follow the highest applicable total rather than adding totals.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ca-dental-hygienist-2026-v1",
    "ca-dental-hygienist",
    1,
    "Dental",
    "Registered Dental Hygienist — standard full-cycle active renewal",
    "California",
    "Dental Hygiene Board of California",
    25,
    "CE units",
    24,
    CA_DENTAL_HYGIENIST_URL,
    "Dental Hygiene Board of California continuing-education guidance for a standard active Registered Dental Hygienist or Registered Dental Hygienist in Extended Functions renewal after the first renewal. Complete 25 approved units in the most recent two-year renewal period, including two units each in California infection control and the California Dental Practice Act. Maintain a qualifying current Basic Life Support course with live, in-person skills practice and testing; the course is mandatory, but no more than four BLS units may count. No more than 12.5 units may be correspondence or other non-live study, no more than five units may be courses primarily benefiting the licensee rather than patient care, and no more than eight units may be credited in one day. Hours do not carry forward. Retain certificates for three renewal periods and attest at renewal. The first renewal, inactive or reactivation status, disability, and other exception paths require separate review. An RDHAP renewal requires 35 units and is outside this 25-unit RDH/RDHEF template; dual credentials use the highest applicable total rather than adding totals.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-dentist-2026-v1",
    "fl-dentist",
    1,
    "Dental",
    "Dentist — standard full-biennium renewal",
    "Florida",
    "Florida Board of Dentistry",
    30,
    "CE hours",
    24,
    FL_DENTIST_URL,
    "Florida Board of Dentistry renewal guidance and Rule 64B5-12 for a standard full biennium. Complete 30 hours, classified as no more than 28 General Dentistry hours plus at least two hours in Prevention of Medical Errors. A Board-approved two-hour Safe and Effective Prescribing of Controlled Substances course is required every renewal and may count within the 30. Domestic Violence is due every third biennium within the 30. Maintain current live CPR certification; CPR carries no numeric credit in this template. The first renewal is a materially different four-hour plan consisting of two hours each in controlled-substance prescribing and HIV/AIDS and is outside this full-cycle template. No CE carries forward. Confirm every completion and any applicable sedation-permit requirement in CE Broker before renewing through MQA. Faculty, residency, volunteer-service, military, inactive, and other exemption or waiver paths require separate Board review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-dental-hygienist-2026-v1",
    "fl-dental-hygienist",
    1,
    "Dental",
    "Dental Hygienist — standard full-biennium renewal",
    "Florida",
    "Florida Board of Dentistry",
    24,
    "CE hours",
    24,
    FL_DENTAL_HYGIENIST_URL,
    "Florida Board of Dentistry dental-hygienist renewal guidance and Rule 64B5-12 for a standard full biennium. Complete 24 hours, classified as no more than 22 General Dental Hygiene hours plus at least two hours in Prevention of Medical Errors. Domestic Violence is due every third biennium in addition to the standard 24, making 26 hours when applicable; activate that condition only after confirming the cadence in CE Broker. Maintain current live CPR certification. The first renewal requires only the special two-hour HIV/AIDS course and is outside this full-cycle template. No CE carries forward. Verify completions in CE Broker before renewing through MQA. Volunteer-service, military, inactive, and other exemption or waiver paths require separate Board review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-dentist-2026-v1",
    "nj-dentist",
    1,
    "Dental",
    "Dentist — standard active biennial renewal",
    "New Jersey",
    "New Jersey State Board of Dentistry",
    40,
    "CE credits",
    24,
    NJ_DENTAL_URL,
    "New Jersey State Board of Dentistry continuing-education notice and N.J.A.C. 13:30-5.1 for a standard active dentist biennium. Complete 40 credits, including three hours each in hands-on CPR and pharmacology or internal medicine, two hours in infection control and prevention, one hour in professional ethics and New Jersey law, and one hour concerning prescription opioids. Electronic-media distance learning is capped at 20 credits; live, synchronous, interactive webinars are treated as live instruction. Practice-management credit is capped at seven hours. Up to seven eligible excess general credits may carry only from the immediately preceding biennium, but current-cycle mandatory subjects, including opioids, must be completed in the current period. Record carryover only with evidence and the actual prior-period completion date. A dentist holding a qualifying sedation permit completes 20 permit-related credits within the 40. Retain proof for two full biennial periods. Recent-graduate, inactive, reactivation, donated-service waiver, hardship, and Board-adjusted paths require separate review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-dental-hygienist-2026-v1",
    "nj-dental-hygienist",
    1,
    "Dental",
    "Dental Hygienist — standard active biennial renewal",
    "New Jersey",
    "New Jersey State Board of Dentistry",
    20,
    "CE credits",
    24,
    NJ_DENTAL_URL,
    "New Jersey State Board of Dentistry continuing-education notice and N.J.A.C. 13:30-5.2 for a standard active dental-hygienist biennium. Complete 20 credits, including three hours of hands-on CPR and one hour each in infection control and prevention, professional ethics and New Jersey law, and prescription opioids. Electronic-media distance learning is capped at 10 credits; live, synchronous, interactive webinars are treated as live instruction. A local-anesthesia permit holder completes four hours every other biennium within the 20. A hygienist authorized to monitor nitrous oxide completes three hours every other renewal in addition to the 20, making 23 when applicable. No carryover provision is included for dental hygienists. Retain proof for two full biennial periods. Initial, inactive, reactivation, donated-service waiver, hardship, and Board-adjusted paths require separate review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-dentist-2026-v1",
    "ny-dentist",
    1,
    "Dental",
    "Dentist — standard full triennial registration",
    "New York",
    "New York State Education Department",
    60,
    "contact hours",
    36,
    NY_DENTAL_URL,
    "New York State Education Department dentistry guidance, Education Law Article 133, and Parts 59 and 61 for a standard full three-year registration period. Complete 60 acceptable contact hours, with at least 42 through live instruction and no more than 18 through self-study. Hours do not carry forward. Track the one-time two-hour tobacco course, one-time three-hour New York dental jurisprudence and ethics course, and initial two-hour child-abuse course only if still outstanding. Complete infection-control and barrier-precautions training every four years and the updated mandated-reporter curriculum by November 17, 2026; those checkpoints use zero fixed hours because approved course duration or the 15-minute addendum may vary and License Lantern does not invent credit. A dentist with a DEA registration completes three hours in pain management, palliative care, and addiction every three years. A dental anesthesia or sedation certificate holder completes 12 approved hours per triennium and maintains the appropriate current life-support credential. Across CPR, BLS, ACLS, and PALS coursework, no more than 12 hours may count; per-course ceilings are three hours for CPR, four and one-half for CPR/AED or BLS, 12 for initial ACLS/PALS, and six for ACLS recertification. NYSED's published guidance does not specify countable PALS-recertification credit, so this template does not auto-count it; confirm directly with NYSED before relying on it. Maintain current in-person CPR and retain CE records for six years. The initial registration, shortened or prorated periods, inactive or reactivation status, endorsement, conditional registration, and exemptions require separate calculation or NYSED review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-dental-hygienist-2026-v1",
    "ny-dental-hygienist",
    1,
    "Dental",
    "Dental Hygienist — standard full triennial registration",
    "New York",
    "New York State Education Department",
    24,
    "contact hours",
    36,
    NY_DENTAL_URL,
    "New York State Education Department dentistry guidance, Education Law Article 133, and Parts 59 and 61 for a standard full three-year dental-hygiene registration period. Complete 24 acceptable contact hours, with at least 14 through live instruction and no more than 10 through self-study. Hours do not carry forward. Track the initial two-hour child-abuse course only if it remains outstanding. Complete infection-control and barrier-precautions training every four years and the updated mandated-reporter curriculum by November 17, 2026; those checkpoints use zero fixed hours because approved course duration or the 15-minute addendum may vary and License Lantern does not invent credit. Across CPR, BLS, ACLS, and PALS coursework, no more than 12 hours may count; per-course ceilings are three hours for CPR, four and one-half for CPR/AED or BLS, 12 for initial ACLS/PALS, and six for ACLS recertification. NYSED's published guidance does not specify countable PALS-recertification credit, so this template does not auto-count it; confirm directly with NYSED before relying on it. Retain CE records for six years. The initial registration, shortened or prorated periods, inactive or reactivation status, endorsement, conditional registration, and exemptions require separate calculation or NYSED review. Renewal of a restricted local-infiltration-anesthesia or nitrous-oxide certificate does not add a recurring numeric CE category to this template.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "pa-dentist-2026-v1",
    "pa-dentist",
    1,
    "Dental",
    "Dentist — standard full biennial renewal",
    "Pennsylvania",
    "Pennsylvania State Board of Dentistry",
    30,
    "CE credit hours",
    24,
    PA_DENTIST_URL,
    "Pennsylvania State Board of Dentistry renewal guidance and 49 Pa. Code Subchapter F for a standard full biennium. Complete 30 approved credit hours in the preceding biennial period, including two hours of approved child-abuse recognition and reporting; the provider reports Act 31 completion electronically. A dentist who holds a DEA registration or prescribes under another person's DEA registration completes two hours of opioid education within the 30. At least 15 hours must be lecture or clinical presentation and no more than 15 may be individual study, instruction, or authorship; a fully interactive real-time webinar is treated as lecture. Maintain current hands-on infant, child, and adult CPR, but CPR hours cannot count toward the 30. An unrestricted or Restricted I anesthesia-permit holder completes 15 permit-related hours within the 30. Hours do not carry forward. Retain records for four years and renew through PALS. The licensure-examination biennium, inactive or reactivation status, hardship waiver, Restricted II permit, and other nonstandard paths require separate review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "pa-dental-hygienist-2026-v1",
    "pa-dental-hygienist",
    1,
    "Dental",
    "Dental Hygienist — standard full biennial renewal",
    "Pennsylvania",
    "Pennsylvania State Board of Dentistry",
    20,
    "CE credit hours",
    24,
    PA_DENTAL_HYGIENIST_URL,
    "Pennsylvania State Board of Dentistry renewal guidance and 49 Pa. Code Subchapter F for a standard full dental-hygiene biennium. Complete 20 approved credit hours in the preceding biennial period, including two hours of approved child-abuse recognition and reporting; the provider reports Act 31 completion electronically. At least 10 hours must be lecture or clinical presentation and no more than 10 may be individual study, instruction, or authorship; a fully interactive real-time webinar is treated as lecture. No more than three hours may count from communication-skills courses. Maintain current hands-on infant, child, and adult CPR, but CPR hours cannot count toward the 20. A local-anesthesia permit holder completes three hours within the 20, and a Public Health Dental Hygiene Practitioner completes five public-health-related hours within the 20. Hours do not carry forward. Retain records for four years and renew through PALS. The licensure-examination biennium, inactive or reactivation status, hardship waiver, and other nonstandard paths require separate review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-dentist-2026-v1",
    "tx-dentist",
    1,
    "Dental",
    "Dentist — standard full biennial renewal without a sedation permit",
    "Texas",
    "Texas State Board of Dental Examiners",
    24,
    "CE hours",
    24,
    TX_DENTIST_URL,
    "Texas State Board of Dental Examiners Dental Practice Act and current-rules hub, including Texas Occupations Code §257.005, 22 TAC Chapter 104, and Rule 115.2, for a standard full biennial dentist renewal after the first renewal and without a sedation permit. Complete 24 approved hours, including at least 16 technical or scientific clinical-care hours; no more than eight risk-management hours and no more than eight self-study hours may count. Complete an HHSC-approved human-trafficking-prevention course within the 24, but the regulator fixes no numeric duration. Maintain current hands-on Basic Life Support, which does not count toward 24, and complete the TSBDE jurisprudence assessment every four years outside the 24. A dentist providing direct patient care completes at least two hours annually, and at least four hours each biennium, in safe and effective pain management within the technical or scientific requirement. Because the published authority does not define the annual boundary, License Lantern maps the two annual minimums to the first and second 12-month portions of the entered renewal cycle; confirm the Board's applicable annual boundary if the official record differs. Under Rule 115.2, a dentist who supervises a dental hygienist's laser use must first have sufficient laser training, including at least the same 12 hours of in-person education and three hours of clinical simulation required of the hygienist; this template tracks that one-time prerequisite as a zero-credit evidence checkpoint rather than inventing a recurring renewal increment. A DEA registrant completes the one-time two-hour controlled-substance prescribing and monitoring course; qualifying hours may overlap the recurring pain-management requirement and may count as risk-management credit. Up to 24 eligible excess classroom or lecture hours earned within the year immediately preceding the renewal period may carry forward. Retain proof for at least three years and attest at renewal. First renewal, retired or charity paths, sedation permits, and other exceptions require separate review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-dental-hygienist-2026-v1",
    "tx-dental-hygienist",
    1,
    "Dental",
    "Dental Hygienist — standard full biennial renewal",
    "Texas",
    "Texas State Board of Dental Examiners",
    24,
    "CE hours",
    24,
    TX_DENTAL_HYGIENIST_URL,
    "Texas State Board of Dental Examiners continuing-education guidance and Chapter 104 for a standard full biennial dental-hygienist renewal after the initial renewal. Complete 24 approved hours, including at least 16 technical or scientific clinical-care hours; no more than eight risk-management hours and no more than eight self-study hours may count. Complete an HHSC-approved human-trafficking-prevention course within the 24, but the regulator fixes no numeric duration. Maintain current hands-on Basic Life Support, which does not count toward 24, and complete the TSBDE jurisprudence assessment every four years outside the 24. A hygienist holding local-infiltration-anesthesia approval completes two additional hours every biennium, making 26 when applicable. Before first using a laser, complete the one-time 12-hour in-person qualification, including three hours of clinical simulation; because the Board source does not state that all 12 recur or add to a renewal total, this template tracks qualification without fabricating a recurring increment. Up to 24 eligible excess classroom or lecture hours earned within the year immediately preceding the renewal period may carry forward. Retain proof for at least three years and attest at renewal. Initial renewal, reinstatement, and other nonstandard paths require separate review.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

function californiaCategories(
  prefix: "ca-dentist-2026" | "ca-dental-hygienist-2026",
  ruleSetId: "ca-dentist-2026-v1" | "ca-dental-hygienist-2026-v1",
  options: {
    dentist: boolean;
    nonLiveCap: number;
    licenseeBenefitCap: number;
  },
): readonly CategorySeedBinding[] {
  const role = options.dentist ? "dentist" : "dental hygienist";
  const deliveryGroup = `California ${role} delivery mode`;
  const benefitGroup = `California ${role} course benefit`;
  const blsCreditGroup = `California ${role} BLS-credit classification`;
  const categories: CategorySeedBinding[] = [
    [
      `${prefix}-infection-control`,
      ruleSetId,
      "California Infection Control",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two units through a Dental Board-registered provider specifically authorized to offer the California Infection Control mandatory course.",
      null,
      0,
    ],
    [
      `${prefix}-dental-practice-act`,
      ruleSetId,
      "California Dental Practice Act",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two units through a Dental Board-registered provider specifically authorized to offer the California Dental Practice Act mandatory course; a general HIPAA course is not a substitute.",
      null,
      1,
    ],
  ];
  if (options.dentist) {
    categories.push([
      `${prefix}-schedule-ii-opioids`,
      ruleSetId,
      "Responsibilities and Requirements for Prescribing Schedule II Opioid Drugs",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete the two-unit California Board-approved mandatory course every renewal, including when the dentist does not prescribe. Federal MATE training does not automatically substitute for this California course.",
      null,
      2,
    ]);
  }
  const nextSort = categories.length;
  categories.push(
    [
      `${prefix}-current-bls`,
      ruleSetId,
      "Current Qualifying Basic Life Support",
      0,
      "informational",
      "overlapping",
      null,
      "always",
      "Maintain a current qualifying BLS course completed during the renewal period with a live, in-person skills-practice session, skills test, and written examination. Online-only BLS is not accepted. Track any countable BLS units separately under the four-unit cap.",
      null,
      nextSort,
    ],
    [
      `${prefix}-live-interactive`,
      ruleSetId,
      "Live or Interactive CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      `Classify live lecture, live workshop, or interactive real-time instruction here. With every activity classified and Non-Live or Correspondence CE capped at ${options.nonLiveCap}, the required live share is enforced.`,
      deliveryGroup,
      nextSort + 1,
    ],
    [
      `${prefix}-nonlive-correspondence`,
      ruleSetId,
      "Non-Live or Correspondence CE",
      options.nonLiveCap,
      "maximum",
      "independent",
      null,
      "optional",
      `No more than 50% of the renewal total (${options.nonLiveCap} units) may be correspondence, recorded, on-demand, home-study, computer, or other non-live instruction. Classify every activity by delivery mode.`,
      deliveryGroup,
      nextSort + 2,
    ],
    [
      `${prefix}-patient-practice-benefit`,
      ruleSetId,
      "Patient-Care or Practice-Related CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify eligible patient-care, clinical, or practice-related education here unless it is a course primarily benefiting the licensee. Courses only of direct personal benefit or outside California dental practice do not count.",
      benefitGroup,
      nextSort + 3,
    ],
    [
      `${prefix}-licensee-benefit`,
      ruleSetId,
      "Courses Primarily Benefiting the Licensee",
      options.licenseeBenefitCap,
      "maximum",
      "independent",
      null,
      "optional",
      `No more than 20% of the renewal total (${options.licenseeBenefitCap} units) may be courses such as practice or human-resource management, leadership, or team development that primarily benefit the licensee. Classify every activity by course benefit.`,
      benefitGroup,
      nextSort + 4,
    ],
    [
      `${prefix}-non-bls-credit`,
      ruleSetId,
      "Non-BLS Eligible CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify eligible education that is not the qualifying Basic Life Support course here. Every activity must use one BLS-credit classification so the four-unit BLS cap cannot be bypassed.",
      blsCreditGroup,
      nextSort + 5,
    ],
    [
      `${prefix}-bls-credit`,
      ruleSetId,
      "Basic Life Support Credit",
      4,
      "maximum",
      "overlapping",
      null,
      "optional",
      "No more than four units from the qualifying BLS course may count toward the renewal total. The current BLS credential remains mandatory regardless of the course's awarded units.",
      blsCreditGroup,
      nextSort + 6,
    ],
  );
  return categories;
}

const FL_DENTIST_CREDIT_BUCKET_GROUP =
  "Florida dentist continuing-education bucket";
const FL_DENTAL_HYGIENIST_CREDIT_BUCKET_GROUP =
  "Florida dental hygienist continuing-education bucket";

function floridaDentistCategories(): readonly CategorySeedBinding[] {
  return [
    [
      "fl-dentist-2026-general",
      "fl-dentist-2026-v1",
      "General Dentistry CE",
      28,
      "maximum",
      "independent",
      null,
      "always",
      "Classify ordinary approved dentist CE here. No more than 28 of the 30 hours may occupy the General Dentistry bucket because two separately classified Medical Errors hours are required.",
      FL_DENTIST_CREDIT_BUCKET_GROUP,
      0,
    ],
    [
      "fl-dentist-2026-medical-errors",
      "fl-dentist-2026-v1",
      "Prevention of Medical Errors",
      2,
      "minimum",
      "independent",
      null,
      "always",
      "Complete and separately classify two Board-approved hours in Prevention of Medical Errors every biennium.",
      FL_DENTIST_CREDIT_BUCKET_GROUP,
      1,
    ],
    [
      "fl-dentist-2026-controlled-substances",
      "fl-dentist-2026-v1",
      "Safe and Effective Prescribing of Controlled Substances",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two hours in the Board-approved course every renewal. These hours may be part of the 30-hour total and should also be classified into the proper General or Medical Errors credit bucket.",
      null,
      2,
    ],
    [
      "fl-dentist-2026-domestic-violence",
      "fl-dentist-2026-v1",
      "Domestic Violence — every third biennium",
      2,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Required every third biennium. Confirm the assigned cadence in CE Broker; for dentists these two hours remain within the 30-hour total.",
      null,
      3,
    ],
    [
      "fl-dentist-2026-current-cpr",
      "fl-dentist-2026-v1",
      "Current Live CPR Certification",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Maintain current CPR certification completed through a live course. This checkpoint carries no numeric CE credit in the standard plan.",
      null,
      4,
    ],
    [
      "fl-dentist-2026-hiv-aids-first-renewal",
      "fl-dentist-2026-v1",
      "HIV/AIDS — first-renewal special-plan checkpoint",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "The first renewal uses a special four-hour plan—two hours of HIV/AIDS and two hours of controlled-substance prescribing—not this standard 30-hour template. Activate only as a reminder to replace this credential with a custom first-renewal plan.",
      null,
      5,
    ],
    [
      "fl-dentist-2026-sedation-permit",
      "fl-dentist-2026-v1",
      "Sedation-Permit Continuing Education",
      4,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Potential four-hour permit overlay within the 30-hour total. The public dentist-renewal summary does not fully identify every sedation or anesthesia permit and renewal condition; confirm the current permit-specific requirement with the Board and CE Broker before activating or relying on this category.",
      null,
      6,
    ],
  ];
}

function floridaDentalHygienistCategories(): readonly CategorySeedBinding[] {
  return [
    [
      "fl-dental-hygienist-2026-general",
      "fl-dental-hygienist-2026-v1",
      "General Dental Hygiene CE",
      22,
      "maximum",
      "independent",
      null,
      "always",
      "Classify ordinary approved dental-hygiene CE here. No more than 22 of the standard 24 hours may occupy the General Dental Hygiene bucket because two separately classified Medical Errors hours are required.",
      FL_DENTAL_HYGIENIST_CREDIT_BUCKET_GROUP,
      0,
    ],
    [
      "fl-dental-hygienist-2026-medical-errors",
      "fl-dental-hygienist-2026-v1",
      "Prevention of Medical Errors",
      2,
      "minimum",
      "independent",
      null,
      "always",
      "Complete and separately classify two Board-approved hours in Prevention of Medical Errors every biennium.",
      FL_DENTAL_HYGIENIST_CREDIT_BUCKET_GROUP,
      1,
    ],
    [
      "fl-dental-hygienist-2026-domestic-violence",
      "fl-dental-hygienist-2026-v1",
      "Domestic Violence — additional two hours every third biennium",
      2,
      "minimum",
      "independent",
      null,
      "conditional",
      "Required every third biennium in addition to the standard 24 hours. Confirm the assigned cadence in CE Broker; activating this condition raises the credential total to 26.",
      null,
      2,
    ],
    [
      "fl-dental-hygienist-2026-current-cpr",
      "fl-dental-hygienist-2026-v1",
      "Current Live CPR Certification",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Maintain current CPR certification completed through a live course. This checkpoint carries no numeric CE credit in the standard plan.",
      null,
      3,
    ],
    [
      "fl-dental-hygienist-2026-hiv-aids-first-renewal",
      "fl-dental-hygienist-2026-v1",
      "HIV/AIDS — first-renewal special-plan checkpoint",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "The first renewal requires the special two-hour HIV/AIDS course rather than this standard 24-hour template. Activate only as a reminder to replace this credential with a custom first-renewal plan.",
      null,
      4,
    ],
  ];
}

const NJ_DENTIST_DELIVERY_GROUP = "New Jersey dentist delivery mode";
const NJ_DENTIST_PERIOD_SOURCE_GROUP = "New Jersey dentist period source";
const NJ_DENTIST_SUBJECT_LIMIT_GROUP =
  "New Jersey dentist subject-limit classification";
const NJ_DENTAL_HYGIENIST_DELIVERY_GROUP =
  "New Jersey dental hygienist delivery mode";

function newJerseyDentistCategories(): readonly CategorySeedBinding[] {
  return [
    [
      "nj-dentist-2026-live-interactive",
      "nj-dentist-2026-v1",
      "Live, In-Person, or Synchronous Interactive CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify live instruction here, including a synchronous webinar that permits real-time instructor interaction. With every activity classified and distance learning capped at 20, the live share is enforced.",
      NJ_DENTIST_DELIVERY_GROUP,
      0,
    ],
    [
      "nj-dentist-2026-distance-learning",
      "nj-dentist-2026-v1",
      "Electronic-Media Distance Learning",
      20,
      "maximum",
      "independent",
      null,
      "optional",
      "No more than 20 credits may be electronic-media distance learning. A recorded program must include a post-test, and proof of the post-test must be retained. Classify every activity by delivery mode.",
      NJ_DENTIST_DELIVERY_GROUP,
      1,
    ],
    [
      "nj-dentist-2026-current-period",
      "nj-dentist-2026-v1",
      "Current-Period Eligible Dental CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Use this period-source classifier for eligible credits completed during the current biennium. Select each applicable current-cycle mandatory topic separately.",
      NJ_DENTIST_PERIOD_SOURCE_GROUP,
      2,
    ],
    [
      "nj-dentist-2026-confirmed-carryover",
      "nj-dentist-2026-v1",
      "Board-Eligible Confirmed General-Credit Carryover",
      7,
      "maximum",
      "independent",
      null,
      "conditional",
      "At most seven eligible excess general credits may carry from the immediately preceding biennium. Record only evidence-backed credit with its actual prior-period completion date. Carryover cannot satisfy current-cycle mandatory subjects, and opioid credit expressly cannot carry.",
      NJ_DENTIST_PERIOD_SOURCE_GROUP,
      3,
    ],
    [
      "nj-dentist-2026-other-approved-subject",
      "nj-dentist-2026-v1",
      "Clinical or Other Approved Dental CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify eligible clinical and other approved dental education here unless it is primarily practice management. Every activity must use one subject-limit classification.",
      NJ_DENTIST_SUBJECT_LIMIT_GROUP,
      4,
    ],
    [
      "nj-dentist-2026-practice-management",
      "nj-dentist-2026-v1",
      "Practice-Management CE",
      7,
      "maximum",
      "independent",
      null,
      "optional",
      "No more than seven credits may count for practice-management education. Classify every activity by subject-limit type.",
      NJ_DENTIST_SUBJECT_LIMIT_GROUP,
      5,
    ],
    [
      "nj-dentist-2026-cpr",
      "nj-dentist-2026-v1",
      "Hands-On Cardiopulmonary Resuscitation",
      3,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete three hours in CPR through a hands-on course during the current biennium.",
      null,
      6,
    ],
    [
      "nj-dentist-2026-pharmacology-internal-medicine",
      "nj-dentist-2026-v1",
      "Pharmacology and Internal Medicine",
      3,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete three current-biennium credits in pharmacology and internal medicine.",
      null,
      7,
    ],
    [
      "nj-dentist-2026-infection-control",
      "nj-dentist-2026-v1",
      "Infection Control and Prevention",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two current-biennium credits in infection control and prevention.",
      null,
      8,
    ],
    [
      "nj-dentist-2026-ethics-law",
      "nj-dentist-2026-v1",
      "Professional Ethics and New Jersey Law",
      1,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete one current-biennium credit in professional ethics and New Jersey law.",
      null,
      9,
    ],
    [
      "nj-dentist-2026-prescription-opioids",
      "nj-dentist-2026-v1",
      "Prescription Opioids",
      1,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete one current-biennium credit concerning prescription opioids. This mandatory credit may not be carried from the prior biennium.",
      null,
      10,
    ],
    [
      "nj-dentist-2026-sedation-permit",
      "nj-dentist-2026-v1",
      "Sedation-Permit Continuing Education",
      20,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Applies to a dentist renewing a qualifying Board sedation permit. Complete 20 permit-related credits within—not in addition to—the 40-credit dentist total, and confirm the exact permit scope with the Board.",
      null,
      11,
    ],
  ];
}

function newJerseyDentalHygienistCategories(): readonly CategorySeedBinding[] {
  return [
    [
      "nj-dental-hygienist-2026-live-interactive",
      "nj-dental-hygienist-2026-v1",
      "Live, In-Person, or Synchronous Interactive CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify live instruction here, including a synchronous webinar that permits real-time instructor interaction. With every activity classified and distance learning capped at 10, the live share is enforced.",
      NJ_DENTAL_HYGIENIST_DELIVERY_GROUP,
      0,
    ],
    [
      "nj-dental-hygienist-2026-distance-learning",
      "nj-dental-hygienist-2026-v1",
      "Electronic-Media Distance Learning",
      10,
      "maximum",
      "independent",
      null,
      "optional",
      "No more than 10 credits may be electronic-media distance learning. A recorded program must include a post-test, and proof of the post-test must be retained. Classify every activity by delivery mode.",
      NJ_DENTAL_HYGIENIST_DELIVERY_GROUP,
      1,
    ],
    [
      "nj-dental-hygienist-2026-cpr",
      "nj-dental-hygienist-2026-v1",
      "Hands-On Cardiopulmonary Resuscitation",
      3,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete three hours in CPR through a hands-on course during the current biennium.",
      null,
      2,
    ],
    [
      "nj-dental-hygienist-2026-infection-control",
      "nj-dental-hygienist-2026-v1",
      "Infection Control and Prevention",
      1,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete one current-biennium credit in infection control and prevention.",
      null,
      3,
    ],
    [
      "nj-dental-hygienist-2026-ethics-law",
      "nj-dental-hygienist-2026-v1",
      "Professional Ethics and New Jersey Law",
      1,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete one current-biennium credit in professional ethics and New Jersey law.",
      null,
      4,
    ],
    [
      "nj-dental-hygienist-2026-prescription-opioids",
      "nj-dental-hygienist-2026-v1",
      "Prescription Opioids",
      1,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete one current-biennium credit concerning prescription opioids.",
      null,
      5,
    ],
    [
      "nj-dental-hygienist-2026-local-anesthesia-permit",
      "nj-dental-hygienist-2026-v1",
      "Local-Anesthesia Permit — every other biennium",
      4,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Applies every other biennium to a hygienist maintaining a local-anesthesia permit. Complete four permit-related credits within the standard 20 and confirm the cadence with the Board.",
      null,
      6,
    ],
    [
      "nj-dental-hygienist-2026-nitrous-monitoring",
      "nj-dental-hygienist-2026-v1",
      "Nitrous-Oxide Monitoring — additional three hours every other renewal",
      3,
      "minimum",
      "independent",
      null,
      "conditional",
      "Applies every other renewal to a hygienist authorized to monitor nitrous oxide. These three hours are in addition to the standard 20; activating this condition raises the credential total to 23. Confirm the cadence with the Board.",
      null,
      7,
    ],
  ];
}

function newYorkCategories(
  prefix: "ny-dentist-2026" | "ny-dental-hygienist-2026",
  ruleSetId: "ny-dentist-2026-v1" | "ny-dental-hygienist-2026-v1",
  options: { dentist: boolean; selfStudyCap: number },
): readonly CategorySeedBinding[] {
  const role = options.dentist ? "dentist" : "dental hygienist";
  const deliveryGroup = `New York ${role} delivery mode`;
  const categories: CategorySeedBinding[] = [
    [
      `${prefix}-live-interactive`,
      ruleSetId,
      "Live or Interactive CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      `Classify instruction that permits real-time interaction with the instructor here. With every activity classified and Self-Study capped at ${options.selfStudyCap}, the required live share is enforced.`,
      deliveryGroup,
      0,
    ],
    [
      `${prefix}-self-study`,
      ruleSetId,
      "Self-Study CE",
      options.selfStudyCap,
      "maximum",
      "independent",
      null,
      "optional",
      `No more than ${options.selfStudyCap} contact hours may be self-study in a full registration period. Classify every activity by delivery mode.`,
      deliveryGroup,
      1,
    ],
  ];
  if (options.dentist) {
    categories.push(
      [
        `${prefix}-tobacco`,
        ruleSetId,
        "Tobacco and Oral-Health Effects — one-time course",
        2,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "One-time two-hour requirement. Mark Applies only if NYSED does not already recognize completion or an applicable exemption; the hours remain within the 60.",
        null,
        2,
      ],
      [
        `${prefix}-jurisprudence-ethics`,
        ruleSetId,
        "New York Dental Jurisprudence and Ethics — one-time course",
        3,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "One-time three-hour NYSED-approved course. Mark Applies only if it remains outstanding; the hours remain within the 60.",
        null,
        3,
      ],
    );
  }
  const nextSort = categories.length;
  categories.push(
    [
      `${prefix}-initial-child-abuse`,
      ruleSetId,
      "Child-Abuse Identification and Reporting — initial two-hour training",
      2,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "One-time two-hour requirement unless NYSED already recognizes completion through an approved professional program or provider, or an exemption applies. A qualifying full updated-curriculum course may satisfy both child-abuse duties; the 15-minute addendum alone does not create a new two-hour course.",
      null,
      nextSort,
    ],
    [
      `${prefix}-infection-control`,
      ruleSetId,
      "Infection Control and Barrier Precautions — four-year training",
      0,
      "informational",
      "overlapping",
      null,
      "conditional",
      "Complete NYSED-approved training appropriate to practice every four years unless NYSED accepts equivalent recent training or grants an exemption. Approved course length varies; count actual CE only when separately eligible and retain the certificate.",
      null,
      nextSort + 1,
    ],
    [
      `${prefix}-updated-child-abuse`,
      ruleSetId,
      "Child-Abuse Mandated-Reporter Training — 2026 updated curriculum",
      0,
      "informational",
      "overlapping",
      null,
      "conditional",
      "Complete the updated curriculum by November 17, 2026 even if previously trained. Training completed from November 1, 2022 through August 31, 2025 may use the official 15-minute addendum. This zero-value checkpoint avoids converting that addendum into a fabricated contact hour.",
      null,
      nextSort + 2,
    ],
  );
  if (options.dentist) {
    categories.push(
      [
        `${prefix}-dea-prescriber`,
        ruleSetId,
        "DEA Prescriber Education — three-year cycle",
        3,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to a dentist with a DEA registration. Complete at least three hours in pain management, palliative care, and addiction every three years. Count within the 60 only when the selected course separately meets NYSED CE standards, and complete the separate Department of Health attestation.",
        null,
        nextSort + 3,
      ],
      [
        `${prefix}-anesthesia-sedation-certificate`,
        ruleSetId,
        "Dental Anesthesia or Sedation Certificate",
        12,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to a dentist renewing a New York dental anesthesia or sedation certificate. Complete 12 clock hours of NYSED-approved anesthesia or sedation education; qualifying hours remain within the 60. Maintain any required current ACLS or PALS documentation separately.",
        null,
        nextSort + 4,
      ],
      [
        `${prefix}-current-cpr`,
        ruleSetId,
        "Current In-Person CPR",
        0,
        "informational",
        "overlapping",
        null,
        "always",
        "Maintain current qualifying CPR completed live and in person. Record actual countable CPR, ACLS, or PALS hours only when the course meets NYSED rules; this checkpoint does not invent a fixed course duration.",
        null,
        nextSort + 5,
      ],
    );
  } else {
    categories.push([
      `${prefix}-restricted-anesthesia-nitrous-certificate`,
      ruleSetId,
      "Restricted Local-Anesthesia or Nitrous-Oxide Certificate",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "Track the separate three-year certificate renewal, form, and fee when applicable. New York does not prescribe an additional recurring CE-hour minimum for this restricted dental-hygiene certificate.",
      null,
      nextSort + 3,
    ]);
  }
  const cardiopulmonaryGroup =
    `New York ${role} cardiopulmonary-credit classification`;
  const cardiopulmonarySubtypeGroup =
    `New York ${role} cardiopulmonary course subtype`;
  const cardiopulmonarySort =
    Math.max(...categories.map((category) => category[10])) + 1;
  categories.push(
    [
      `${prefix}-other-acceptable-ce`,
      ruleSetId,
      "Other Acceptable Dental CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify acceptable coursework that is not CPR, BLS, ACLS, or PALS here. Every activity must use one cardiopulmonary-credit classification so the combined 12-hour ceiling cannot be bypassed.",
      cardiopulmonaryGroup,
      cardiopulmonarySort,
    ],
    [
      `${prefix}-cardiopulmonary-credit`,
      ruleSetId,
      "Combined CPR, BLS, ACLS, and PALS Credit",
      12,
      "maximum",
      "overlapping",
      null,
      "optional",
      "No more than 12 combined hours of CPR, BLS, ACLS, and PALS coursework may count in one triennial registration period. Also choose the actual course subtype so its per-course ceiling is enforced.",
      cardiopulmonaryGroup,
      cardiopulmonarySort + 1,
    ],
    [
      `${prefix}-cpr-course`,
      ruleSetId,
      "CPR Course — per-record ceiling",
      0,
      "informational",
      "overlapping",
      null,
      "optional",
      "Use with Combined CPR, BLS, ACLS, and PALS Credit for an ordinary CPR course. No more than three hours from this individual course record may count.",
      cardiopulmonarySubtypeGroup,
      cardiopulmonarySort + 2,
    ],
    [
      `${prefix}-cpr-aed-bls-course`,
      ruleSetId,
      "CPR/AED or BLS Course — per-record ceiling",
      0,
      "informational",
      "overlapping",
      null,
      "optional",
      "Use with Combined CPR, BLS, ACLS, and PALS Credit for a CPR course including AED or for BLS. No more than four and one-half hours from this individual course record may count.",
      cardiopulmonarySubtypeGroup,
      cardiopulmonarySort + 3,
    ],
    [
      `${prefix}-initial-acls-pals-course`,
      ruleSetId,
      "Initial ACLS or PALS Course — per-record ceiling",
      0,
      "informational",
      "overlapping",
      null,
      "optional",
      "Use with Combined CPR, BLS, ACLS, and PALS Credit for an initial ACLS or PALS course. No more than 12 hours from this individual course record may count.",
      cardiopulmonarySubtypeGroup,
      cardiopulmonarySort + 4,
    ],
    [
      `${prefix}-acls-recertification-course`,
      ruleSetId,
      "ACLS Recertification Course — per-record ceiling",
      0,
      "informational",
      "overlapping",
      null,
      "optional",
      "Use with Combined CPR, BLS, ACLS, and PALS Credit for ACLS recertification. No more than six hours from this individual course record may count.",
      cardiopulmonarySubtypeGroup,
      cardiopulmonarySort + 5,
    ],
  );
  return categories;
}

function pennsylvaniaCategories(
  prefix: "pa-dentist-2026" | "pa-dental-hygienist-2026",
  ruleSetId: "pa-dentist-2026-v1" | "pa-dental-hygienist-2026-v1",
  options: { dentist: boolean; individualStudyCap: number },
): readonly CategorySeedBinding[] {
  const role = options.dentist ? "dentist" : "dental hygienist";
  const deliveryGroup = `Pennsylvania ${role} learning format`;
  const subjectGroup = `Pennsylvania ${role} subject-limit classification`;
  const categories: CategorySeedBinding[] = [
    [
      `${prefix}-lecture-clinical`,
      ruleSetId,
      "Lecture or Clinical Presentation",
      0,
      "informational",
      "independent",
      null,
      "always",
      `Classify lecture, clinical presentation, or fully interactive real-time webinar credit here. With every activity classified and Individual Study, Instruction, or Authorship capped at ${options.individualStudyCap}, the required 50% lecture or clinical share is enforced.`,
      deliveryGroup,
      0,
    ],
    [
      `${prefix}-individual-study`,
      ruleSetId,
      "Individual Study, Instruction, or Authorship",
      options.individualStudyCap,
      "maximum",
      "independent",
      null,
      "optional",
      `No more than 50% of the renewal total (${options.individualStudyCap} hours) may come from individual study, serving as an instructor, or qualifying authorship. Classify every activity by learning format.`,
      deliveryGroup,
      1,
    ],
    [
      `${prefix}-child-abuse`,
      ruleSetId,
      "Child Abuse Recognition and Reporting",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two hours through a Pennsylvania-approved Act 31 provider every biennium. The provider reports completion electronically; retain your own proof.",
      null,
      2,
    ],
    [
      `${prefix}-current-cpr`,
      ruleSetId,
      "Current Hands-On Infant, Child, and Adult CPR",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Maintain current hands-on CPR covering infant, child, and adult techniques. CPR certification hours are expressly excluded from the numeric CE total.",
      null,
      3,
    ],
  ];
  if (options.dentist) {
    categories.push(
      [
        `${prefix}-opioid-education`,
        ruleSetId,
        "Opioid Education for a Dentist Using a DEA Registration",
        2,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies when the dentist holds a DEA registration or prescribes controlled substances under another person's DEA registration. Complete two hours within the 30; confirm the no-DEA exemption before marking Not this cycle.",
        null,
        4,
      ],
      [
        `${prefix}-anesthesia-permit`,
        ruleSetId,
        "Unrestricted or Restricted I Anesthesia Permit",
        15,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to an unrestricted or Restricted I permit holder. Complete 15 Board-approved hours related to the applicable anesthesia or sedation level within—not in addition to—the 30-hour dentist total. Restricted II follows a different permit rule.",
        null,
        5,
      ],
    );
  } else {
    categories.push(
      [
        `${prefix}-other-approved-subject`,
        ruleSetId,
        "Clinical or Other Approved Dental-Hygiene CE",
        0,
        "informational",
        "independent",
        null,
        "always",
        "Classify eligible dental-hygiene education here unless it is primarily a communication-skills course. Every activity must use one subject-limit classification.",
        subjectGroup,
        4,
      ],
      [
        `${prefix}-communication-skills`,
        ruleSetId,
        "Communication-Skills CE",
        3,
        "maximum",
        "independent",
        null,
        "optional",
        "No more than three of the required 20 hours may count from communication-skills courses. Classify every activity by subject-limit type.",
        subjectGroup,
        5,
      ],
      [
        `${prefix}-local-anesthesia-permit`,
        ruleSetId,
        "Local-Anesthesia Permit",
        3,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to a dental hygienist holding a local-anesthesia permit. Complete three hours related to local-anesthesia administration, pharmacology, or a related subject within the 20.",
        null,
        6,
      ],
      [
        `${prefix}-phdhp`,
        ruleSetId,
        "Public Health Dental Hygiene Practitioner",
        5,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to a certified Public Health Dental Hygiene Practitioner. Complete five public-health-related hours within the 20.",
        null,
        7,
      ],
    );
  }
  return categories;
}

function texasCategories(
  prefix: "tx-dentist-2026" | "tx-dental-hygienist-2026",
  ruleSetId: "tx-dentist-2026-v1" | "tx-dental-hygienist-2026-v1",
  dentist: boolean,
): readonly CategorySeedBinding[] {
  const role = dentist ? "dentist" : "dental hygienist";
  const contentGroup = `Texas ${role} CE content type`;
  const deliveryGroup = `Texas ${role} CE delivery mode`;
  const periodGroup = `Texas ${role} CE period source`;
  const categories: CategorySeedBinding[] = [
    [
      `${prefix}-technical-scientific`,
      ruleSetId,
      "Technical or Scientific Clinical-Care CE",
      16,
      "minimum",
      "independent",
      null,
      "always",
      "At least 16 of the 24 hours must have significant intellectual or practical content that directly enhances knowledge and skill in clinical patient care. Classify every countable activity as Technical or Scientific or Risk Management.",
      contentGroup,
      0,
    ],
    [
      `${prefix}-risk-management`,
      ruleSetId,
      "Risk-Management CE",
      8,
      "maximum",
      "independent",
      null,
      "optional",
      "No more than eight hours may be risk-management education, including qualifying recordkeeping, HIPAA, or ethics coursework. Classify every countable activity by content type.",
      contentGroup,
      1,
    ],
    [
      `${prefix}-classroom-live`,
      ruleSetId,
      "Classroom, Lecture, or Live Interactive CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Classify classroom, lecture, or live interactive instruction here. Only eligible classroom or lecture excess credit can carry forward.",
      deliveryGroup,
      2,
    ],
    [
      `${prefix}-self-study`,
      ruleSetId,
      "Self-Study CE",
      8,
      "maximum",
      "independent",
      null,
      "optional",
      "No more than eight hours may be Board-provider self-study, including correspondence, video, audio, or reading courses. Classify every activity by delivery mode.",
      deliveryGroup,
      3,
    ],
    [
      `${prefix}-current-period`,
      ruleSetId,
      "Current-Period Eligible Dental CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Use this period-source classifier for eligible hours earned during the current renewal period.",
      periodGroup,
      4,
    ],
    [
      `${prefix}-confirmed-carryover`,
      ruleSetId,
      "Board-Eligible Confirmed Carryover",
      24,
      "maximum",
      "independent",
      null,
      "conditional",
      "At most 24 eligible excess classroom or lecture hours may carry forward when earned within the one year immediately preceding the current renewal period. Record only evidence-backed credit with its actual prior-period completion date; License Lantern never copies credit automatically.",
      periodGroup,
      5,
    ],
    [
      `${prefix}-human-trafficking`,
      ruleSetId,
      "HHSC-Approved Human Trafficking Prevention Course",
      0,
      "informational",
      "overlapping",
      null,
      "always",
      "Complete a course currently listed by HHSC for this renewal. The Board fixes no numeric duration; count actual hours toward 24 only when the selected course separately awards Board-acceptable CE.",
      null,
      6,
    ],
    [
      `${prefix}-jurisprudence`,
      ruleSetId,
      "TSBDE Jurisprudence Assessment — four-year cycle",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "Complete the TSBDE jurisprudence assessment every four years. It is additional to and may not count toward the 24. A dentist with a sedation permit follows the anesthesia-jurisprudence cadence instead and requires a separate permit plan.",
      null,
      7,
    ],
    [
      `${prefix}-current-bls`,
      ruleSetId,
      "Current Hands-On Basic Life Support",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Maintain current qualifying hands-on BLS. Basic CPR/BLS and OSHA-update hours may not count toward the 24.",
      null,
      8,
    ],
  ];
  if (dentist) {
    categories.push(
      [
        `${prefix}-pain-management`,
        ruleSetId,
        "Safe and Effective Pain Management — biennial aggregate",
        4,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to a dentist whose practice includes direct patient care. Complete at least four hours during the biennium. This aggregate is calculated from the two annual child categories; classify each qualifying activity to its actual renewal year rather than tagging this parent directly.",
        null,
        9,
      ],
      [
        `${prefix}-pain-management-year-1`,
        ruleSetId,
        "Safe and Effective Pain Management — first renewal year",
        2,
        "minimum",
        "nested",
        `${prefix}-pain-management`,
        "conditional",
        "Applies to a dentist whose practice includes direct patient care. Complete at least two hours during the first 12 months of this renewal period concerning safe and effective pain management for opioids and other controlled substances. These hours may satisfy the technical or scientific minimum.",
        null,
        10,
      ],
      [
        `${prefix}-pain-management-year-2`,
        ruleSetId,
        "Safe and Effective Pain Management — second renewal year",
        2,
        "minimum",
        "nested",
        `${prefix}-pain-management`,
        "conditional",
        "Applies to a dentist whose practice includes direct patient care. Complete at least two hours during the second 12 months of this renewal period. The two annual categories enforce the four-hour biennial total without treating four hours completed in one year as sufficient.",
        null,
        11,
      ],
      [
        `${prefix}-dea-controlled-substances`,
        ruleSetId,
        "DEA Controlled-Substance Prescribing and Monitoring — one-time course",
        2,
        "minimum",
        "overlapping",
        null,
        "conditional",
        "Applies to a dentist with a DEA registration until the one-time two-hour course has been completed. Qualifying hours may overlap the recurring pain-management requirement and may be classified as risk-management credit.",
        null,
        12,
      ],
      [
        `${prefix}-laser-supervision-qualification`,
        ruleSetId,
        "Laser Supervision — one-time pre-supervision qualification",
        0,
        "informational",
        "independent",
        null,
        "conditional",
        "Applies when the dentist supervises a dental hygienist's laser use. Before supervising, complete sufficient laser training, including at least the same 12 hours of in-person education specific to the procedures and three hours of clinical simulation required of the hygienist. Retain evidence of the one-time prerequisite; this checkpoint does not invent recurring CE credit.",
        null,
        13,
      ],
    );
  } else {
    categories.push(
      [
        `${prefix}-local-anesthesia`,
        ruleSetId,
        "Local-Infiltration-Anesthesia Approval — additional two hours",
        2,
        "minimum",
        "independent",
        null,
        "conditional",
        "Applies every biennium to a dental hygienist maintaining local-infiltration-anesthesia approval. These two hours are in addition to the standard 24; activating this condition raises the credential total to 26.",
        null,
        9,
      ],
      [
        `${prefix}-laser-qualification`,
        ruleSetId,
        "Laser Utilization — one-time pre-use qualification",
        0,
        "informational",
        "independent",
        null,
        "conditional",
        "Before first using a laser, complete at least 12 hours of in-person laser-utilization education specific to the procedures, including three hours of clinical simulation. This is a scope-of-practice qualification rather than a recurring renewal increment; retain proof and count hours toward a renewal only after confirming eligibility.",
        null,
        10,
      ],
    );
  }
  return categories;
}

export const DENTAL_CATEGORY_SEED_BINDINGS = [
  ...californiaCategories("ca-dentist-2026", "ca-dentist-2026-v1", {
    dentist: true,
    nonLiveCap: 25,
    licenseeBenefitCap: 10,
  }),
  ...californiaCategories(
    "ca-dental-hygienist-2026",
    "ca-dental-hygienist-2026-v1",
    {
      dentist: false,
      nonLiveCap: 12.5,
      licenseeBenefitCap: 5,
    },
  ),
  ...floridaDentistCategories(),
  ...floridaDentalHygienistCategories(),
  ...newJerseyDentistCategories(),
  ...newJerseyDentalHygienistCategories(),
  ...newYorkCategories("ny-dentist-2026", "ny-dentist-2026-v1", {
    dentist: true,
    selfStudyCap: 18,
  }),
  ...newYorkCategories(
    "ny-dental-hygienist-2026",
    "ny-dental-hygienist-2026-v1",
    {
      dentist: false,
      selfStudyCap: 10,
    },
  ),
  ...pennsylvaniaCategories("pa-dentist-2026", "pa-dentist-2026-v1", {
    dentist: true,
    individualStudyCap: 15,
  }),
  ...pennsylvaniaCategories(
    "pa-dental-hygienist-2026",
    "pa-dental-hygienist-2026-v1",
    {
      dentist: false,
      individualStudyCap: 10,
    },
  ),
  ...texasCategories("tx-dentist-2026", "tx-dentist-2026-v1", true),
  ...texasCategories(
    "tx-dental-hygienist-2026",
    "tx-dental-hygienist-2026-v1",
    false,
  ),
] as const satisfies readonly CategorySeedBinding[];

export const DENTAL_ADDITIONAL_TOTAL_BINDINGS = [
  [
    "fl-dental-hygienist-2026-v1",
    "fl-dental-hygienist-2026-domestic-violence",
    2,
  ],
  [
    "nj-dental-hygienist-2026-v1",
    "nj-dental-hygienist-2026-nitrous-monitoring",
    3,
  ],
  [
    "tx-dental-hygienist-2026-v1",
    "tx-dental-hygienist-2026-local-anesthesia",
    2,
  ],
] as const;

export const DENTAL_CHECKPOINT_RULE_CATEGORY_IDS = [
  "ca-dentist-2026-current-bls",
  "ca-dental-hygienist-2026-current-bls",
  "fl-dentist-2026-current-cpr",
  "fl-dental-hygienist-2026-current-cpr",
  "ny-dentist-2026-infection-control",
  "ny-dentist-2026-updated-child-abuse",
  "ny-dentist-2026-current-cpr",
  "ny-dental-hygienist-2026-infection-control",
  "ny-dental-hygienist-2026-updated-child-abuse",
  "ny-dental-hygienist-2026-restricted-anesthesia-nitrous-certificate",
  "pa-dentist-2026-current-cpr",
  "pa-dental-hygienist-2026-current-cpr",
  "tx-dentist-2026-human-trafficking",
  "tx-dentist-2026-jurisprudence",
  "tx-dentist-2026-current-bls",
  "tx-dentist-2026-laser-supervision-qualification",
  "tx-dental-hygienist-2026-human-trafficking",
  "tx-dental-hygienist-2026-jurisprudence",
  "tx-dental-hygienist-2026-current-bls",
  "tx-dental-hygienist-2026-laser-qualification",
] as const;

export const DENTAL_DAILY_UNIT_LIMIT_BINDINGS = [
  ["ca-dentist-2026-v1", 8],
  ["ca-dental-hygienist-2026-v1", 8],
] as const;

export const DENTAL_PER_ACTIVITY_UNIT_LIMIT_BINDINGS = [
  ["ny-dentist-2026-cpr-course", 3],
  ["ny-dentist-2026-cpr-aed-bls-course", 4.5],
  ["ny-dentist-2026-initial-acls-pals-course", 12],
  ["ny-dentist-2026-acls-recertification-course", 6],
  ["ny-dental-hygienist-2026-cpr-course", 3],
  ["ny-dental-hygienist-2026-cpr-aed-bls-course", 4.5],
  ["ny-dental-hygienist-2026-initial-acls-pals-course", 12],
  ["ny-dental-hygienist-2026-acls-recertification-course", 6],
] as const;

export const DENTAL_REQUIRED_SUBTYPE_CATEGORY_GROUPS = [
  [
    "ny-dentist-2026-cardiopulmonary-credit",
    [
      "ny-dentist-2026-cpr-course",
      "ny-dentist-2026-cpr-aed-bls-course",
      "ny-dentist-2026-initial-acls-pals-course",
      "ny-dentist-2026-acls-recertification-course",
    ],
  ],
  [
    "ny-dental-hygienist-2026-cardiopulmonary-credit",
    [
      "ny-dental-hygienist-2026-cpr-course",
      "ny-dental-hygienist-2026-cpr-aed-bls-course",
      "ny-dental-hygienist-2026-initial-acls-pals-course",
      "ny-dental-hygienist-2026-acls-recertification-course",
    ],
  ],
] as const;

export const DENTAL_ANNUAL_REQUIREMENT_WINDOW_BINDINGS = [
  ["tx-dentist-2026-pain-management-year-1", 0, 12],
  ["tx-dentist-2026-pain-management-year-2", 12, 24],
] as const;

export const DENTAL_LINKED_APPLICABILITY_CATEGORY_GROUPS = [
  [
    "tx-dentist-2026-pain-management",
    "tx-dentist-2026-pain-management-year-1",
    "tx-dentist-2026-pain-management-year-2",
  ],
] as const;

export const DENTAL_AGGREGATE_PARENT_CATEGORY_IDS = [
  "tx-dentist-2026-pain-management",
] as const;

export const DENTAL_MAXIMUM_CLASSIFICATION_RULE_SET_IDS = [
  "ca-dentist-2026-v1",
  "ca-dental-hygienist-2026-v1",
  "fl-dentist-2026-v1",
  "fl-dental-hygienist-2026-v1",
  "nj-dentist-2026-v1",
  "nj-dental-hygienist-2026-v1",
  "ny-dentist-2026-v1",
  "ny-dental-hygienist-2026-v1",
  "pa-dentist-2026-v1",
  "pa-dental-hygienist-2026-v1",
  "tx-dentist-2026-v1",
  "tx-dental-hygienist-2026-v1",
] as const;

export const DENTAL_RENEWAL_TASK_COPY_BINDINGS = [
  [
    "ca-dentist-2026-v1",
    "Confirm BreEZe dates, full-cycle eligibility, active status, and any permit or reduced-fee pathway",
    "Complete and classify 50 approved units, mandatory courses, and current qualifying BLS; retain certificates for three renewal periods",
    "Renew through BreEZe and save the updated dentist license and renewal confirmation",
  ],
  [
    "ca-dental-hygienist-2026-v1",
    "Confirm Board dates, full-cycle eligibility, active status, and whether the credential is RDH/RDHEF rather than RDHAP",
    "Complete and classify 25 approved units, mandatory courses, and current qualifying BLS; retain certificates for three renewal periods",
    "Renew with the Dental Hygiene Board and save the updated license and confirmation",
  ],
  [
    "fl-dentist-2026-v1",
    "Confirm MQA and CE Broker dates, full-biennium eligibility, domestic-violence cadence, CPR, and any sedation permit",
    "Complete and verify the 30-hour Florida dentist plan and every applicable topic in CE Broker",
    "Renew through MQA and save the updated dentist license and CE Broker record",
  ],
  [
    "fl-dental-hygienist-2026-v1",
    "Confirm MQA and CE Broker dates, full-biennium eligibility, domestic-violence cadence, and current live CPR",
    "Complete and verify 24 hours—or 26 when domestic violence is due—in CE Broker",
    "Renew through MQA and save the updated dental-hygienist license and CE Broker record",
  ],
  [
    "nj-dentist-2026-v1",
    "Confirm Board biennium dates, active status, delivery limits, sedation permit, and any evidence-backed prior-biennium carryover",
    "Complete 40 credits and every current-cycle mandatory subject; retain proof for two full biennia",
    "Attest and renew with the Board, then save the updated New Jersey dentist license record",
  ],
  [
    "nj-dental-hygienist-2026-v1",
    "Confirm Board biennium dates, active status, delivery limit, and local-anesthesia or nitrous-monitoring cadence",
    "Complete 20 credits and mandatory subjects, plus three additional hours when nitrous monitoring is due",
    "Attest and renew with the Board, then save the updated New Jersey dental-hygienist license record",
  ],
  [
    "ny-dentist-2026-v1",
    "Confirm NYSED registration dates, full-period eligibility, live-hour plan, one-time duties, DEA status, and anesthesia certificate",
    "Complete 60 hours and every applicable New York training checkpoint; retain records for six years",
    "Re-register with NYSED and save the registration, prescriber attestation, and any certificate confirmations",
  ],
  [
    "ny-dental-hygienist-2026-v1",
    "Confirm NYSED registration dates, full-period eligibility, live-hour plan, and mandated-training cadence",
    "Complete 24 hours and every applicable New York training checkpoint; retain records for six years",
    "Re-register with NYSED and save the updated dental-hygiene registration confirmation",
  ],
  [
    "pa-dentist-2026-v1",
    "Confirm PALS biennium dates, full-cycle eligibility, DEA use, current CPR, and any anesthesia permit",
    "Complete and classify 30 hours and verify the Act 31 provider reported child-abuse training",
    "Renew through PALS and save the updated Pennsylvania dentist license record",
  ],
  [
    "pa-dental-hygienist-2026-v1",
    "Confirm PALS biennium dates, full-cycle eligibility, current CPR, and any local-anesthesia or PHDHP condition",
    "Complete and classify 20 hours and verify the Act 31 provider reported child-abuse training",
    "Renew through PALS and save the updated Pennsylvania dental-hygienist license record",
  ],
  [
    "tx-dentist-2026-v1",
    "Confirm TSBDE dates, full-cycle eligibility, no sedation-permit pathway, direct-care and DEA conditions, jurisprudence cadence, and any carryover",
    "Complete and classify 24 hours, human-trafficking training, current BLS, and every applicable dentist topic",
    "Attest and renew through the TSBDE licensing account, then save the updated license and proof",
  ],
  [
    "tx-dental-hygienist-2026-v1",
    "Confirm TSBDE dates, full-cycle eligibility, jurisprudence cadence, local-anesthesia and laser status, and any carryover",
    "Complete and classify 24 hours—or 26 with local-anesthesia approval—plus human-trafficking training and current BLS",
    "Attest and renew through the TSBDE licensing account, then save the updated license and proof",
  ],
] as const;
