type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

const LAST_VERIFIED_AT = "2026-07-26";

const CA_CHILD_DEVELOPMENT_URL =
  "https://www.ctc.ca.gov/credentials/leaflets/cl-797/";
const TX_CLASSROOM_TEACHER_URL =
  "https://tea.texas.gov/laws-and-rules/sbec-rules-tac/sbec-tac-currently-effect/ch232a-3.pdf";
const NY_CTLE_URL =
  "https://www.highered.nysed.gov/tcert/resteachers/ctle.html";
const NJ_TEACHER_PD_URL =
  "https://www.nj.gov/education/profdev/resources/faq/";
const PA_ACT_48_URL =
  "https://www.pa.gov/agencies/education/programs-and-services/educators/continuing-education-and-professional-development/act-48-and-perms/frequently-asked-questions/general-act-48-faq";

const NY_COMMON_NOTE =
  "Use only for a Professional classroom-teaching certificate holder who is subject to CTLE, practiced in an applicable New York school throughout a standard subsequent five-year registration period, and did not have an inactive year. NYSED defines practice as at least 90 employed days in one school year at one applicable school. An inactive or partial registration period instead requires 20 CTLE hours for each year of practice, without prorating a practiced partial year; use the TEACH-calculated requirement rather than this full-cycle template. The first registration period can be five years plus zero to eleven months, so use the exact TEACH dates. There is one 100-hour requirement per educator regardless of the number of Professional certificates. CTLE must come from a NYSED-approved sponsor; one semester credit equals 15 CTLE hours, one quarter credit equals 10, and other CTLE hours contain at least 60 minutes of instruction. No prior-period CTLE carries forward. At re-registration the educator attests in TEACH and does not routinely submit evidence. The educator must retain completion documentation for at least three years after the registration period; the separate eight-year duty applies to approved CTLE sponsors' awarded-credit records (https://www.highered.nysed.gov/tcert/resteachers/ctle-record-doc.html). NYSED allows a one-year, nonrenewable conditional registration and may adjust hours or time for documented good cause, but those special paths are outside this ordinary full-cycle template; use a custom plan with the exact TEACH dates and hours. Permanent-only certificate holders, Initial certificate holders, inactive registrants, and pupil-personnel-service certificate holders are outside this template. National Board certification can satisfy the cycle total only when the applicable language-acquisition requirement is also met.";

export const EDUCATION_RULE_SET_SEED_BINDINGS = [
  [
    "ca-child-development-permit-2026-v1",
    "ca-child-development-permit-professional-growth",
    1,
    "Education",
    "Child Development Permit — professional-growth renewal",
    "California",
    "California Commission on Teacher Credentialing",
    105,
    "professional-growth clock hours",
    60,
    CA_CHILD_DEVELOPMENT_URL,
    "California Commission on Teacher Credentialing Child Development Permit renewal guidance. Current permits are issued for five years and may be renewed for successive five-year periods after 105 hours of professional growth. This applies to the Assistant, Associate Teacher, Teacher, Master Teacher, Site Supervisor, and Program Director permit levels; regulations aligning Associate Teacher permits became effective April 9, 2025 (https://www.ctc.ca.gov/docs/default-source/commission/coded/2025/coded-25-04.pdf). Use the exact CTC Online validity dates. The permit holder and professional-growth advisor must determine and document activities that contribute to competence, performance, or effectiveness in early-childhood education, and the holder must complete the required self-verification/application process. CTC permits a one-time two-year reinstatement when the 105 hours were not finished, but this template models only an ordinary on-time five-year renewal. Use a custom plan with the exact CTC-approved dates for lapse or reinstatement activity rather than stretching this deadline. CTC publishes no general excess-hour carryover into a later five-year cycle, so iTrack does not copy surplus automatically. This template is not for a California Preliminary, Clear, or Life classroom-teaching credential.",
    "2025-04-09",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-standard-classroom-teacher-2026-v1",
    "tx-standard-classroom-teacher-full-cycle",
    1,
    "Education",
    "Standard Classroom Teacher Certificate — full five-year renewal cycle",
    "Texas",
    "Texas Education Agency",
    150,
    "TEA-recognized CPE hours",
    60,
    TX_CLASSROOM_TEACHER_URL,
    "Texas State Board for Educator Certification rules in 19 TAC Chapter 232 and the current Standard Certificate renewal page (https://tea.texas.gov/educators/certification/certification-renewals/standard-certificate-renewal-and-continuing-professional-education-cpe-information). Use only for a full five-year Standard classroom-teacher cycle when the educator does not also renew an administrator or student-services certificate; those combinations require 200 hours. Use the exact ECOS certificate dates and only CPE from an approved provider completed during the cycle. All educators need training on educating students with disabilities, including dyslexia; educators who teach students with dyslexia are expressly required by 19 TAC §232.11(k) to receive new-research-and-practices content. TEA states no numeric minimum, so that duty is a source-linked checklist condition rather than a fabricated one-hour category. Texas Education Code §21.054(d) and 19 TAC §232.11(d)(3) say TEA may not require more than 25% of classroom-teacher CPE in the listed topic areas; §21.054(d-2) and 19 TAC §232.11(d)(4) make excess topic hours creditable. Because TEA's August 2025 classroom-teacher handout describes 25% as required (https://tea.texas.gov/educators/certification/certification-renewals/classroom-teacher-certificate-cpe-requirements.pdf) while the controlling statute and rule use a ceiling, iTrack shows the topic pool as informational and does not enforce a 37.5-hour minimum; confirm the current ECOS/TEA instruction for the educator's cycle. One semester credit equals 15 CPE hours. Enter the TEA-creditable amount; qualifying in-person mental-health-first-aid or grief/trauma training can receive double credit, up to 16 credited hours. Educators apply and attest through TEAL/ECOS, retain evidence for five years, and submit it only if audited. CPE must be completed during each five-year period, so no carryover is applied. An expired certificate can have a separate late-reactivation pathway, but this template models only an ordinary on-time cycle; use a custom plan with the exact ECOS-approved dates for late CPE. A hardship exemption grants extra time, not a waiver of CPE, and likewise requires a custom date plan. Lifetime professional/provisional certificates issued before September 1, 1999 and educational-aide certificates are outside this template.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-professional-classroom-teacher-standard-ctle-2026-v1",
    "ny-professional-classroom-teacher-standard-ctle",
    1,
    "Education",
    "Professional Classroom Teacher Certificate — standard CTLE cycle, no language waiver",
    "New York",
    "New York State Education Department",
    100,
    "CTLE clock hours",
    60,
    NY_CTLE_URL,
    `New York State Education Department registration and CTLE guidance for a standard subsequent five-year period. This variant is for a Professional classroom teacher who does not hold a Professional ESOL certificate or Bilingual Education extension and whose applicable school did not have a language-acquisition exemption for any practiced year; at least 15% of the required CTLE must address language acquisition for English language learners (https://www.highered.nysed.gov/tcert/resteachers/ctle-language-acquisition.html). ${NY_COMMON_NOTE}`,
    "2016-07-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-professional-esol-bilingual-ctle-2026-v1",
    "ny-professional-esol-bilingual-ctle",
    1,
    "Education",
    "Professional ESOL Certificate or Bilingual Education Extension — CTLE cycle, no language waiver",
    "New York",
    "New York State Education Department",
    100,
    "CTLE clock hours",
    60,
    NY_CTLE_URL,
    `New York State Education Department registration and CTLE guidance for a standard subsequent five-year period. This variant is for an educator who holds a Professional English to Speakers of Other Languages certificate or Bilingual Education extension and whose applicable school did not have a language-acquisition exemption for any practiced year; at least 50% of the required CTLE must be language acquisition aligned with the core content area taught (https://www.highered.nysed.gov/tcert/resteachers/ctle-language-acquisition.html). ${NY_COMMON_NOTE}`,
    "2016-07-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-employed-teacher-annual-pd-2026-v1",
    "nj-employed-teacher-annual-pdp",
    1,
    "Education",
    "Employed Teacher — annual PDP professional learning (not certificate renewal)",
    "New Jersey",
    "New Jersey Department of Education",
    20,
    "supervisor-approved PD hours",
    12,
    NJ_TEACHER_PD_URL,
    "New Jersey Department of Education professional-development guidance and N.J.A.C. 6A:9C-4.4 (https://www.nj.gov/education/profdev/regs/docs/chap9c.pdf). This is an annual employment and individualized-PDP obligation for an active, full-time teacher employed for the full school year; it is not renewal of the New Jersey Standard certificate, which is permanent. A supervisor must prorate the 20 hours for part-time employment or leave, and may require more through the PDP or a corrective-action plan. Extra hours do not replace the next year's 20-hour minimum, so iTrack does not carry them forward. Activities, including online learning, require supervisor approval; the provider-registration system was eliminated, providers document completion, and the supervisor/district maintains the PDP and evidence. Separate state employment-training duties can apply and may fit within the annual total when approved: NJDOE currently lists certain K-3 general-education, special-education, basic-skills, ESL, reading-specialist, media-specialist, learning-disabilities-consultant, and speech-language roles for two hours of reading-disability/dyslexia training annually; because the agency table's media-specialist wording is broader than enacted N.J.S.A. 18A:6-131, confirm that role with the employer. Teaching staff need two hours of suicide-prevention training and public-school teachers need two hours of HIB-prevention training at least every five years. Beginning July 1, 2025, P.L. 2024, c. 52 also requires annual foundational-literacy professional development for covered prekindergarten-through-grade-six teachers and administrators, but NJDOE publishes no statewide numeric duration, so iTrack does not fabricate an hour minimum. Several other annual policy and safety trainings likewise have no statewide numeric duration (https://www.nj.gov/education/profdev/requirements/topics/prevention.shtml). The five-year duties require a separate rolling checklist because they cannot be safely inferred from one annual PDP graph. CE/CEAS credentials have lifetime eligibility, the Standard certificate is permanent, and a Provisional certificate is a time-limited induction credential, so none should be represented as a recurring 20-hour certificate renewal.",
    "2013-07-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "pa-professional-educator-act-48-2026-v1",
    "pa-professional-educator-act-48",
    1,
    "Education",
    "Professional Educator Certificate — Act 48 active-status cycle",
    "Pennsylvania",
    "Pennsylvania Department of Education",
    180,
    "Act 48 hours",
    60,
    PA_ACT_48_URL,
    "Pennsylvania Department of Education Act 48 guidance for a standard five-year active-status period. All Pennsylvania public-school professional certificates are subject to Act 48 whether employed or not, including Instructional I and II; Level II is permanent for validity purposes but does not eliminate Act 48. Complete six semester credits, six PDE-approved CPE credits, 180 approved hours, or a combination at 30 hours per credit. One requirement maintains all certificates held. The first period starts on the effective date of the initial certificate; use the exact PERMS period because extensions, delayed completion, or inactive status can change dates. Approved providers report to PERMS within 30 days and retain records for seven years; the educator must monitor PERMS and contact the provider about discrepancies. Up to 50 excess hours earned in the final two years may carry to a consecutive next period; record the actual prior-period date only in the PERMS-confirmed carryover category and only after PERMS posts the amount. Failure to finish leaves the certificate valid but inactive for most professional public-school employment, but this template models only an ordinary on-time period; use a custom plan with the exact PERMS dates for late completion or reactivation. A non-employed educator may request voluntary inactive status; removal requires a TIMS application plus 30 hours or one semester credit earned in the preceding 18 months, after which the prior remaining time is restored. That special pathway and PDE extensions require a custom date plan. An inactivation appeal is due within 30 days of notice. Act 126 separately requires three hours of child-abuse recognition and reporting every five years for employees or contractors with direct child contact; its employer-controlled five-year cycle is not the educator's individual Act 48 period, and it counts toward Act 48 only when the training is PDE-approved (https://www.pa.gov/agencies/education/programs-and-services/schools/school-climate-wellbeing/laws-and-regulations/act-126-child-abuse-reporting/faq). Act 55 separately requires three hours of school-safety training each year for covered school employees: two hours on the specified safety topics plus one hour on emergency drills or threat recognition (https://www.pa.gov/agencies/pccd/programs-and-services/training/school-safety-training/act-55). It is an employment duty rather than a universal Act 48 subcategory minimum and counts toward Act 48 only when the course is PDE-approved and reportable. Act 47 separately requires specified certificate holders who provide or supervise reading instruction to complete a PDE-approved structured-literacy program by the start of the 2028–29 school year; PDE does not publish one statewide hour minimum, so track it as a source-linked checklist rather than an Act 48 numeric subcategory (https://www.pa.gov/agencies/education/programs-and-services/schools/school-services/act-47-structured-literacy-faqs). Certified leaders serving in covered administrator roles require 180 Act 45/PIL hours rather than this classroom-educator variant.",
    "2000-07-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

const TX_ACTIVITY_GROUP = "Texas classroom-teacher CPE activity type";
const NY_ACTIVITY_GROUP = "New York classroom-teacher CTLE activity type";
const PA_ACTIVITY_GROUP = "Pennsylvania Act 48 activity type";

function nyCategoryBindings(
  ruleSetId:
    | "ny-professional-classroom-teacher-standard-ctle-2026-v1"
    | "ny-professional-esol-bilingual-ctle-2026-v1",
  languageHours: 15 | 50,
): readonly CategorySeedBinding[] {
  const prefix =
    ruleSetId === "ny-professional-esol-bilingual-ctle-2026-v1"
      ? "ny-professional-esol-bilingual-ctle-2026"
      : "ny-professional-classroom-standard-ctle-2026";

  return [
    [
      `${prefix}-other-approved-ctle`,
      ruleSetId,
      "Other Approved CTLE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Use this activity-type classifier for approved content, pedagogy, language-acquisition, or other acceptable CTLE that is not claimed as one of the capped mentoring activity types.",
      NY_ACTIVITY_GROUP,
      0,
    ],
    [
      `${prefix}-mentor-new-teacher`,
      ruleSetId,
      "Mentoring a New Classroom Teacher",
      30,
      "maximum",
      "independent",
      null,
      "optional",
      "At the district or BOCES sponsor's discretion, at most 30 CTLE hours may count in a five-year period for mentoring a new classroom teacher in its mentoring program. The sponsor must approve the activity and issue CTLE documentation.",
      NY_ACTIVITY_GROUP,
      1,
    ],
    [
      `${prefix}-mentor-teacher-candidate`,
      ruleSetId,
      "Mentoring a Teacher Candidate",
      25,
      "maximum",
      "independent",
      null,
      "optional",
      "At the district or BOCES sponsor's discretion, at most 25 CTLE hours may count in a five-year period for mentoring a teacher candidate. The sponsor must approve the activity and issue CTLE documentation.",
      NY_ACTIVITY_GROUP,
      2,
    ],
    [
      `${prefix}-language-acquisition`,
      ruleSetId,
      "Language Acquisition Addressing English Language Learners",
      languageHours,
      "minimum",
      "overlapping",
      null,
      "always",
      `Complete at least ${languageHours} of the 100 CTLE hours in the applicable NYSED language-acquisition content. This no-waiver full-cycle variant must not be used when TEACH calculates a reduced language requirement.`,
      null,
      3,
    ],
  ];
}

export const EDUCATION_CATEGORY_SEED_BINDINGS = [
  [
    "ca-child-development-permit-2026-professional-growth",
    "ca-child-development-permit-2026-v1",
    "Qualifying Professional Growth",
    105,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 105 clock hours selected with and accepted by the professional-growth advisor as contributing to competence, performance, or effectiveness in early-childhood education.",
    null,
    0,
  ],
  [
    "tx-standard-classroom-teacher-2026-other-cpe",
    "tx-standard-classroom-teacher-2026-v1",
    "Other Approved CPE Activity",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Use this activity-type classifier for approved workshops, conferences, in-service training, online learning, college coursework, and other TEA-eligible CPE not claimed under a capped activity type.",
    TX_ACTIVITY_GROUP,
    0,
  ],
  [
    "tx-standard-classroom-teacher-2026-independent-study",
    "tx-standard-classroom-teacher-2026-v1",
    "Independent Study",
    30,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 30 of the 150 CPE hours may count from independent study, including relevant self-study, curriculum development, or authoring a published work.",
    TX_ACTIVITY_GROUP,
    1,
  ],
  [
    "tx-standard-classroom-teacher-2026-presenting",
    "tx-standard-classroom-teacher-2026-v1",
    "Developing, Teaching, or Presenting CPE",
    15,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 15 of the 150 CPE hours may count from developing, teaching, or presenting a CPE activity to other educators.",
    TX_ACTIVITY_GROUP,
    2,
  ],
  [
    "tx-standard-classroom-teacher-2026-mentoring",
    "tx-standard-classroom-teacher-2026-v1",
    "Mentoring Another Educator",
    45,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 45 of the 150 CPE hours may count from providing professional guidance as a mentor to another educator.",
    TX_ACTIVITY_GROUP,
    3,
  ],
  [
    "tx-standard-classroom-teacher-2026-mandatory-topic-pool",
    "tx-standard-classroom-teacher-2026-v1",
    "Listed Classroom-Teacher Topic Pool — confirm current TEA instruction",
    0,
    "informational",
    "overlapping",
    null,
    "always",
    "Texas Education Code §21.054(d) and 19 TAC §232.11(d)(3) describe 25% as a ceiling, while an August 2025 TEA handout describes it as required. Track hours in the listed topics here if useful, but iTrack does not block readiness on 37.5 hours until TEA resolves or clarifies that conflict. The topics are classroom-effectiveness information; dropout early-warning indicators; digital learning and technology integration; educating diverse, disadvantaged, or dropout-risk populations; and appropriate educator-student relationships, boundaries, and communication.",
    null,
    4,
  ],
  ...nyCategoryBindings(
    "ny-professional-classroom-teacher-standard-ctle-2026-v1",
    15,
  ),
  ...nyCategoryBindings(
    "ny-professional-esol-bilingual-ctle-2026-v1",
    50,
  ),
  [
    "nj-employed-teacher-annual-pd-2026-qualifying-pdp",
    "nj-employed-teacher-annual-pd-2026-v1",
    "Qualifying Individual PDP Professional Learning",
    20,
    "minimum",
    "independent",
    null,
    "always",
    "Complete at least 20 supervisor-approved hours aligned with the individual PDP. This is the full-time, full-school-year amount; use a custom prorated total for part-time work or leave.",
    null,
    0,
  ],
  [
    "nj-employed-teacher-annual-pd-2026-dyslexia",
    "nj-employed-teacher-annual-pd-2026-v1",
    "Reading Disabilities, Including Dyslexia",
    2,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "NJDOE currently lists K-3 general-education teachers, special-education teachers, basic-skills teachers, ESL teachers, reading specialists, media specialists, learning-disabilities teacher consultants, and speech-language specialists. Its media-specialist wording is broader than enacted N.J.S.A. 18A:6-131, so confirm employer applicability. The two hours sit within the annual PDP total when approved.",
    null,
    1,
  ],
  [
    "pa-professional-educator-act-48-2026-other-approved",
    "pa-professional-educator-act-48-2026-v1",
    "Other PDE-Approved Act 48 Learning",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Use this activity-type classifier for PDE-approved Act 48 coursework, programs, activities, and learning experiences that are not claimed as capped mentoring/supervision or portal-confirmed carryover.",
    PA_ACTIVITY_GROUP,
    0,
  ],
  [
    "pa-professional-educator-act-48-2026-mentoring",
    "pa-professional-educator-act-48-2026-v1",
    "Mentoring Educators or Supervising Student Teachers",
    45,
    "maximum",
    "independent",
    null,
    "optional",
    "With LEA approval, mentoring an inductee or supervising a student teacher may earn up to 15 Act 48 hours per person and no more than 45 hours in the compliance period.",
    PA_ACTIVITY_GROUP,
    1,
  ],
  [
    "pa-professional-educator-act-48-2026-confirmed-carryover",
    "pa-professional-educator-act-48-2026-v1",
    "PERMS-Confirmed Carryover",
    50,
    "maximum",
    "independent",
    null,
    "conditional",
    "Record only carryover that PERMS posts for this period. Use the actual prior-period completion date and attach or reference the PERMS record. At most 50 excess hours earned in the final two years of the prior period may transfer to a consecutive new period; do not reconstruct or automatically copy prior activities.",
    PA_ACTIVITY_GROUP,
    2,
  ],
  [
    "pa-professional-educator-act-48-2026-act-126",
    "pa-professional-educator-act-48-2026-v1",
    "Act 126 Child-Abuse Recognition and Reporting",
    3,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Apply this category only when the employer-confirmed Act 126 deadline falls inside this Act 48 period for an employee or independent contractor with direct contact with children. The separate employer-controlled cycle requires at least three hours every five years. Count the same hours toward the Act 48 total only when the provider and course are approved for Act 48 credit and PERMS records them.",
    null,
    3,
  ],
] as const satisfies readonly CategorySeedBinding[];

export const EDUCATION_MAXIMUM_CLASSIFICATION_RULE_SET_IDS = [
  "tx-standard-classroom-teacher-2026-v1",
  "ny-professional-classroom-teacher-standard-ctle-2026-v1",
  "ny-professional-esol-bilingual-ctle-2026-v1",
  "pa-professional-educator-act-48-2026-v1",
] as const;
