type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

type RenewalTaskCopyBinding = readonly [
  ruleSetId: string,
  review: string,
  progress: string,
  submission: string,
];

const LAST_VERIFIED_AT = "2026-07-26";

const ANCC_HANDBOOK_URL =
  "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf";
const AACN_CCRN_URL =
  "https://www.aacn.org/certification/certification-renewal/ccrn-adult";
const NBCOT_RENEWAL_HANDBOOK_URL =
  "https://www.nbcot.org/-/media/PDFs/Renewal_Handbook.pdf";
const NBCOT_ACTIVITY_CHART_URL =
  "https://www.nbcot.org/-/media/PDFs/Renewal_Activities_Chart.pdf";
const BACB_HANDBOOK_URL = "https://www.bacb.com/bcba-handbook";
const NBCC_MANAGE_URL =
  "https://community.nbcc.org/resources/nccs/manage";
const NBCC_CE_URL =
  "https://community.nbcc.org/resources/nccs/earnce";
const CCMC_RENEWAL_GUIDE_URL =
  "https://yourcommission.org/certification/board-certified-case-manager/stay-certified";
const AAPC_CE_POLICY_URL =
  "https://www.aapc.com/medical-coding-education/help/";
const AHIMA_RECERTIFICATION_GUIDE_URL =
  "https://www.ahima.org/media/abhjxi3w/recertification-guide_updated_03-2026_final.pdf";
const ASCP_MLS_URL =
  "https://www.ascp.org/boc/maintain-your-credentials/view-credentials-to-maintain/MLS";
const NBRC_CMP_RESOURCES_URL = "https://www.nbrc.org/resources/";
const NBRC_CMP_BROCHURE_URL =
  "https://www.nbrc.org/wp-content/uploads/2026/01/NBRC-CMP-Brochure-01.26.26.pdf";
const INTELEOS_MOC_FAQ_URL = "https://www.inteleos.org/moc-faq/";
const AAMA_RECERTIFICATION_URL =
  "https://www.aama-ntl.org/certification/recertification";
const NAHQ_RECERTIFICATION_URL =
  "https://nahq.org/credentials/cphq-certified-professional-in-healthcare-quality/cphq-recertification/";

const ANCC_FNP_SOURCE_NOTE =
  `ANCC Certification Renewal Handbook effective September 10, 2025, Version 2 dated February 10, 2026, scoped to the fully continuing-education-based renewal path for an active Family Nurse Practitioner (FNP-BC): complete the mandatory 75 contact hours related to the FNP role and population plus Category 1 Continuing Education in its entirety as the separate professional-development category, for 150 contact hours during the assigned five-year certification period. Each 75-hour block requires at least 60 formally approved continuing-education hours, so at least 120 of the 150 hours must meet ANCC's formally approved criteria. At least 25 pharmacology contact hours must be part of the mandatory 75. Maintain a current active RN license or legally recognized equivalent. Effective January 14, 2026, renewal activities must be completed inside the designated certification cycle and before application submission. ANCC accepts a repeated course only once in a cycle and may audit supporting records. Official handbook: ${ANCC_HANDBOOK_URL}. This template must not be used when the certificant selects practice hours, preceptorship, academic credits, presentations, professional service, EBP/QI/publication/research, or the assessment option as the required additional professional-development category; those paths need a custom checklist. Use the exact ANCC account dates, and do not treat a hardship extension or lapsed-certification reactivation as automatic.`;

const AACN_CCRN_SOURCE_NOTE =
  "AACN Certification Corporation CCRN Adult renewal guidance, scoped to an active adult direct-care CCRN using the Renewal by Synergy CERPs pathway. During the assigned three-year certification period, earn 100 Synergy CERPs: at least 60 Category A, 10 Category B, and 10 Category C, with the remaining 20 in any category. Also maintain a current unencumbered RN or APRN license and complete 432 direct-care hours with acutely or critically ill adult patients during the cycle, including 144 hours in the 12 months before renewal; the majority of eligible hours must focus on critically ill patients and must meet AACN's setting and role rules. Renewal by examination is a separate alternative and is not represented by this template. This is not the CCRN Adult knowledge-professional pathway, nor a pediatric or neonatal CCRN. Use the exact AACN account dates and retain supporting CERP and practice-hour records.";

function nbcotSourceNote(credential: "OTR" | "COTA") {
  return `NBCOT 2026 certification-renewal guidance for one active ${credential} credential in good standing: accrue at least 36 renewal units during the assigned three-year renewal cycle through any accepted combination of competency assessment units (CAUs) and professional development units (PDUs), complete the renewal application and attestations, and pay the fee. Use the units that NBCOT awards under its current activity chart; activity types have different conversion formulas, documentation rules, and limits, so do not automatically equate one attendance hour with one unit. A narrow cohort exception permits certificants who renewed in 2023 to carry into the 2023–2026 cycle up to 10 documented units earned in excess of the 36 required during 2020–2023; iTrack never creates that carryover automatically, and the exception must not be applied to another cohort. The standard renewal season runs January through March of the certificant's scheduled renewal year, but the exact deadline and status shown in MyNBCOT control. Retain all renewal documentation for one full year after renewal for possible random audit. A dual OTR/COTA holder follows NBCOT's separate dual-credential policy and should not duplicate this single-credential template. The Navigator Physical Agent Modalities activity is OTR-only${credential === "COTA" ? " and cannot be counted for this COTA credential" : ""}. Official 2026 renewal handbook: ${NBCOT_RENEWAL_HANDBOOK_URL}. Official activity values, evidence rules, and caps: ${NBCOT_ACTIVITY_CHART_URL}.`;
}

const BACB_BCBA_SOURCE_NOTE =
  `BACB BCBA Handbook current June 2026: complete 32 continuing-education units during the assigned two-year recertification cycle, including four ethics CEUs. A BCBA who at any point in the cycle supervised the ongoing practice of RBTs or BCaBAs on record, or trainees pursuing BCBA or BCaBA certification, must also complete three behavior-analytic supervision CEUs covering the effective supervision practices BACB describes; those CEUs remain part of the 32. Complete ethics and self-reporting attestations, keep the credential in good standing, enter every CEU in the BACB portal with its supporting documentation uploaded before the recertification date, and apply no earlier than 45 days before expiration. CEUs must be earned within the current cycle; excess CEUs do not carry forward and missing CEUs cannot be made up during reinstatement. Official handbook: ${BACB_HANDBOOK_URL}. This plain BCBA template excludes BCBA-D designation administration and any separate state behavior-analyst license.`;

const NBCC_NCC_SOURCE_NOTE =
  `NBCC maintenance guidance for an active, standard-practice National Certified Counselor: complete 100 qualifying continuing-education clock hours during the assigned five-year certification period, keep annual certification fees current, adhere to the NBCC Code of Ethics, and make required ethics or disciplinary disclosures. Activities must fit an NBCC-approved content area or another specifically accepted activity type and must have the documentation NBCC describes. During one cycle, no more than 20 hours may count from publications, presentations, and new-program development combined; 45 from a dissertation; 25 from supervision or consultation received; 20 from qualifying leadership; 10 from volunteer activity; and 20 from otherwise unrelated programs accepted case by case. Graduate courses, seminars or workshops, and qualifying home study have no published clock-hour cap. Official maintenance guidance: ${NBCC_MANAGE_URL}. Official activity, conversion, documentation, and activity-limit guidance: ${NBCC_CE_URL}. Passing the NCE or NCMHCE is a separate recertification alternative and is not modeled here. Reduced-practice status can reduce the total to 10 hours, and retired status and specialty credentials such as CCMHC, NCSC, or MAC have different conditions; none is covered by this standard NCC template. Use the exact NBCC account cycle and do not assume that an extension has been granted.`;

const CCMC_CCM_SOURCE_NOTE =
  `Commission for Case Manager Certification renewal guide for a standard active CCM renewing by continuing education: earn 80 continuing-education credits during the assigned five-year certification period, including at least eight ethics credits, with content in the CCM exam knowledge domains and focus areas. The online renewal window generally opens about three months before the account's May 31 or November 30 renewal date. Pre-approved education is reported with its approval information; post-approved education and university coursework require the documentation, review, and any fee described by CCMC. Renewal by examination is a separate alternative and is not represented here. Official guide: ${CCMC_RENEWAL_GUIDE_URL}. Use the exact certification dashboard dates and accepted-credit values, complete the ethics and professional-conduct attestations, and retain evidence for audit.`;

const AAPC_CPC_SOURCE_NOTE =
  `AAPC continuing-education policy for a holder maintaining exactly one CPC credential: report 36 approved CEUs every two years while keeping AAPC membership current. At least two-thirds of the CEUs must be Curriculum A; no more than one-third, or 12 of 36, may be Curriculum B. Activities must appear on AAPC's approved list or otherwise satisfy the current policy, may be reported only once, must be earned in the applicable reporting period, and do not carry forward. Official policy: ${AAPC_CE_POLICY_URL}. AAPC assigns larger totals to holders of two or more credentials (40, 44, 48, or 52 CEUs depending on credential count), and an initial period may be prorated, so this template is only for one CPC in a normal full cycle. The reporting deadline is tied to the individual membership renewal month; use the exact AAPC account date and retain index numbers and certificates for possible audit.`;

function ahimaSourceNote(
  credential: "RHIA" | "CCS",
  total: 30 | 20,
  hiimMinimum: 24 | 16,
) {
  return `AHIMA Recertification Guide updated March 2026, scoped to a holder maintaining only the ${credential} credential in a standard full two-year cycle: earn ${total} CEUs, with at least 80%, or ${hiimMinimum} CEUs, in current health information and informatics (HIIM) domains; at most 20% may be other job-relevant education. Complete the recertification reporting and fee by the exact date shown in the AHIMA account, upload or retain supporting documentation as directed, and keep records for two years after the cycle closes. Official guide: ${AHIMA_RECERTIFICATION_GUIDE_URL}. A holder with multiple AHIMA credentials uses the highest single-credential total plus 10 CEUs for each additional credential, capped at 50, with additional credential-specific rules; early-test and synchronized cycles can also differ. The announced 40% AHIMA-source requirement and rollover program are on hold until further notice in the March 2026 guide and are deliberately not enforced here.`;
}

const ASCP_MLS_SOURCE_NOTE =
  `ASCP Board of Certification Credential Maintenance Program requirements for a time-limited MLS credential: complete 36 CMP points during the assigned three-year cycle, including two points each in blood banking, chemistry, hematology, and microbiology; one point in laboratory or patient safety; one point in medical ethics; and the remaining 26 points in laboratory specialty, immunology, molecular biology, management, education, or other accepted related content. Activities must be completed inside the current cycle and entered on the CMP declaration using ASCP's activity values and documentation rules. Official MLS requirements: ${ASCP_MLS_URL}. This template is for one time-limited MLS credential. A pre-2004 legacy credential may participate voluntarily, and a holder maintaining multiple ASCP credentials must follow the separate declaration and eligibility rules for each credential rather than assuming every activity applies to all of them.`;

const NBRC_RRT_SOURCE_NOTE =
  `NBRC Credential Maintenance Program guidance current January 2026, scoped only to an RRT whose dashboard requires or whose holder selects the full 30-CE route: complete 30 Category I continuing-education credits directly related to respiratory care during the assigned five-year credential term. When a state does not award credit, NBRC accepts six CEU hours for successful completion of each BLS, ACLS, NRP, or PALS course, subject to a 12-credit combined cap for those programs during the five-year term. Official current CMP FAQ and resources: ${NBRC_CMP_RESOURCES_URL}. Official January 26, 2026 brochure: ${NBRC_CMP_BROCHURE_URL}. NBRC's assessment pathway can reduce an individual's CE requirement to 15 or zero, and earning a new credential or retaking the examination may provide other maintenance paths; use this template only when the NBRC dashboard confirms 30 credits. Keep annual CMP fee installments current, use the exact credential expiration at the end of the examination-anniversary month, and retain acceptable Category I documentation. Credentials issued before July 1, 2002, and holders using another CMP path are outside scope.`;

const ARDMS_RDMS_SOURCE_NOTE =
  `Inteleos/ARDMS Maintenance of Certification rules effective January 1, 2026, scoped to an RDMS holder whose current three-year CME period ends on or after December 31, 2026 and whose dashboard requires the standard 25 CME credits. Complete 25 accepted CME credits during the assigned period; the credits no longer need to be specialty-specific. In addition, for each RDMS specialty held, complete four quarterly SKILLS quizzes (40 questions total) each calendar year and achieve at least 80% cumulatively by December 31. Complete the annual renewal payment, attestation, disclosure, and contact-information review by December 31. Official MOC FAQ: ${INTELEOS_MOC_FAQ_URL}. New credentials and specialties, volunteer service, multiple credentials, or other waivers can change the displayed CME obligation, so use the exact Inteleos dashboard total instead of this template when it is not 25. The annual knowledge-confirmation requirement is a separate checklist obligation and does not add CME units. Retain CME evidence for four years.`;

const AAMA_CMA_SOURCE_NOTE =
  `AAMA CMA (AAMA) recertification guidance for the continuing-education pathway in a standard five-year cycle: earn 60 recertification points, including at least 10 General, 10 Administrative, and 10 Clinical points; the remaining 30 may be in any of those content areas. At least 30 of the 60 points must be AAMA-approved continuing education. Points do not carry forward to a later cycle. Official guidance: ${AAMA_RECERTIFICATION_URL}. Recertification by examination is a separate alternative and is not represented here. A first recertification may use no more than 20 eligible points earned in the three months before initial certification, and a credential expired more than three months generally requires examination; those special paths are outside this normal-cycle template. Use the exact AAMA account deadline and retain certificates and approval information.`;

const NAHQ_CPHQ_SOURCE_NOTE =
  `NAHQ/Healthcare Quality Certification Commission CPHQ recertification guidance: complete 30 eligible continuing-education credits during the assigned two-year cycle. A normal cycle begins January 1 after the initial examination year and ends December 31 of the second year. The recertification application is normally available July 1 through December 31; the January 1-31 late-fee period does not extend the time to earn CE. Activities must relate to the CPHQ content outline or otherwise meet NAHQ's current eligibility and documentation rules, and ordinary job duties do not count merely because they involve healthcare quality. Official guidance: ${NAHQ_RECERTIFICATION_URL}. Use the exact NAHQ account cycle, retain evidence for audit, submit the application and fee on time, and do not assume an extension or an examination-in-lieu option.`;

export const HEALTHCARE_CERTIFICATION_RULE_SET_SEED_BINDINGS = [
  [
    "ancc-fnp-150-ce-2026-v1",
    "ancc-fnp-150-ce",
    1,
    "Nursing",
    "Family Nurse Practitioner (FNP-BC) — ANCC 150-contact-hour renewal path",
    "United States",
    "American Nurses Credentialing Center",
    150,
    "ANCC-accepted contact hours",
    60,
    ANCC_HANDBOOK_URL,
    ANCC_FNP_SOURCE_NOTE,
    "2025-09-10",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "aacn-ccrn-adult-direct-care-cerp-2026-v1",
    "aacn-ccrn-adult-direct-care-cerp",
    1,
    "Nursing",
    "CCRN Adult — direct-care Synergy CERP renewal path",
    "United States",
    "AACN Certification Corporation",
    100,
    "Synergy CERPs",
    36,
    AACN_CCRN_URL,
    AACN_CCRN_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nbcot-otr-2026-v1",
    "nbcot-otr",
    1,
    "Occupational Therapy",
    "Occupational Therapist, Registered (OTR) — standard renewal",
    "United States",
    "National Board for Certification in Occupational Therapy",
    36,
    "NBCOT renewal units",
    36,
    NBCOT_RENEWAL_HANDBOOK_URL,
    nbcotSourceNote("OTR"),
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nbcot-cota-2026-v1",
    "nbcot-cota",
    1,
    "Occupational Therapy",
    "Certified Occupational Therapy Assistant (COTA) — standard renewal",
    "United States",
    "National Board for Certification in Occupational Therapy",
    36,
    "NBCOT renewal units",
    36,
    NBCOT_RENEWAL_HANDBOOK_URL,
    nbcotSourceNote("COTA"),
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "bacb-bcba-2026-v1",
    "bacb-bcba",
    1,
    "Behavior Analysis",
    "Board Certified Behavior Analyst (BCBA) — standard recertification",
    "United States",
    "Behavior Analyst Certification Board",
    32,
    "BACB CEUs",
    24,
    BACB_HANDBOOK_URL,
    BACB_BCBA_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nbcc-ncc-2026-v1",
    "nbcc-ncc",
    1,
    "Professional Counseling",
    "National Certified Counselor (NCC) — standard-practice recertification",
    "United States",
    "National Board for Certified Counselors",
    100,
    "NBCC qualifying clock hours",
    60,
    NBCC_MANAGE_URL,
    NBCC_NCC_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ccmc-ccm-2026-v1",
    "ccmc-ccm",
    1,
    "Case Management",
    "Certified Case Manager (CCM) — continuing-education renewal path",
    "United States",
    "Commission for Case Manager Certification",
    80,
    "CCMC continuing-education credits",
    60,
    CCMC_RENEWAL_GUIDE_URL,
    CCMC_CCM_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "aapc-cpc-single-2026-v1",
    "aapc-cpc-single",
    1,
    "Medical Coding",
    "Certified Professional Coder (CPC) — one-credential full cycle",
    "United States",
    "AAPC",
    36,
    "AAPC-approved CEUs",
    24,
    AAPC_CE_POLICY_URL,
    AAPC_CPC_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ahima-rhia-single-2026-v1",
    "ahima-rhia-single",
    1,
    "Health Information Management",
    "Registered Health Information Administrator (RHIA) — one-credential full cycle",
    "United States",
    "AHIMA Commission on Certification for Health Informatics and Information Management",
    30,
    "AHIMA CEUs",
    24,
    AHIMA_RECERTIFICATION_GUIDE_URL,
    ahimaSourceNote("RHIA", 30, 24),
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ahima-ccs-single-2026-v1",
    "ahima-ccs-single",
    1,
    "Health Information Management",
    "Certified Coding Specialist (CCS) — one-credential full cycle",
    "United States",
    "AHIMA Commission on Certification for Health Informatics and Information Management",
    20,
    "AHIMA CEUs",
    24,
    AHIMA_RECERTIFICATION_GUIDE_URL,
    ahimaSourceNote("CCS", 20, 16),
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ascp-mls-cmp-2026-v1",
    "ascp-mls-cmp",
    1,
    "Medical Laboratory Science",
    "Medical Laboratory Scientist (MLS) — ASCP CMP",
    "United States",
    "ASCP Board of Certification",
    36,
    "ASCP CMP points",
    36,
    ASCP_MLS_URL,
    ASCP_MLS_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nbrc-rrt-full-ce-2026-v1",
    "nbrc-rrt-full-ce",
    1,
    "Respiratory Care",
    "Registered Respiratory Therapist (RRT) — full 30-CE CMP path",
    "United States",
    "National Board for Respiratory Care",
    30,
    "NBRC Category I CE credits",
    60,
    NBRC_CMP_RESOURCES_URL,
    NBRC_RRT_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ardms-rdms-standard-moc-2026-v1",
    "ardms-rdms-standard-moc",
    1,
    "Diagnostic Medical Sonography",
    "Registered Diagnostic Medical Sonographer (RDMS) — standard 25-CME MOC period",
    "United States",
    "American Registry for Diagnostic Medical Sonography (Inteleos)",
    25,
    "Inteleos-accepted CME credits",
    36,
    INTELEOS_MOC_FAQ_URL,
    ARDMS_RDMS_SOURCE_NOTE,
    "2026-01-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "aama-cma-ce-2026-v1",
    "aama-cma-ce",
    1,
    "Medical Assisting",
    "Certified Medical Assistant, AAMA (CMA) — continuing-education path",
    "United States",
    "Certifying Board of the American Association of Medical Assistants",
    60,
    "AAMA recertification points",
    60,
    AAMA_RECERTIFICATION_URL,
    AAMA_CMA_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nahq-cphq-2026-v1",
    "nahq-cphq",
    1,
    "Healthcare Quality",
    "Certified Professional in Healthcare Quality (CPHQ) — standard recertification",
    "United States",
    "Healthcare Quality Certification Commission",
    30,
    "CPHQ continuing-education credits",
    24,
    NAHQ_RECERTIFICATION_URL,
    NAHQ_CPHQ_SOURCE_NOTE,
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

function nbcotCategoryBindings(credential: "otr" | "cota") {
  const ruleSetId = `nbcot-${credential}-2026-v1`;
  const prefix = `nbcot-${credential}-2026`;
  const rootId = `${prefix}-eligible-units`;
  const fieldworkId = `${prefix}-fieldwork-supervision`;
  const activityGroup = `NBCOT ${credential.toUpperCase()} renewal activity type`;
  const credentialLabel = credential.toUpperCase();

  return [
    [
      rootId,
      ruleSetId,
      "NBCOT-Eligible Renewal Units",
      36,
      "minimum",
      "independent",
      null,
      "always",
      "Record only CAUs or PDUs calculated under NBCOT's current activity chart after applying the activity-specific conversion, evidence rule, and limit. The 2023-renewed cohort may include no more than 10 documented excess units from 2020–2023; do not infer or copy carryover for any other cohort.",
      null,
      0,
    ],
    [
      `${prefix}-other-eligible-activity`,
      ruleSetId,
      "Other Eligible NBCOT Activity Without a Published Cycle Cap",
      0,
      "informational",
      "nested",
      rootId,
      "optional",
      `Use this catch-all only for an accepted activity-chart type without a published cycle cap. Do not use it for a separately listed capped activity.${credential === "otr" ? " The OTR-only PAM Navigator activity may be classified here when NBCOT awards it." : " The PAM Navigator activity is OTR-only and cannot be counted for this COTA credential."}`,
      activityGroup,
      1,
    ],
    [
      `${prefix}-self-assessment`,
      ruleSetId,
      "Professional Skills Self-Assessments",
      7,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than seven units may count from accepted professional skills self-assessments; the same assessment may be claimed only once per renewal cycle.",
      activityGroup,
      2,
    ],
    [
      `${prefix}-competency-plan`,
      ruleSetId,
      "Professional Development Continuing-Competency Plan",
      1,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than one unit may count for developing a continuing-competency plan from professional skills assessment results.",
      activityGroup,
      3,
    ],
    [
      fieldworkId,
      ruleSetId,
      "Fieldwork Supervision — All Levels Combined",
      12,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 12 units combined may count from Level I, Level II, entry-level, and post-doctoral advanced fieldwork supervision. Classify the activity with one fieldwork subtype below; do not select this rollup by itself.",
      null,
      4,
    ],
    [
      `${prefix}-fieldwork-level-i`,
      ruleSetId,
      "Level I Fieldwork Direct Supervision",
      6,
      "maximum",
      "nested",
      fieldworkId,
      "optional",
      "Level I fieldwork direct supervision is capped at six units and remains inside the 12-unit combined fieldwork-supervision cap. It must not be the certificant's primary role.",
      activityGroup,
      5,
    ],
    [
      `${prefix}-fieldwork-level-ii-advanced`,
      ruleSetId,
      "Level II, Entry-Level, or Post-Doctoral Advanced Fieldwork Supervision",
      0,
      "informational",
      "nested",
      fieldworkId,
      "optional",
      "Use for accepted Level II, entry-level, or post-doctoral advanced direct supervision. These units remain inside the 12-unit combined fieldwork-supervision cap, and supervision must not be the certificant's primary role.",
      activityGroup,
      6,
    ],
    [
      `${prefix}-otd-capstone-mentorship`,
      ruleSetId,
      "Entry-Level OTD Capstone Mentorship",
      14,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 14 units may count from accepted entry-level OTD capstone mentorship.",
      activityGroup,
      7,
    ],
    [
      `${prefix}-volunteer-service`,
      ruleSetId,
      "Professional Volunteer Service",
      6,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than six units may count from accepted volunteer service that develops the certificant's professional practice or leadership role.",
      activityGroup,
      8,
    ],
    [
      `${prefix}-peer-review`,
      ruleSetId,
      "Peer Review of Research Article or Textbook",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted peer review of practice-related research articles or textbooks.",
      activityGroup,
      9,
    ],
    [
      `${prefix}-mentoring-provided`,
      ruleSetId,
      "Professional Mentoring Provided",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      `No more than 18 units may count from accepted mentoring provided by the currently NBCOT-certified ${credentialLabel} to an OT colleague or other professional.`,
      activityGroup,
      10,
    ],
    [
      `${prefix}-mentoring-received`,
      ruleSetId,
      "Professional Mentoring Received",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted mentoring received from a currently certified occupational therapy practitioner or another professional in good standing.",
      activityGroup,
      11,
    ],
    [
      `${prefix}-study-group`,
      ruleSetId,
      "Professional Study Group",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted active participation in a professional or online study group.",
      activityGroup,
      12,
    ],
    [
      `${prefix}-poster-presentation`,
      ruleSetId,
      "State, National, or International Poster Presentation",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted poster presentations; each topic may be claimed only once per renewal cycle and preparation time does not count.",
      activityGroup,
      13,
    ],
    [
      `${prefix}-adjunct-faculty`,
      ruleSetId,
      "Adjunct Faculty",
      6,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than six units may count from accepted adjunct-faculty teaching that is not the certificant's primary role.",
      activityGroup,
      14,
    ],
    [
      `${prefix}-in-service-or-guest-lecture`,
      ruleSetId,
      "Professional In-Service, Instruction, or Guest Lecture",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted professional in-service training, instruction, or guest lectures; each topic may be claimed only once and preparation time does not count.",
      activityGroup,
      15,
    ],
    [
      `${prefix}-local-presentation`,
      ruleSetId,
      "Local Organization or Association Presentation",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted local presentations on a practice-related topic; each topic may be claimed only once and preparation time does not count.",
      activityGroup,
      16,
    ],
    [
      `${prefix}-research-or-outcome-study`,
      ruleSetId,
      "Research, Outcome Study, or Funded Service/Training Project",
      18,
      "maximum",
      "nested",
      rootId,
      "optional",
      "No more than 18 units may count from accepted work as primary or co-primary investigator on scholarly research, outcome studies, or qualifying externally funded projects.",
      activityGroup,
      17,
    ],
    [
      `${prefix}-confirmed-2023-cohort-carryover`,
      ruleSetId,
      "Confirmed 2023-Cohort Carryover",
      10,
      "maximum",
      "nested",
      rootId,
      "optional",
      "Use only for a certificant who renewed in 2023 and has evidence of units earned during 2020–2023 in excess of the 36 required for that renewal. Record the actual prior-cycle date and no more than 10 units; this one-time cohort exception does not apply to another renewal cohort.",
      activityGroup,
      18,
    ],
  ] as const satisfies readonly CategorySeedBinding[];
}

export const HEALTHCARE_CERTIFICATION_CATEGORY_SEED_BINDINGS = [
  [
    "ancc-fnp-150-ce-2026-specialty",
    "ancc-fnp-150-ce-2026-v1",
    "FNP Role and Population Continuing Education",
    150,
    "minimum",
    "independent",
    null,
    "always",
    "All 150 contact hours in this specifically scoped pathway must satisfy ANCC's FNP specialty-content rules: 75 mandatory hours plus 75 hours used as the selected continuing-education professional-development category.",
    null,
    0,
  ],
  [
    "ancc-fnp-150-ce-2026-formally-approved",
    "ancc-fnp-150-ce-2026-v1",
    "Formally Approved Continuing Education",
    120,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least 60 hours in each 75-hour continuing-education block must meet ANCC's formally approved provider or sponsor criteria, for at least 120 formally approved hours across this 150-hour path. These hours remain part of the 150-hour total.",
    null,
    1,
  ],
  [
    "ancc-fnp-150-ce-2026-pharmacology",
    "ancc-fnp-150-ce-2026-v1",
    "Advanced Pharmacology",
    25,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least 25 contact hours must address pharmacotherapeutics appropriate to the FNP role and population. Pharmacology is part of the mandatory 75 and the 150-hour total; enter only the supported pharmacology portion.",
    null,
    2,
  ],
  [
    "aacn-ccrn-adult-2026-category-a",
    "aacn-ccrn-adult-direct-care-cerp-2026-v1",
    "Synergy CERP Category A",
    60,
    "minimum",
    "independent",
    null,
    "always",
    "At least 60 CERPs must be awarded in Category A. Classify each CERP once using the category on AACN's accepted record.",
    "AACN Synergy CERP category",
    0,
  ],
  [
    "aacn-ccrn-adult-2026-category-b",
    "aacn-ccrn-adult-direct-care-cerp-2026-v1",
    "Synergy CERP Category B",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "At least 10 CERPs must be awarded in Category B. Classify each CERP once using the category on AACN's accepted record.",
    "AACN Synergy CERP category",
    1,
  ],
  [
    "aacn-ccrn-adult-2026-category-c",
    "aacn-ccrn-adult-direct-care-cerp-2026-v1",
    "Synergy CERP Category C",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "At least 10 CERPs must be awarded in Category C. The remaining 20 of the required 100 may be in A, B, or C.",
    "AACN Synergy CERP category",
    2,
  ],
  ...nbcotCategoryBindings("otr"),
  ...nbcotCategoryBindings("cota"),
  [
    "bacb-bcba-2026-eligible-ce",
    "bacb-bcba-2026-v1",
    "BACB-Eligible Continuing Education",
    32,
    "minimum",
    "independent",
    null,
    "always",
    "All 32 CEUs must satisfy a current BACB CE activity type and documentation rule and must be earned inside the assigned recertification cycle.",
    null,
    0,
  ],
  [
    "bacb-bcba-2026-ethics",
    "bacb-bcba-2026-v1",
    "Ethics",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least four of the 32 CEUs must cover ethics. Enter only the ethics portion supported by the BACB-eligible activity record.",
    null,
    1,
  ],
  [
    "bacb-bcba-2026-supervision",
    "bacb-bcba-2026-v1",
    "Supervision",
    3,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Required only when the BCBA supervised the ongoing practice of RBTs or BCaBAs on record, or trainees pursuing BCBA or BCaBA certification, at any point during the cycle. The three CEUs must be behavior-analytic and cover BACB-described effective supervision practices; they remain part of the 32.",
    null,
    2,
  ],
  [
    "nbcc-ncc-2026-qualifying-ce",
    "nbcc-ncc-2026-v1",
    "NBCC-Qualifying Continuing Education",
    100,
    "minimum",
    "independent",
    null,
    "always",
    "Record clock hours only after applying NBCC's accepted-content, conversion, documentation, and activity-limit rules. This category is for standard-practice NCC status, not the reduced 10-hour status.",
    null,
    0,
  ],
  [
    "nbcc-ncc-2026-uncapped-program",
    "nbcc-ncc-2026-v1",
    "Graduate Course, Seminar, Workshop, or Home Study",
    0,
    "informational",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "Use for qualifying graduate courses, seminars, workshops, conferences, and home-study programs, for which NBCC publishes no clock-hour cap. Do not use this category to bypass a cap assigned to another activity type.",
    "NBCC NCC activity type",
    1,
  ],
  [
    "nbcc-ncc-2026-publication-presentation-program",
    "nbcc-ncc-2026-v1",
    "Publication, Presentation, or New-Program Development",
    20,
    "maximum",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "No more than 20 clock hours combined may count from qualifying publications, presentations, and new-program development during one certification cycle.",
    "NBCC NCC activity type",
    2,
  ],
  [
    "nbcc-ncc-2026-dissertation",
    "nbcc-ncc-2026-v1",
    "Dissertation",
    45,
    "maximum",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "No more than 45 clock hours may count from qualifying dissertation work during one certification cycle.",
    "NBCC NCC activity type",
    3,
  ],
  [
    "nbcc-ncc-2026-supervision-consultation",
    "nbcc-ncc-2026-v1",
    "Supervision or Consultation Received",
    25,
    "maximum",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "No more than 25 clock hours may count from formal, clinically focused supervision or consultation received. Supervision provided to others does not qualify under this activity type.",
    "NBCC NCC activity type",
    4,
  ],
  [
    "nbcc-ncc-2026-leadership",
    "nbcc-ncc-2026-v1",
    "Qualifying Leadership",
    20,
    "maximum",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "No more than 20 clock hours may count from a qualifying unpaid leadership position meeting NBCC's duration and organization rules.",
    "NBCC NCC activity type",
    5,
  ],
  [
    "nbcc-ncc-2026-volunteer",
    "nbcc-ncc-2026-v1",
    "Qualifying Volunteer Activity",
    10,
    "maximum",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "No more than 10 clock hours may count from volunteer activity accepted under NBCC's mission, documentation, and direct-client-service rules.",
    "NBCC NCC activity type",
    6,
  ],
  [
    "nbcc-ncc-2026-unrelated-program",
    "nbcc-ncc-2026-v1",
    "Case-by-Case Unrelated Program",
    20,
    "maximum",
    "nested",
    "nbcc-ncc-2026-qualifying-ce",
    "optional",
    "No more than 20 clock hours may count from programs outside NBCC's nine counseling content areas, and only when NBCC accepts their direct-service relevance and supporting documentation.",
    "NBCC NCC activity type",
    7,
  ],
  [
    "ccmc-ccm-2026-eligible-ce",
    "ccmc-ccm-2026-v1",
    "CCMC-Eligible Continuing Education",
    80,
    "minimum",
    "independent",
    null,
    "always",
    "All 80 credits must be accepted under the current pre-approved or post-approved CCMC pathway and relate to the CCM exam knowledge domains and focus areas.",
    null,
    0,
  ],
  [
    "ccmc-ccm-2026-ethics",
    "ccmc-ccm-2026-v1",
    "Ethics",
    8,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least eight of the 80 accepted credits must be ethics credits. Enter only the ethics amount shown by the approval or accepted documentation.",
    null,
    1,
  ],
  [
    "aapc-cpc-single-2026-curriculum-a",
    "aapc-cpc-single-2026-v1",
    "Curriculum A",
    24,
    "minimum",
    "independent",
    null,
    "always",
    "For one CPC credential, at least 24 of the 36 CEUs must be Curriculum A. Use the curriculum designation on the AAPC-approved activity.",
    "AAPC curriculum",
    0,
  ],
  [
    "aapc-cpc-single-2026-curriculum-b",
    "aapc-cpc-single-2026-v1",
    "Curriculum B",
    12,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 12 of the 36 CEUs may be Curriculum B. Classify each CEU as Curriculum A or B, not both.",
    "AAPC curriculum",
    1,
  ],
  [
    "ahima-rhia-single-2026-hiim",
    "ahima-rhia-single-2026-v1",
    "HIIM Domain Continuing Education",
    24,
    "minimum",
    "independent",
    null,
    "always",
    "At least 24 of the 30 CEUs must fall within an AHIMA health information and informatics domain.",
    "AHIMA recertification content",
    0,
  ],
  [
    "ahima-rhia-single-2026-other-job-relevant",
    "ahima-rhia-single-2026-v1",
    "Other Job-Relevant Continuing Education",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than six of the 30 CEUs may be job-relevant education outside the current HIIM domains. Classify each CEU in one content group.",
    "AHIMA recertification content",
    1,
  ],
  [
    "ahima-ccs-single-2026-hiim",
    "ahima-ccs-single-2026-v1",
    "HIIM Domain Continuing Education",
    16,
    "minimum",
    "independent",
    null,
    "always",
    "At least 16 of the 20 CEUs must fall within an AHIMA health information and informatics domain.",
    "AHIMA recertification content",
    0,
  ],
  [
    "ahima-ccs-single-2026-other-job-relevant",
    "ahima-ccs-single-2026-v1",
    "Other Job-Relevant Continuing Education",
    4,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than four of the 20 CEUs may be job-relevant education outside the current HIIM domains. Classify each CEU in one content group.",
    "AHIMA recertification content",
    1,
  ],
  [
    "ascp-mls-2026-blood-banking",
    "ascp-mls-cmp-2026-v1",
    "Blood Banking",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least two CMP points to the ASCP blood-banking requirement.",
    "ASCP MLS CMP point allocation",
    0,
  ],
  [
    "ascp-mls-2026-chemistry",
    "ascp-mls-cmp-2026-v1",
    "Chemistry",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least two CMP points to the ASCP chemistry requirement.",
    "ASCP MLS CMP point allocation",
    1,
  ],
  [
    "ascp-mls-2026-hematology",
    "ascp-mls-cmp-2026-v1",
    "Hematology",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least two CMP points to the ASCP hematology requirement.",
    "ASCP MLS CMP point allocation",
    2,
  ],
  [
    "ascp-mls-2026-microbiology",
    "ascp-mls-cmp-2026-v1",
    "Microbiology",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least two CMP points to the ASCP microbiology requirement.",
    "ASCP MLS CMP point allocation",
    3,
  ],
  [
    "ascp-mls-2026-safety",
    "ascp-mls-cmp-2026-v1",
    "Laboratory or Patient Safety",
    1,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least one CMP point to laboratory or patient safety.",
    "ASCP MLS CMP point allocation",
    4,
  ],
  [
    "ascp-mls-2026-ethics",
    "ascp-mls-cmp-2026-v1",
    "Medical Ethics",
    1,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least one CMP point to medical ethics.",
    "ASCP MLS CMP point allocation",
    5,
  ],
  [
    "ascp-mls-2026-related-content",
    "ascp-mls-cmp-2026-v1",
    "Other Accepted MLS-Related Content",
    26,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate the remaining 26 CMP points to accepted laboratory specialty, immunology, molecular biology, management, education, or other related content. Each point must be allocated once.",
    "ASCP MLS CMP point allocation",
    6,
  ],
  [
    "nbrc-rrt-full-ce-2026-category-i",
    "nbrc-rrt-full-ce-2026-v1",
    "Respiratory-Care Category I Continuing Education",
    30,
    "minimum",
    "independent",
    null,
    "always",
    "Use this full-CE template only when the NBRC dashboard requires 30 credits. All credited education must meet NBRC's Category I and respiratory-care relevance rules.",
    "NBRC RRT full-route CE activity type",
    0,
  ],
  [
    "nbrc-rrt-full-ce-2026-resuscitation",
    "nbrc-rrt-full-ce-2026-v1",
    "BLS, ACLS, NRP, and PALS Combined",
    12,
    "maximum",
    "nested",
    "nbrc-rrt-full-ce-2026-category-i",
    "optional",
    "When the state does not award CE for these courses, NBRC accepts six CEU hours for each successfully completed BLS, ACLS, NRP, or PALS course, with no more than 12 combined credits from those programs. Select this child instead of separately classifying the same units to the Category I parent.",
    "NBRC RRT full-route CE activity type",
    1,
  ],
  [
    "ardms-rdms-standard-moc-2026-cme",
    "ardms-rdms-standard-moc-2026-v1",
    "Accepted CME for a Period Ending in 2026 or Later",
    25,
    "minimum",
    "independent",
    null,
    "always",
    "Record 25 accepted CME credits only when the Inteleos dashboard shows that standard total. Annual SKILLS quizzes and renewal attestations are separate non-CME checklist obligations.",
    null,
    0,
  ],
  [
    "aama-cma-ce-2026-general",
    "aama-cma-ce-2026-v1",
    "General",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least 10 recertification points to AAMA General content.",
    "AAMA CMA content area",
    0,
  ],
  [
    "aama-cma-ce-2026-administrative",
    "aama-cma-ce-2026-v1",
    "Administrative",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least 10 recertification points to AAMA Administrative content.",
    "AAMA CMA content area",
    1,
  ],
  [
    "aama-cma-ce-2026-clinical",
    "aama-cma-ce-2026-v1",
    "Clinical",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate at least 10 recertification points to AAMA Clinical content. The remaining 30 points may be in any content area.",
    "AAMA CMA content area",
    2,
  ],
  [
    "aama-cma-ce-2026-aama-approved",
    "aama-cma-ce-2026-v1",
    "AAMA-Approved Continuing Education",
    30,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least 30 of the 60 points must be AAMA-approved CE. This provider-source classification overlaps the General, Administrative, or Clinical content classification.",
    null,
    3,
  ],
  [
    "nahq-cphq-2026-eligible-ce",
    "nahq-cphq-2026-v1",
    "CPHQ-Eligible Healthcare Quality Education",
    30,
    "minimum",
    "independent",
    null,
    "always",
    "All 30 credits must satisfy NAHQ's current healthcare-quality relevance, activity, timing, and documentation requirements.",
    null,
    0,
  ],
] as const satisfies readonly CategorySeedBinding[];

export const HEALTHCARE_CERTIFICATION_MAXIMUM_CLASSIFICATION_RULE_SET_IDS = [
  "nbcot-otr-2026-v1",
  "nbcot-cota-2026-v1",
  "nbcc-ncc-2026-v1",
  "aapc-cpc-single-2026-v1",
  "ahima-rhia-single-2026-v1",
  "ahima-ccs-single-2026-v1",
  "nbrc-rrt-full-ce-2026-v1",
] as const;

export const HEALTHCARE_CERTIFICATION_RENEWAL_TASK_COPY_BINDINGS = [
  [
    "ancc-fnp-150-ce-2026-v1",
    "Confirm the ANCC cycle, active RN license, FNP-BC status, and selection of the additional 75-contact-hour CE category",
    "Record 150 in-cycle FNP contact hours, including 25 pharmacology and at least 120 formally approved hours, with audit evidence",
    "Transfer the professional-development entries, complete the ANCC renewal application and attestations, pay, and save confirmation",
  ],
  [
    "aacn-ccrn-adult-direct-care-cerp-2026-v1",
    "Confirm adult direct-care CCRN status, the Synergy CERP path, AACN dates, and a current unencumbered RN or APRN license",
    "Record 100 CERPs with 60 A, 10 B, and 10 C, and document 432 eligible adult direct-care hours including 144 recent hours",
    "Submit the CCRN renewal attestations and payment by the AACN deadline and save approval and audit records",
  ],
  [
    "nbcot-otr-2026-v1",
    "Confirm the OTR cycle, good-standing status, exact MyNBCOT deadline, current handbook and activity chart, and any documented 2023-cohort carryover",
    "Record 36 NBCOT-calculated CAUs or PDUs with one activity classification per entry, required evidence, and every published cap",
    "Complete the OTR renewal application, attestations, and fee, save confirmation, and retain all renewal documentation for one full year",
  ],
  [
    "nbcot-cota-2026-v1",
    "Confirm the COTA cycle, good-standing status, exact MyNBCOT deadline, current handbook and activity chart, and any documented 2023-cohort carryover",
    "Record 36 NBCOT-calculated CAUs or PDUs with one activity classification per entry, required evidence, and every published cap",
    "Complete the COTA renewal application, attestations, and fee, save confirmation, and retain all renewal documentation for one full year",
  ],
  [
    "bacb-bcba-2026-v1",
    "Confirm the BACB cycle, good-standing status, exact expiration, and whether the supervision CEU condition applies",
    "Record 32 eligible CEUs with four ethics and, when the defined supervision trigger applies, three behavior-analytic supervision CEUs",
    "Enter every CEU and upload its supporting documentation before the recertification date, then apply, attest, pay, and save confirmation",
  ],
  [
    "nbcc-ncc-2026-v1",
    "Confirm standard-practice NCC status, the five-year account cycle, annual fees, ethics standing, and any specialty credentials",
    "Record 100 NBCC-qualifying clock hours after applying content, activity-limit, conversion, and documentation rules",
    "Complete the NCC recertification and disclosures, pay all required fees, and save NBCC confirmation",
  ],
  [
    "ccmc-ccm-2026-v1",
    "Confirm the CCM five-year cycle, exact May 31 or November 30 deadline, and continuing-education renewal path",
    "Report 80 CCMC-eligible credits with at least eight ethics credits and retain pre- or post-approval evidence",
    "Complete CCM conduct attestations and renewal payment, submit by the account deadline, and save confirmation",
  ],
  [
    "aapc-cpc-single-2026-v1",
    "Confirm one CPC credential, a normal full reporting cycle, current membership, and the account's reporting month",
    "Record 36 approved CEUs with at least 24 Curriculum A and no more than 12 Curriculum B, retaining index numbers and certificates",
    "Submit the CPC CEU report with membership renewal, resolve any audit, and save the accepted AAPC record",
  ],
  [
    "ahima-rhia-single-2026-v1",
    "Confirm one RHIA credential, a standard full cycle, exact AHIMA dates, and no synchronized or early-test adjustment",
    "Record 30 CEUs with at least 24 in HIIM domains and no more than six other job-relevant CEUs; retain evidence",
    "Submit the AHIMA recertification report and fee by the account deadline and save the accepted RHIA status",
  ],
  [
    "ahima-ccs-single-2026-v1",
    "Confirm one CCS credential, a standard full cycle, exact AHIMA dates, and no synchronized or early-test adjustment",
    "Record 20 CEUs with at least 16 in HIIM domains and no more than four other job-relevant CEUs; retain evidence",
    "Submit the AHIMA recertification report and fee by the account deadline and save the accepted CCS status",
  ],
  [
    "ascp-mls-cmp-2026-v1",
    "Confirm a time-limited MLS credential, the three-year CMP dates, and whether other ASCP credentials require separate declarations",
    "Record 36 CMP points, including two each in four laboratory disciplines plus one safety and one ethics point",
    "Submit the MLS CMP declaration and fee with supporting records, then save the updated ASCP credential status",
  ],
  [
    "nbrc-rrt-full-ce-2026-v1",
    "Confirm the NBRC dashboard requires 30 CE credits, the five-year RRT dates, and current annual CMP fees",
    "Record 30 respiratory-care Category I credits and keep combined BLS, ACLS, NRP, and PALS credit at or below 12 when the cap applies",
    "Complete the NBRC CMP submission by the examination-anniversary deadline and save renewed RRT status",
  ],
  [
    "ardms-rdms-standard-moc-2026-v1",
    "Confirm the RDMS dashboard shows a 25-CME period ending in 2026 or later and list every active specialty",
    "Record 25 accepted CME credits and each year complete four SKILLS quizzes per specialty with at least 80% cumulative performance",
    "By each December 31 complete annual payment, attestation, disclosure, and profile review; save CME-period completion evidence",
  ],
  [
    "aama-cma-ce-2026-v1",
    "Confirm a normal five-year CMA (AAMA) cycle, the continuing-education path, and the exact account deadline",
    "Record 60 points with 10 General, 10 Administrative, 10 Clinical, and at least 30 AAMA-approved points",
    "Submit the CMA recertification application and fee with any requested documentation and save the renewed credential record",
  ],
  [
    "nahq-cphq-2026-v1",
    "Confirm the CPHQ two-year cycle, exact December 31 earning deadline, and current recertification window",
    "Record 30 eligible healthcare-quality CE credits and retain activity evidence for a possible audit",
    "Submit the CPHQ recertification application and fee on time and save the renewed-status confirmation",
  ],
] as const satisfies readonly RenewalTaskCopyBinding[];
