type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: string,
  isCurrent: number,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

export const INSURANCE_RULE_SET_SEED_BINDINGS = [
  [
    "ca-insurance-producer-major-lines-full-term-2026-v1",
    "ca-insurance-producer-major-lines-full-term",
    1,
    "Insurance",
    "Resident Major-Line Insurance Producer — base CE only, no product-specific training",
    "California",
    "California Department of Insurance",
    24,
    "CE hours",
    24,
    "https://www.insurance.ca.gov/0200-industry/0090-faq/education/continuing-ed/index.cfm",
    "California Department of Insurance continuing-education guidance for the base requirement in a standard full two-year resident Property, Casualty, Personal Lines, Life-Only, or Accident and Health or Sickness license term. This deliberately narrow template is not a complete product-authority compliance plan: use it only after confirming that no flood, annuity, long-term-care, specified-life, variable-life, or other product-specific training applies, or after adding every applicable official overlay as a custom requirement. Use CDI's official license class and expiration date. The full 24 hours, including three ethics hours, apply at the first renewal; this template does not apply the age-and-tenure exemption, inactive-period rules, or other exceptions. CDI allows qualifying excess completed on time to appear in the next term but publishes no numeric cap; Vigilo never copies carryover automatically, so add only CDI-posted credit with evidence, and never carry excess ethics. A provider's 30-day reporting window does not extend the expiration deadline.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-insurance-producer-major-lines-full-term-2026-v1",
    "tx-insurance-producer-major-lines-full-term",
    1,
    "Insurance",
    "Resident Major-Line Insurance Producer — standard full term",
    "Texas",
    "Texas Department of Insurance",
    24,
    "CE hours",
    24,
    "https://www.tdi.texas.gov/agent/agcehome.html",
    "Texas Department of Insurance continuing-education guidance for a standard full two-year resident General Lines Life, Accident and Health and HMO, General Lines Property and Casualty, Life Agent, or Personal Lines Property and Casualty review period. Use TDI's official review date, which is the license expiration date. A shorter initial period is not this template: Texas prorates at one hour per whole licensed month, up to 24, and requires no CE when the prorated period is under six months. This template does not infer the 20-year exemption or an extension. Excess hours do not carry forward. Providers report electronically, but pending provider reporting does not extend the expiration deadline. Flood, annuity, and long-term-care Partnership training have separate triggers and timing and must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-life-under-6-years-2026-v1",
    "fl-insurance-producer-life-under-6-years",
    1,
    "Insurance",
    "Resident Life Producer — licensed under 6 years",
    "Florida",
    "Florida Department of Financial Services",
    24,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Life producer licensed fewer than six years: the four-hour 5-214 Law and Ethics Update plus 20 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-life-6-plus-years-2026-v1",
    "fl-insurance-producer-life-6-plus-years",
    1,
    "Insurance",
    "Resident Life Producer — licensed 6 or more years",
    "Florida",
    "Florida Department of Financial Services",
    20,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Life producer licensed at least six years who is not using an approved 25-year reduction: the four-hour 5-214 Law and Ethics Update plus 16 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-life-approved-25-plus-years-2026-v1",
    "fl-insurance-producer-life-approved-25-plus-years",
    1,
    "Insurance",
    "Resident Life Producer — approved 25-year reduction",
    "Florida",
    "Florida Department of Financial Services",
    10,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Life producer with at least 25 years licensed and an approved CLU, CPCU, or qualifying insurance or risk-management degree reduction: the four-hour 5-214 Law and Ethics Update plus six elective hours. Tenure alone does not qualify; use this variant only after DFS approval is shown in the official record, and use MyProfile's exact dates. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Vigilo never copies statutory carryover automatically; add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-health-under-6-years-2026-v1",
    "fl-insurance-producer-health-under-6-years",
    1,
    "Insurance",
    "Resident Health Producer — licensed under 6 years",
    "Florida",
    "Florida Department of Financial Services",
    24,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Health producer licensed fewer than six years: the four-hour 5-240 Law and Ethics Update plus 20 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-health-6-plus-years-2026-v1",
    "fl-insurance-producer-health-6-plus-years",
    1,
    "Insurance",
    "Resident Health Producer — licensed 6 or more years",
    "Florida",
    "Florida Department of Financial Services",
    20,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Health producer licensed at least six years who is not using an approved 25-year reduction: the four-hour 5-240 Law and Ethics Update plus 16 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-health-approved-25-plus-years-2026-v1",
    "fl-insurance-producer-health-approved-25-plus-years",
    1,
    "Insurance",
    "Resident Health Producer — approved 25-year reduction",
    "Florida",
    "Florida Department of Financial Services",
    10,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Health producer with at least 25 years licensed and an approved CLU, CPCU, or qualifying insurance or risk-management degree reduction: the four-hour 5-240 Law and Ethics Update plus six elective hours. Tenure alone does not qualify; use this variant only after DFS approval is shown in the official record, and use MyProfile's exact dates. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Vigilo never copies statutory carryover automatically; add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-life-health-under-6-years-2026-v1",
    "fl-insurance-producer-life-health-under-6-years",
    1,
    "Insurance",
    "Resident Life and Health Producer — licensed under 6 years",
    "Florida",
    "Florida Department of Financial Services",
    24,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Life and Health producer licensed fewer than six years: the four-hour 5-215 Law and Ethics Update plus 20 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-life-health-6-plus-years-2026-v1",
    "fl-insurance-producer-life-health-6-plus-years",
    1,
    "Insurance",
    "Resident Life and Health Producer — licensed 6 or more years",
    "Florida",
    "Florida Department of Financial Services",
    20,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Life and Health producer licensed at least six years who is not using an approved 25-year reduction: the four-hour 5-215 Law and Ethics Update plus 16 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-life-health-approved-25-plus-years-2026-v1",
    "fl-insurance-producer-life-health-approved-25-plus-years",
    1,
    "Insurance",
    "Resident Life and Health Producer — approved 25-year reduction",
    "Florida",
    "Florida Department of Financial Services",
    10,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident Life and Health producer with at least 25 years licensed and an approved CLU, CPCU, or qualifying insurance or risk-management degree reduction: the four-hour 5-215 Law and Ethics Update plus six elective hours. Tenure alone does not qualify; use this variant only after DFS approval is shown in the official record, and use MyProfile's exact dates. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Vigilo never copies statutory carryover automatically; add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-general-personal-lines-under-6-years-2026-v1",
    "fl-insurance-producer-general-personal-lines-under-6-years",
    1,
    "Insurance",
    "Resident General or Personal Lines Producer — licensed under 6 years",
    "Florida",
    "Florida Department of Financial Services",
    24,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident General or Personal Lines producer licensed fewer than six years: the four-hour 5-220 Law and Ethics Update plus 20 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-general-personal-lines-6-plus-years-2026-v1",
    "fl-insurance-producer-general-personal-lines-6-plus-years",
    1,
    "Insurance",
    "Resident General or Personal Lines Producer — licensed 6 or more years",
    "Florida",
    "Florida Department of Financial Services",
    20,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident General or Personal Lines producer licensed at least six years who is not using an approved 25-year reduction: the four-hour 5-220 Law and Ethics Update plus 16 elective hours. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. Use MyProfile's exact dates and select this tenure variant only after checking the official license history. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Statutory excess may carry to the next period, but no numeric cap is stated; Vigilo never copies carryover automatically, so add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-insurance-producer-general-personal-lines-approved-25-plus-years-2026-v1",
    "fl-insurance-producer-general-personal-lines-approved-25-plus-years",
    1,
    "Insurance",
    "Resident General or Personal Lines Producer — approved 25-year reduction",
    "Florida",
    "Florida Department of Financial Services",
    10,
    "CE hours",
    24,
    "https://myfloridacfo.com/division/agents/licensing/agents-and-adjusters/continuing-education",
    "Florida Department of Financial Services continuing-education guidance and section 626.2815 for a resident General or Personal Lines producer with at least 25 years licensed and an approved CLU, CPCU, or qualifying insurance or risk-management degree reduction: the four-hour 5-220 Law and Ethics Update plus six elective hours. Tenure alone does not qualify; use this variant only after DFS approval is shown in the official record, and use MyProfile's exact dates. Florida licenses are perpetual; this is a two-year CE compliance period, not a license-renewal term. A provider may take 21 days to report, but that reporting period does not extend the compliance deadline. Vigilo never copies statutory carryover automatically; add only MyProfile-confirmed credit with evidence, and do not treat carryover as the next period's required update. Flood, annuity, and long-term-care training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-insurance-producer-life-health-full-term-2026-v1",
    "ny-insurance-producer-life-health-full-term",
    1,
    "Insurance",
    "Resident Life or Accident and Health Producer — applicable full term",
    "New York",
    "New York State Department of Financial Services",
    15,
    "CE credits",
    24,
    "https://www.dfs.ny.gov/apps_and_licensing/agents_and_brokers/continuing_education",
    "New York State Department of Financial Services continuing-education guidance for a resident Life or Accident and Health producer whose license has been in effect for more than two years. Use the exact DFS license period and complete the credits before filing the renewal or relicensing application. Do not use this template to infer first-term applicability: a license in effect no more than two years can be CE-exempt, so verify the DFS record. Excess credits do not carry into a later period. Provider roster reporting does not extend the license-period or application deadline. Insurer-required annuity training is not a numeric New York license-maintenance category, and product-specific training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-insurance-producer-property-casualty-full-term-2026-v1",
    "ny-insurance-producer-property-casualty-full-term",
    1,
    "Insurance",
    "Resident Property and Casualty Producer — applicable full term",
    "New York",
    "New York State Department of Financial Services",
    15,
    "CE credits",
    24,
    "https://www.dfs.ny.gov/apps_and_licensing/agents_and_brokers/continuing_education",
    "New York State Department of Financial Services continuing-education guidance for a resident Property and Casualty producer whose license has been in effect for more than two years. Use the exact DFS license period and complete the credits before filing the renewal or relicensing application. Do not use this template to infer first-term applicability: a license in effect no more than two years can be CE-exempt, so verify the DFS record. The one-hour flood minimum applies to the P&C license; the enhanced three-hour flood minimum is an additional conditional category for a producer who sells through the National Flood Insurance Program. All category hours sit within the 15-credit total. Excess credits do not carry into a later period, and provider roster reporting does not extend the deadline. Other product-specific training must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-insurance-producer-major-lines-2026-v1",
    "nj-insurance-producer-major-lines",
    1,
    "Insurance",
    "Resident Major-Line Insurance Producer",
    "New Jersey",
    "New Jersey Department of Banking and Insurance",
    24,
    "CE credits",
    24,
    "https://www.nj.gov/dobi/prodfaqs.htm",
    "New Jersey Department of Banking and Insurance producer continuing-education guidance and N.J.A.C. 11:17-3.6 for a resident major-line individual producer. Complete 24 credits, including three professional-ethics credits, during the prior licensing term and use the PSI transcript and official expiration date. An initial term can be 18 through 23 months; the current rule does not publish a proration or first-renewal exemption, so this template retains 24 credits and requires PSI verification rather than inferring a reduction. Up to 12 qualifying credits may carry once, but ethics cannot carry; Vigilo never copies carryover automatically, so add only PSI-confirmed credit with evidence. A provider's 15-day banking period does not extend the license deadline. Flood, annuity, and long-term-care training have separate triggers and timing and must be tracked separately with custom requirements.",
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

export const INSURANCE_CATEGORY_SEED_BINDINGS = [
  [
    "ca-insurance-producer-major-lines-2026-ethics",
    "ca-insurance-producer-major-lines-full-term-2026-v1",
    "Ethics",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three approved ethics hours within the 24-hour total. Excess ethics does not carry into a later term.",
    null,
    0,
  ],
  [
    "ca-insurance-producer-major-lines-2026-fraud",
    "ca-insurance-producer-major-lines-full-term-2026-v1",
    "Insurance Fraud",
    1,
    "minimum",
    "nested",
    "ca-insurance-producer-major-lines-2026-ethics",
    "always",
    "At least one of the three ethics hours must cover insurance fraud; this is nested within Ethics and is not an additional hour beyond the 24-hour total.",
    null,
    1,
  ],
  [
    "tx-insurance-producer-major-lines-2026-ethics",
    "tx-insurance-producer-major-lines-full-term-2026-v1",
    "Ethics",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three ethics hours within the 24-hour standard full-term total.",
    null,
    0,
  ],
  [
    "tx-insurance-producer-major-lines-2026-classroom-equivalent",
    "tx-insurance-producer-major-lines-full-term-2026-v1",
    "Classroom or Classroom-Equivalent Delivery",
    12,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least half of the standard full-term total must use classroom or classroom-equivalent delivery. These 12 hours overlap the 24-hour total and may include qualifying ethics hours.",
    null,
    1,
  ],
  [
    "fl-insurance-producer-life-under-6-years-2026-update",
    "fl-insurance-producer-life-under-6-years-2026-v1",
    "Law and Ethics Update — Life (5-214)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-214 update within this compliance period. It is part of, not additional to, the 24-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-life-6-plus-years-2026-update",
    "fl-insurance-producer-life-6-plus-years-2026-v1",
    "Law and Ethics Update — Life (5-214)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-214 update within this compliance period. It is part of, not additional to, the 20-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-life-approved-25-plus-years-2026-update",
    "fl-insurance-producer-life-approved-25-plus-years-2026-v1",
    "Law and Ethics Update — Life (5-214)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-214 update within this compliance period. It is part of, not additional to, the 10-hour approved-reduction total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-health-under-6-years-2026-update",
    "fl-insurance-producer-health-under-6-years-2026-v1",
    "Law and Ethics Update — Health (5-240)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-240 update within this compliance period. It is part of, not additional to, the 24-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-health-6-plus-years-2026-update",
    "fl-insurance-producer-health-6-plus-years-2026-v1",
    "Law and Ethics Update — Health (5-240)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-240 update within this compliance period. It is part of, not additional to, the 20-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-health-approved-25-plus-years-2026-update",
    "fl-insurance-producer-health-approved-25-plus-years-2026-v1",
    "Law and Ethics Update — Health (5-240)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-240 update within this compliance period. It is part of, not additional to, the 10-hour approved-reduction total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-life-health-under-6-years-2026-update",
    "fl-insurance-producer-life-health-under-6-years-2026-v1",
    "Law and Ethics Update — Life and Health (5-215)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-215 update within this compliance period. It is part of, not additional to, the 24-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-life-health-6-plus-years-2026-update",
    "fl-insurance-producer-life-health-6-plus-years-2026-v1",
    "Law and Ethics Update — Life and Health (5-215)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-215 update within this compliance period. It is part of, not additional to, the 20-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-life-health-approved-25-plus-years-2026-update",
    "fl-insurance-producer-life-health-approved-25-plus-years-2026-v1",
    "Law and Ethics Update — Life and Health (5-215)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-215 update within this compliance period. It is part of, not additional to, the 10-hour approved-reduction total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-general-personal-lines-under-6-years-2026-update",
    "fl-insurance-producer-general-personal-lines-under-6-years-2026-v1",
    "Law and Ethics Update — General or Personal Lines (5-220)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-220 update within this compliance period. It is part of, not additional to, the 24-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-general-personal-lines-6-plus-years-2026-update",
    "fl-insurance-producer-general-personal-lines-6-plus-years-2026-v1",
    "Law and Ethics Update — General or Personal Lines (5-220)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-220 update within this compliance period. It is part of, not additional to, the 20-hour total.",
    null,
    0,
  ],
  [
    "fl-insurance-producer-general-personal-lines-approved-25-plus-years-2026-update",
    "fl-insurance-producer-general-personal-lines-approved-25-plus-years-2026-v1",
    "Law and Ethics Update — General or Personal Lines (5-220)",
    4,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the current four-hour 5-220 update within this compliance period. It is part of, not additional to, the 10-hour approved-reduction total.",
    null,
    0,
  ],
  [
    "ny-insurance-producer-life-health-2026-law",
    "ny-insurance-producer-life-health-full-term-2026-v1",
    "Insurance Law",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour of Insurance Law within the 15-credit total.",
    null,
    0,
  ],
  [
    "ny-insurance-producer-life-health-2026-ethics",
    "ny-insurance-producer-life-health-full-term-2026-v1",
    "Ethics and Professionalism",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour of Ethics and Professionalism within the 15-credit total.",
    null,
    1,
  ],
  [
    "ny-insurance-producer-life-health-2026-deib",
    "ny-insurance-producer-life-health-full-term-2026-v1",
    "Diversity, Inclusion, and Elimination of Bias",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour of Diversity, Inclusion, and Elimination of Bias within the 15-credit total.",
    null,
    2,
  ],
  [
    "ny-insurance-producer-property-casualty-2026-law",
    "ny-insurance-producer-property-casualty-full-term-2026-v1",
    "Insurance Law",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour of Insurance Law within the 15-credit total.",
    null,
    0,
  ],
  [
    "ny-insurance-producer-property-casualty-2026-ethics",
    "ny-insurance-producer-property-casualty-full-term-2026-v1",
    "Ethics and Professionalism",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour of Ethics and Professionalism within the 15-credit total.",
    null,
    1,
  ],
  [
    "ny-insurance-producer-property-casualty-2026-deib",
    "ny-insurance-producer-property-casualty-full-term-2026-v1",
    "Diversity, Inclusion, and Elimination of Bias",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour of Diversity, Inclusion, and Elimination of Bias within the 15-credit total.",
    null,
    2,
  ],
  [
    "ny-insurance-producer-property-casualty-2026-flood",
    "ny-insurance-producer-property-casualty-full-term-2026-v1",
    "Flood Insurance",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "A Property and Casualty licensee must complete at least one hour of flood-insurance instruction within the 15-credit total.",
    null,
    3,
  ],
  [
    "ny-insurance-producer-property-casualty-2026-enhanced-nfip",
    "ny-insurance-producer-property-casualty-full-term-2026-v1",
    "Enhanced National Flood Insurance Program Instruction",
    3,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the producer sells flood insurance through the National Flood Insurance Program. Track at least three enhanced-flood hours within the 15-credit total in addition to the P&C flood category, and confirm the course coding in the DFS record.",
    null,
    4,
  ],
  [
    "nj-insurance-producer-major-lines-2026-ethics",
    "nj-insurance-producer-major-lines-2026-v1",
    "Professional Ethics",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three professional-ethics credits within the 24-credit total. Ethics credits cannot carry into the next term.",
    null,
    0,
  ],
  [
    "nj-insurance-producer-major-lines-2026-fraud-option",
    "nj-insurance-producer-major-lines-2026-v1",
    "Insurance Fraud — optional ethics substitution",
    1,
    "informational",
    "nested",
    "nj-insurance-producer-major-lines-2026-ethics",
    "optional",
    "One insurance-fraud credit may substitute for one of the three professional-ethics credits. It is not a separate fourth-hour minimum.",
    null,
    1,
  ],
] as const satisfies readonly CategorySeedBinding[];

export const INSURANCE_RULE_SET_IDS = [
  "ca-insurance-producer-major-lines-full-term-2026-v1",
  "tx-insurance-producer-major-lines-full-term-2026-v1",
  "fl-insurance-producer-life-under-6-years-2026-v1",
  "fl-insurance-producer-life-6-plus-years-2026-v1",
  "fl-insurance-producer-life-approved-25-plus-years-2026-v1",
  "fl-insurance-producer-health-under-6-years-2026-v1",
  "fl-insurance-producer-health-6-plus-years-2026-v1",
  "fl-insurance-producer-health-approved-25-plus-years-2026-v1",
  "fl-insurance-producer-life-health-under-6-years-2026-v1",
  "fl-insurance-producer-life-health-6-plus-years-2026-v1",
  "fl-insurance-producer-life-health-approved-25-plus-years-2026-v1",
  "fl-insurance-producer-general-personal-lines-under-6-years-2026-v1",
  "fl-insurance-producer-general-personal-lines-6-plus-years-2026-v1",
  "fl-insurance-producer-general-personal-lines-approved-25-plus-years-2026-v1",
  "ny-insurance-producer-life-health-full-term-2026-v1",
  "ny-insurance-producer-property-casualty-full-term-2026-v1",
  "nj-insurance-producer-major-lines-2026-v1",
] as const;
