const ISC2_MAINTENANCE_HANDBOOK_URL =
  "https://edge.sitecorecloud.io/internationf173-xmc4e73-prodbc0f-9660/media/Project/ISC2/Main/Media/documents/members/MEM-Certification-Maintenance-Handbook-Digital.pdf";

const COMMON_ACTIVITY_CAVEAT =
  "ISC2 typically awards one CPE per activity hour in 0.25-credit increments; an individual activity is capped at 40 CPEs, its end date determines the cycle, unique work experience is capped at 10 CPEs per entry, and self-directed education is capped at 5 per book, 5 per magazine, and 1 per white paper. These are per-entry or per-item limits, not cycle-category caps.";

const STANDARD_MEMBER_CYCLE_CAVEAT =
  "Use the certification cycle and annual fee dates shown in the ISC2 Dashboard rather than deriving them from an exam or award date. The annual CPE figures are suggested pacing targets, not annual CPE gates. ISC2 charges one annual U.S. $135 AMF for a member holding one or more non-CC certifications, subject to change. Certified members may earn and manually submit outstanding CPEs during the 90-day grace period after cycle expiration; automatic CPE posting does not apply during grace. When all required CPEs and AMFs are satisfied, ISC2 renews the certification automatically.";

function standardSourceNote({
  credential,
  annualPace,
  groupAFloor,
  groupBCap,
  rolloverCap,
}: {
  credential: string;
  annualPace: string;
  groupAFloor: number;
  groupBCap: number;
  rolloverCap: number;
}) {
  return `ISC2 Certification Maintenance Handbook (January 2026) for the standard ${credential} three-year maintenance cycle: complete the full total with at least ${groupAFloor} Group A domain-related CPEs; Group B is optional general professional development and no more than ${groupBCap} Group B CPEs may count. ISC2 suggests ${annualPace}, but that is planning guidance only. ${STANDARD_MEMBER_CYCLE_CAVEAT} Only surplus Group A CPEs earned in the final six months may roll to the next cycle, automatically and up to ${rolloverCap}; Group B does not roll. License Lantern does not copy prior-cycle credit automatically, so record only rollover confirmed in the ISC2 Dashboard and retain that evidence. ${COMMON_ACTIVITY_CAVEAT}`;
}

export const ISC2_RULE_SET_SEED_BINDINGS = [
  [
    "isc2-cc-2026-v1",
    "isc2-cc",
    1,
    "Cybersecurity",
    "Certified in Cybersecurity (CC) — standard maintenance cycle",
    "Global",
    "ISC2",
    45,
    "CPE credits",
    36,
    ISC2_MAINTENANCE_HANDBOOK_URL,
    `ISC2 Certification Maintenance Handbook (January 2026) for the standard CC three-year maintenance cycle: complete 45 Group A domain-related CPEs; Group B is not accepted. ISC2 suggests 15 Group A CPEs annually, but that is planning guidance only, not an annual CPE gate. Use the certification cycle and annual fee dates shown in the ISC2 Dashboard rather than deriving them from an exam or award date. A member holding only CC pays an annual U.S. $50 AMF, subject to change; a member who also holds another ISC2 certification pays ISC2's single certified-member AMF instead. Certified members may earn and manually submit outstanding CPEs during the 90-day grace period after cycle expiration; automatic CPE posting does not apply during grace. When all required CPEs and AMFs are satisfied, ISC2 renews the certification automatically. Only surplus Group A CPEs earned in the final six months may roll to the next cycle, automatically and up to 15. License Lantern does not copy prior-cycle credit automatically, so record only rollover confirmed in the ISC2 Dashboard and retain that evidence. ${COMMON_ACTIVITY_CAVEAT}`,
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "isc2-cissp-2026-v1",
    "isc2-cissp",
    1,
    "Cybersecurity",
    "Certified Information Systems Security Professional (CISSP) — standard maintenance cycle",
    "Global",
    "ISC2",
    120,
    "CPE credits",
    36,
    ISC2_MAINTENANCE_HANDBOOK_URL,
    standardSourceNote({
      credential: "CISSP",
      annualPace: "40 CPEs annually (30 Group A plus 10 Group A or B)",
      groupAFloor: 90,
      groupBCap: 30,
      rolloverCap: 40,
    }),
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "isc2-ccsp-2026-v1",
    "isc2-ccsp",
    1,
    "Cybersecurity",
    "Certified Cloud Security Professional (CCSP) — standard maintenance cycle",
    "Global",
    "ISC2",
    90,
    "CPE credits",
    36,
    ISC2_MAINTENANCE_HANDBOOK_URL,
    standardSourceNote({
      credential: "CCSP",
      annualPace: "30 CPEs annually (20 Group A plus 10 Group A or B)",
      groupAFloor: 60,
      groupBCap: 30,
      rolloverCap: 30,
    }),
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "isc2-sscp-2026-v1",
    "isc2-sscp",
    1,
    "Cybersecurity",
    "Systems Security Certified Practitioner (SSCP) — standard maintenance cycle",
    "Global",
    "ISC2",
    60,
    "CPE credits",
    36,
    ISC2_MAINTENANCE_HANDBOOK_URL,
    standardSourceNote({
      credential: "SSCP",
      annualPace: "20 CPEs annually (15 Group A plus 5 Group A or B)",
      groupAFloor: 45,
      groupBCap: 15,
      rolloverCap: 20,
    }),
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "isc2-csslp-2026-v1",
    "isc2-csslp",
    1,
    "Cybersecurity",
    "Certified Secure Software Lifecycle Professional (CSSLP) — standard maintenance cycle",
    "Global",
    "ISC2",
    90,
    "CPE credits",
    36,
    ISC2_MAINTENANCE_HANDBOOK_URL,
    standardSourceNote({
      credential: "CSSLP",
      annualPace: "30 CPEs annually (20 Group A plus 10 Group A or B)",
      groupAFloor: 60,
      groupBCap: 30,
      rolloverCap: 30,
    }),
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
  [
    "isc2-cgrc-2026-v1",
    "isc2-cgrc",
    1,
    "Cybersecurity",
    "Governance, Risk and Compliance Certification (CGRC) — standard maintenance cycle",
    "Global",
    "ISC2",
    60,
    "CPE credits",
    36,
    ISC2_MAINTENANCE_HANDBOOK_URL,
    standardSourceNote({
      credential: "CGRC",
      annualPace: "20 CPEs annually (15 Group A plus 5 Group A or B)",
      groupAFloor: 45,
      groupBCap: 15,
      rolloverCap: 20,
    }),
    null,
    "2026-07-26",
    "source_linked_check_conditions",
    1,
  ],
] as const;

export const ISC2_CATEGORY_SEED_BINDINGS = [
  [
    "isc2-cc-2026-group-a",
    "isc2-cc-2026-v1",
    "Group A — Domain-Related CPE",
    45,
    "minimum",
    "independent",
    null,
    "always",
    "All 45 CPEs must relate directly to one or more CC domains. Group B professional-development credit is not accepted for CC.",
    null,
    0,
  ],
  [
    "isc2-cissp-2026-group-a",
    "isc2-cissp-2026-v1",
    "Group A — Domain-Related CPE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify CISSP-domain activity here. Because every credited time block must be classified as Group A or Group B and Group B is capped at 30, completing 120 countable CPEs enforces the 90-CPE Group A floor.",
    "ISC2 CISSP CPE classification",
    0,
  ],
  [
    "isc2-cissp-2026-group-b",
    "isc2-cissp-2026-v1",
    "Group B — Professional Development",
    30,
    "maximum",
    "independent",
    null,
    "always",
    "No more than 30 of the 120 countable CPEs may be general professional development outside the CISSP domains. Group B is optional, not a required minimum, and it cannot roll over.",
    "ISC2 CISSP CPE classification",
    1,
  ],
  [
    "isc2-ccsp-2026-group-a",
    "isc2-ccsp-2026-v1",
    "Group A — Domain-Related CPE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify CCSP-domain activity here. Because every credited time block must be classified as Group A or Group B and Group B is capped at 30, completing 90 countable CPEs enforces the 60-CPE Group A floor.",
    "ISC2 CCSP CPE classification",
    0,
  ],
  [
    "isc2-ccsp-2026-group-b",
    "isc2-ccsp-2026-v1",
    "Group B — Professional Development",
    30,
    "maximum",
    "independent",
    null,
    "always",
    "No more than 30 of the 90 countable CPEs may be general professional development outside the CCSP domains. Group B is optional, not a required minimum, and it cannot roll over.",
    "ISC2 CCSP CPE classification",
    1,
  ],
  [
    "isc2-sscp-2026-group-a",
    "isc2-sscp-2026-v1",
    "Group A — Domain-Related CPE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify SSCP-domain activity here. Because every credited time block must be classified as Group A or Group B and Group B is capped at 15, completing 60 countable CPEs enforces the 45-CPE Group A floor.",
    "ISC2 SSCP CPE classification",
    0,
  ],
  [
    "isc2-sscp-2026-group-b",
    "isc2-sscp-2026-v1",
    "Group B — Professional Development",
    15,
    "maximum",
    "independent",
    null,
    "always",
    "No more than 15 of the 60 countable CPEs may be general professional development outside the SSCP domains. Group B is optional, not a required minimum, and it cannot roll over.",
    "ISC2 SSCP CPE classification",
    1,
  ],
  [
    "isc2-csslp-2026-group-a",
    "isc2-csslp-2026-v1",
    "Group A — Domain-Related CPE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify CSSLP-domain activity here. Because every credited time block must be classified as Group A or Group B and Group B is capped at 30, completing 90 countable CPEs enforces the 60-CPE Group A floor.",
    "ISC2 CSSLP CPE classification",
    0,
  ],
  [
    "isc2-csslp-2026-group-b",
    "isc2-csslp-2026-v1",
    "Group B — Professional Development",
    30,
    "maximum",
    "independent",
    null,
    "always",
    "No more than 30 of the 90 countable CPEs may be general professional development outside the CSSLP domains. Group B is optional, not a required minimum, and it cannot roll over.",
    "ISC2 CSSLP CPE classification",
    1,
  ],
  [
    "isc2-cgrc-2026-group-a",
    "isc2-cgrc-2026-v1",
    "Group A — Domain-Related CPE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify CGRC-domain activity here. Because every credited time block must be classified as Group A or Group B and Group B is capped at 15, completing 60 countable CPEs enforces the 45-CPE Group A floor.",
    "ISC2 CGRC CPE classification",
    0,
  ],
  [
    "isc2-cgrc-2026-group-b",
    "isc2-cgrc-2026-v1",
    "Group B — Professional Development",
    15,
    "maximum",
    "independent",
    null,
    "always",
    "No more than 15 of the 60 countable CPEs may be general professional development outside the CGRC domains. Group B is optional, not a required minimum, and it cannot roll over.",
    "ISC2 CGRC CPE classification",
    1,
  ],
] as const;
