type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

const CA_BBS_RULE_SET_ID =
  "ca-bbs-lmft-lcsw-lpcc-standard-2026-v1";
const TX_LPC_RULE_SET_ID = "tx-lpc-standard-renewal-2026-v1";
const NY_SOCIAL_WORK_RULE_SET_ID =
  "ny-lmsw-lcsw-standard-registration-2026-v1";
const NJ_LPC_RULE_SET_ID = "nj-lpc-standard-renewal-2026-v1";
const PA_LPC_RULE_SET_ID = "pa-lpc-standard-renewal-2026-v1";
const FL_ETHICS_PHASE_RULE_SET_ID =
  "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-v1";
const FL_TELEHEALTH_PHASE_RULE_SET_ID =
  "fl-lcsw-lmft-lmhc-telehealth-phase-2026-v1";

const CA_BBS_ACTIVITY_SOURCE_GROUP =
  "California BBS CE activity source";
const TX_LPC_ACTIVITY_SOURCE_GROUP = "Texas LPC CE activity source";
const NY_SOCIAL_WORK_DELIVERY_GROUP =
  "New York social-work CE delivery type";
const NJ_LPC_ACTIVITY_SOURCE_GROUP = "New Jersey LPC CE activity source";
const FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP =
  "Florida mental-health CE credit bucket";
const FL_MENTAL_HEALTH_CONTENT_TYPE_GROUP =
  "Florida mental-health CE content type";
const FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP =
  "Florida mental-health CE activity source";

const CA_BBS_GENERAL_ACTIVITY_CATEGORY_ID =
  "ca-bbs-lmft-lcsw-lpcc-standard-2026-other-qualifying-ce";
const TX_LPC_GENERAL_ACTIVITY_CATEGORY_ID =
  "tx-lpc-standard-renewal-2026-other-qualifying-ce";
const NY_SOCIAL_WORK_GENERAL_DELIVERY_CATEGORY_ID =
  "ny-lmsw-lcsw-standard-registration-2026-other-approved-ce";
const NJ_LPC_GENERAL_ACTIVITY_CATEGORY_ID =
  "nj-lpc-standard-renewal-2026-other-qualifying-ce";
const FL_ETHICS_PHASE_GENERAL_CATEGORY_ID =
  "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-general";
const FL_TELEHEALTH_PHASE_GENERAL_CATEGORY_ID =
  "fl-lcsw-lmft-lmhc-telehealth-phase-2026-general";

const LAST_VERIFIED_AT = "2026-07-26";

export const MENTAL_HEALTH_RULE_SET_SEED_BINDINGS = [
  [
    CA_BBS_RULE_SET_ID,
    "ca-bbs-lmft-lcsw-lpcc-standard",
    1,
    "Mental Health",
    "LMFT, LCSW, or LPCC — standard active renewal",
    "California",
    "California Board of Behavioral Sciences",
    36,
    "CE hours",
    24,
    "https://www.bbs.ca.gov/pdf/publications/ceinfo_brochure.pdf",
    "California Board of Behavioral Sciences Licensee Continuing Education Requirements and FAQ, revised May 2026, for a standard active LMFT, LCSW, or LPCC renewal. Complete 36 hours before submitting each renewal, including six current-period Law and Ethics hours. The first renewal is also 36 hours and is not prorated. Confirm the one-time Suicide Risk Assessment and Intervention and Telehealth requirements and the first-renewal HIV/AIDS requirement; a one-time course completed before the current renewal period can satisfy that one-time obligation but contributes no hours to the current 36. Supervisors must confirm their six-hour supervision CPD requirement. Teaching is capped at 18 hours. Alternative Board service may provide up to six Law and Ethics hours for enforcement-case review, subject-matter-expert work, or professional law-and-ethics review-committee participation; completion of a Board occupational-analysis survey provides six CE hours. Classify each credited activity source separately. Courses count in only one renewal period, so this template applies no carryover. Use the Board's actual issue/prior-expiration and expiration dates. Retain proof for at least two years after the renewal date. Inactive or retired status and a Board-granted pre-expiration waiver are outside this standard template. LEP is deliberately excluded because its first-renewal course stack differs and may total 37 hours.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    TX_LPC_RULE_SET_ID,
    "tx-lpc-standard-renewal",
    1,
    "Professional Counseling",
    "Licensed Professional Counselor — standard renewal",
    "Texas",
    "Texas Behavioral Health Executive Council",
    24,
    "CE hours",
    24,
    "https://bhec.texas.gov/wp-content/uploads/2026/03/LPC-Rulebook-2026-March.pdf",
    "Texas LPC Rulebook updated March 25, 2026, including 22 TAC 681.140, for an active LPC renewal. Complete 24 hours during each renewal period, including six ethics hours, three hours designed to ensure competency with a distinct population, at least 12 hours from an enumerated provider type, and the required human-trafficking-prevention course. A supervisor has an additional six-hour supervision topic requirement within the 24. The Texas jurisprudence examination is a separate task required every renewal; passing it may be claimed as one ethics hour, but this catalog does not misstate the exam as an ordinary numeric CE minimum. Up to 10 excess hours may carry only into the next period; License Lantern never copies them automatically, so add only Council- or CE Broker-posted carryover with evidence, using the actual prior-period date. This conservative template does not let a carried record satisfy a separate current-period topic or provider condition. BHEC requires licensees to report CE through CE Broker before completing renewal; do not derive that reporting requirement from the license expiration date alone. Initial expiration dates can produce a shorter official period under the Council's 180-day birthday rule, so use the official license period rather than deriving an initial 24-month term. Retain proof for at least three years.",
    "2025-07-20",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    NY_SOCIAL_WORK_RULE_SET_ID,
    "ny-lmsw-lcsw-standard-registration",
    1,
    "Social Work",
    "LMSW or LCSW — standard triennial registration",
    "New York",
    "New York State Education Department",
    36,
    "CE hours",
    36,
    "https://www.op.nysed.gov/professions/licensed-master-social-worker/continuing-education/continuing-education-faqs",
    "New York State Education Department social-work continuing-education guidance for a standard 36-month LMSW or LCSW registration period. Complete 36 approved hours, including three hours on maintaining appropriate professional boundaries. No more than 12 hours may be self-study; live courses delivered in person or through real-time interactive technology are not self-study. For a shorter subsequent registration, the total is one hour per month and self-study may be no more than one third, so use a custom prorated cycle instead of this template. The initial three-year registration is exempt, and hours do not carry forward. Child-abuse mandated training is a separate licensure/current-training condition rather than a recurring 36-hour subminimum. Mandated reporters, including those previously trained, must complete the updated curriculum by November 17, 2026; a licensee who completed the prior curriculum from November 1, 2022 through August 31, 2025 may qualify to complete NYSED's 15-minute addendum instead, so confirm the individual's record separately. For first-time teaching or presenting, credit may include the presentation time plus up to two preparation hours per presentation hour. A first-time authored article or book chapter earns two hours, a first-time authored book earns five hours, and approved higher-education coursework earns 15 hours per semester credit. These are per-activity valuations rather than aggregate caps. Lapsed-registration, reactivation, conditional-registration, adjustment, and exemption calculations are outside this standard template. Retain records for six years from completion.",
    "2023-04-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    NJ_LPC_RULE_SET_ID,
    "nj-lpc-standard-renewal",
    1,
    "Professional Counseling",
    "Licensed Professional Counselor — standard biennial renewal",
    "New Jersey",
    "New Jersey Professional Counselor Examiners Committee",
    40,
    "CE hours",
    24,
    "https://www.njconsumeraffairs.gov/regulations/Chapter-34-Subchapters-10-31-Professional-Counselors.pdf",
    "N.J.A.C. 13:34 Professional Counselor Examiners Committee rules for a standard LPC biennial renewal. Complete 40 hours, including five hours in legal standards and ethics, three hours in social and cultural competency, and one hour concerning prescription-opioid risks and signs of abuse, addiction, and diversion. The former first-renewal exemption was removed beginning with the biennium that commenced December 1, 2020, so this template does not waive or prorate an initial period. Up to 10 excess hours may carry to the next biennium, but opioid credit may not carry; License Lantern never copies carryover automatically, so add only Committee-supported credit with evidence. Graduate coursework earns 15 hours per semester credit, and first-time teaching of a graduate course earns 15 hours per semester credit taught. A refereed article earns four hours, capped at eight article hours per biennium. A new course or program presentation earns one and one-half hours per presentation hour, capped at nine presentation hours per biennium. Online courses are permitted without a numeric delivery cap. Use the official license dates, confirm any waiver, and retain verification for five years after renewal. This template is for LPC only and does not duplicate the existing New Jersey LCSW ruleset.",
    "2020-12-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    PA_LPC_RULE_SET_ID,
    "pa-lpc-standard-renewal",
    1,
    "Professional Counseling",
    "Licensed Professional Counselor — standard full biennial renewal",
    "Pennsylvania",
    "Pennsylvania State Board of Social Workers, Marriage and Family Therapists and Professional Counselors",
    30,
    "CE hours",
    24,
    "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/social-workers-marriage-family-therapists-professional-counselors/professional-counselor-licensure-snapshot",
    "Pennsylvania Department of State Professional Counselor Licensure Requirements Snapshot and Board renewal guidance for a standard full biennial LPC renewal. Complete 30 approved hours, including three ethics hours, two hours of Act 31 child-abuse recognition and reporting training, and one hour of suicide-prevention education. Excess hours do not carry. A licensee's renewal following initial Pennsylvania licensure is exempt from the general continuing-education requirement, although Act 31 training still applies, so do not use this full-cycle template for that first renewal. Approved online education may supply all 30 hours; there is no live-hour minimum. Use PALS and the current Board renewal schedule for exact dates instead of hardcoding a prior cycle's deadline. Retain general CE documentation for four years; the approved Act 31 provider reports that training electronically.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    FL_ETHICS_PHASE_RULE_SET_ID,
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase",
    1,
    "Mental Health",
    "LCSW, LMFT, or LMHC — Ethics and Boundaries phase (user-confirmed)",
    "Florida",
    "Florida Board of Clinical Social Work, Marriage and Family Therapy and Mental Health Counseling",
    30,
    "CE hours",
    24,
    "https://floridasmentalhealthprofessions.gov/licensed-clinical-social-worker/",
    "Florida Board continuing-education table and Rules 64B4-6.001 through 64B4-6.003 for a standard LCSW, LMFT, or LMHC biennium in which CE Broker or the Board confirms Ethics and Boundaries as the current alternating three-hour phase. The 30 hours are non-overlapping buckets: 25 General, two Prevention of Medical Errors, and three Ethics and Boundaries. Within General, three Laws and Rules hours and two Domestic Violence hours apply every third biennium; a Qualified Supervisor also needs four supervisor-training hours every third biennium. Those individual phases initialize for confirmation and must not be inferred from the statewide calendar. No more than six of the 30 hours may be in administrative, office-management, or nonclinical skills. Presenter or moderator credit is capped at 10 hours per biennium, and full attendance at one qualifying disciplinary Board meeting earns three hours once per biennium. Rule 64B4-6.002 states five CE hours per semester hour taught for a graduate-course instructor, while the Board license webpage summarizes that method as up to five hours; obtain Board confirmation before relying on graduate-instructor credit because this template does not resolve that official-source conflict. The first biennial renewal is generally CE-exempt and is outside this template, but the separate initial two-hour Domestic Violence requirement within six months after licensure still must be confirmed. The biennium runs from April 1 of an odd year through March 31 of the next odd year, but use CE Broker for the licensee's exact status and reported credits. There is no home-study limit. This template applies no unverified carryover and requires mutually exclusive allocation among the three top-level credit buckets. Retain renewal CE documentation for at least two years following the renewal period; the separate four-year retention guidance applies to initial HIV/AIDS and Domestic Violence certificates.",
    "2020-11-18",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "fl-lcsw-lmft-lmhc-telehealth-phase",
    1,
    "Mental Health",
    "LCSW, LMFT, or LMHC — Telehealth phase (user-confirmed)",
    "Florida",
    "Florida Board of Clinical Social Work, Marriage and Family Therapy and Mental Health Counseling",
    30,
    "CE hours",
    24,
    "https://floridasmentalhealthprofessions.gov/licensed-clinical-social-worker/",
    "Florida Board continuing-education table and Rules 64B4-6.001 through 64B4-6.003 for a standard LCSW, LMFT, or LMHC biennium in which CE Broker or the Board confirms Telehealth as the current alternating three-hour phase. The 30 hours are non-overlapping buckets: 25 General, two Prevention of Medical Errors, and three Telehealth. Within General, three Laws and Rules hours and two Domestic Violence hours apply every third biennium; a Qualified Supervisor also needs four supervisor-training hours every third biennium. Those individual phases initialize for confirmation and must not be inferred from the statewide calendar. No more than six of the 30 hours may be in administrative, office-management, or nonclinical skills. Presenter or moderator credit is capped at 10 hours per biennium, and full attendance at one qualifying disciplinary Board meeting earns three hours once per biennium. Rule 64B4-6.002 states five CE hours per semester hour taught for a graduate-course instructor, while the Board license webpage summarizes that method as up to five hours; obtain Board confirmation before relying on graduate-instructor credit because this template does not resolve that official-source conflict. The first biennial renewal is generally CE-exempt and is outside this template, but the separate initial two-hour Domestic Violence requirement within six months after licensure still must be confirmed. The biennium runs from April 1 of an odd year through March 31 of the next odd year, but use CE Broker for the licensee's exact status and reported credits. There is no home-study limit. This template applies no unverified carryover and requires mutually exclusive allocation among the three top-level credit buckets. Retain renewal CE documentation for at least two years following the renewal period; the separate four-year retention guidance applies to initial HIV/AIDS and Domestic Violence certificates.",
    "2020-11-18",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

export const MENTAL_HEALTH_CATEGORY_SEED_BINDINGS = [
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-law-ethics",
    CA_BBS_RULE_SET_ID,
    "Law and Ethics",
    6,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete six Board-accepted Law and Ethics hours during every renewal period. They count within the 36-hour total.",
    null,
    0,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-suicide-risk",
    CA_BBS_RULE_SET_ID,
    "Suicide Risk Assessment and Intervention — one time",
    6,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Confirm whether the Board has already accepted this one-time requirement. It applies to renewal or reactivation after January 1, 2021 unless previously satisfied. If completed during this renewal period, the six hours count within 36; a completion before the period satisfies only the one-time condition and contributes no current-period hours.",
    null,
    1,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-telehealth",
    CA_BBS_RULE_SET_ID,
    "Telehealth — one time",
    3,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Confirm whether the Board has already accepted this one-time requirement. It applies to renewal or reactivation after July 1, 2023 unless previously satisfied. If completed during this renewal period, the three hours count within 36; a completion before the period satisfies only the one-time condition and contributes no current-period hours.",
    null,
    2,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-hiv-aids",
    CA_BBS_RULE_SET_ID,
    "HIV/AIDS — first renewal",
    7,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies to the first active LMFT, LCSW, or LPCC renewal unless the Board confirms the one-time course was already satisfied. The first renewal still requires 36 total hours and is not prorated. Credit these seven hours toward the current 36 only when completed during the current renewal period.",
    null,
    3,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-supervision-cpd",
    CA_BBS_RULE_SET_ID,
    "Supervision Continuing Professional Development",
    6,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the licensee supervises associates or MFT trainees. Complete six hours of supervision CPD each renewal period. Qualifying CE may count within the 36-hour total, but a supervisor-specific Law and Ethics course cannot also satisfy the general six-hour Law and Ethics minimum.",
    null,
    4,
  ],
  [
    CA_BBS_GENERAL_ACTIVITY_CATEGORY_ID,
    CA_BBS_RULE_SET_ID,
    "Other Qualifying CE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Activity-source catchall for countable CE not claimed for teaching or one of the four Board-service credit methods. Classify every credited time block once in this activity-source group; topic tags such as Law and Ethics may overlap the selected activity source.",
    CA_BBS_ACTIVITY_SOURCE_GROUP,
    5,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-teaching",
    CA_BBS_RULE_SET_ID,
    "Teaching for a Board-Accepted CE Provider",
    18,
    "maximum",
    "independent",
    null,
    "optional",
    "At most 18 of the 36 hours may be claimed for teaching for a Board-accepted CE provider. Credit equals what an attendee would receive, and the same course may be claimed only once in one renewal period. Select this activity-source classifier instead of Other Qualifying CE for the teaching hours.",
    CA_BBS_ACTIVITY_SOURCE_GROUP,
    6,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-enforcement-case-review",
    CA_BBS_RULE_SET_ID,
    "BBS Enforcement-Case Review",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "At most six hours may be claimed for reviewing Board enforcement cases under the Board's authorized program, and those hours may satisfy Law and Ethics. Select this activity-source classifier instead of Other Qualifying CE for the credited Board service.",
    CA_BBS_ACTIVITY_SOURCE_GROUP,
    7,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-subject-matter-expert",
    CA_BBS_RULE_SET_ID,
    "BBS Subject-Matter-Expert Service",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "At most six hours may be claimed for qualifying service as a Board subject-matter expert, and those hours may satisfy Law and Ethics. Select this activity-source classifier instead of Other Qualifying CE for the credited Board service.",
    CA_BBS_ACTIVITY_SOURCE_GROUP,
    8,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-law-ethics-review-committee",
    CA_BBS_RULE_SET_ID,
    "Professional Law-and-Ethics Review Committee",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "At most six hours may be claimed for qualifying participation on a professional law-and-ethics review committee, and those hours may satisfy Law and Ethics. Select this activity-source classifier instead of Other Qualifying CE for the credited committee service.",
    CA_BBS_ACTIVITY_SOURCE_GROUP,
    9,
  ],
  [
    "ca-bbs-lmft-lcsw-lpcc-standard-2026-occupational-analysis-survey",
    CA_BBS_RULE_SET_ID,
    "BBS Occupational-Analysis Survey",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "A completed Board occupational-analysis survey provides six CE hours. Record the Board's six-hour award once and select this activity-source classifier instead of Other Qualifying CE.",
    CA_BBS_ACTIVITY_SOURCE_GROUP,
    10,
  ],
  [
    "tx-lpc-standard-renewal-2026-ethics",
    TX_LPC_RULE_SET_ID,
    "Ethics",
    6,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete six ethics hours within the 24-hour total. Passing the separately required Texas jurisprudence examination may be claimed as one of these hours.",
    null,
    0,
  ],
  [
    "tx-lpc-standard-renewal-2026-distinct-population",
    TX_LPC_RULE_SET_ID,
    "Competency in Services to a Distinct Population",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three hours designed to ensure competency when providing services to a distinct population chosen by the licensee. They count within the 24-hour total.",
    null,
    1,
  ],
  [
    "tx-lpc-standard-renewal-2026-enumerated-provider",
    TX_LPC_RULE_SET_ID,
    "Enumerated Provider-Type CE",
    12,
    "minimum",
    "overlapping",
    null,
    "always",
    "At least 50 percent of the 24 hours must come from one or more provider types enumerated in 22 TAC 681.140(e). Confirm provider eligibility from the completion record; a topic match alone does not establish this source requirement.",
    null,
    2,
  ],
  [
    "tx-lpc-standard-renewal-2026-human-trafficking",
    TX_LPC_RULE_SET_ID,
    "Human Trafficking Prevention",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete the human-trafficking-prevention course required as a condition of each renewal. Successful completion may claim one CE hour within the 24-hour total; do not infer additional credit from a longer course unless it independently qualifies under another part of the rule.",
    null,
    3,
  ],
  [
    "tx-lpc-standard-renewal-2026-supervision",
    TX_LPC_RULE_SET_ID,
    "Supervision",
    6,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the LPC holds supervisory status. Complete six supervision hours within the 24-hour total.",
    null,
    4,
  ],
  [
    "tx-lpc-standard-renewal-2026-confirmed-carryover",
    TX_LPC_RULE_SET_ID,
    "Confirmed Prior-Period Carryover",
    10,
    "maximum",
    "independent",
    null,
    "conditional",
    "Optional only when the Council or CE Broker record posts unused excess from the immediately preceding renewal period into this period. At most 10 hours may count. License Lantern never copies prior-period credit automatically; use the actual prior-period date, attach evidence, and do not use a carried record to satisfy a separate current-period topic or provider condition.",
    TX_LPC_ACTIVITY_SOURCE_GROUP,
    5,
  ],
  [
    TX_LPC_GENERAL_ACTIVITY_CATEGORY_ID,
    TX_LPC_RULE_SET_ID,
    "Other Qualifying CE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Activity-source catchall for countable CE not claimed under one of the four capped activity methods. Classify each credited time block once in this activity-source group; topic and provider-source tags may overlap the selected source.",
    TX_LPC_ACTIVITY_SOURCE_GROUP,
    6,
  ],
  [
    "tx-lpc-standard-renewal-2026-presentation",
    TX_LPC_RULE_SET_ID,
    "Preparing and Giving a CE Presentation",
    5,
    "maximum",
    "independent",
    null,
    "optional",
    "At most five hours may be claimed for preparing and giving a presentation at a continuing-education activity. Select this source classifier instead of Other Qualifying CE for those hours.",
    TX_LPC_ACTIVITY_SOURCE_GROUP,
    7,
  ],
  [
    "tx-lpc-standard-renewal-2026-authorship",
    TX_LPC_RULE_SET_ID,
    "Authoring a Book or Peer-Reviewed Article",
    5,
    "maximum",
    "independent",
    null,
    "optional",
    "At most five hours may be claimed for authoring a book or peer-reviewed article. Select this source classifier instead of Other Qualifying CE for those hours.",
    TX_LPC_ACTIVITY_SOURCE_GROUP,
    8,
  ],
  [
    "tx-lpc-standard-renewal-2026-graduate-course",
    TX_LPC_RULE_SET_ID,
    "Teaching or Attending a Graduate-Level Course",
    5,
    "maximum",
    "independent",
    null,
    "optional",
    "At most five hours may be claimed for teaching or attending a graduate-level course. Select this source classifier instead of Other Qualifying CE for those hours.",
    TX_LPC_ACTIVITY_SOURCE_GROUP,
    9,
  ],
  [
    "tx-lpc-standard-renewal-2026-self-study",
    TX_LPC_RULE_SET_ID,
    "Individual Self-Study",
    1,
    "maximum",
    "independent",
    null,
    "optional",
    "At most one hour may be claimed for an activity performed by the licensee acting alone. Individual viewing or listening within an organized third-party CE offering is not subject to this self-study cap and belongs in Other Qualifying CE when otherwise eligible.",
    TX_LPC_ACTIVITY_SOURCE_GROUP,
    10,
  ],
  [
    "ny-lmsw-lcsw-standard-registration-2026-boundaries",
    NY_SOCIAL_WORK_RULE_SET_ID,
    "Maintaining Appropriate Professional Boundaries",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three approved hours on maintaining appropriate professional boundaries within the 36-hour registration total.",
    null,
    0,
  ],
  [
    NY_SOCIAL_WORK_GENERAL_DELIVERY_CATEGORY_ID,
    NY_SOCIAL_WORK_RULE_SET_ID,
    "Other Approved CE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Delivery-type catchall for approved CE that is not self-study, including in-person and live real-time interactive online courses. Classify every credited time block once as either Other Approved CE or Self-Study; the professional-boundaries topic tag may overlap this delivery allocation.",
    NY_SOCIAL_WORK_DELIVERY_GROUP,
    1,
  ],
  [
    "ny-lmsw-lcsw-standard-registration-2026-self-study",
    NY_SOCIAL_WORK_RULE_SET_ID,
    "Self-Study",
    12,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 12 of 36 hours may consist of self-study educational activities from a New York State Education Department-approved provider. A live course with real-time interaction is not self-study. Select this delivery classifier instead of Other Approved CE for self-study hours.",
    NY_SOCIAL_WORK_DELIVERY_GROUP,
    2,
  ],
  [
    "nj-lpc-standard-renewal-2026-ethics",
    NJ_LPC_RULE_SET_ID,
    "Legal Standards and Ethics",
    5,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete five hours in legal standards and ethics within the 40-hour total.",
    null,
    0,
  ],
  [
    "nj-lpc-standard-renewal-2026-social-cultural",
    NJ_LPC_RULE_SET_ID,
    "Social and Cultural Competency",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three hours in social and cultural competency within the 40-hour total.",
    null,
    1,
  ],
  [
    "nj-lpc-standard-renewal-2026-opioid",
    NJ_LPC_RULE_SET_ID,
    "Prescription Opioid Drugs",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete one current-biennium hour concerning prescription-opioid risks and signs of abuse, addiction, and diversion. It counts within 40 and may not be carried from a prior biennium.",
    null,
    2,
  ],
  [
    "nj-lpc-standard-renewal-2026-confirmed-carryover",
    NJ_LPC_RULE_SET_ID,
    "Confirmed Prior-Biennium Carryover",
    10,
    "maximum",
    "independent",
    null,
    "conditional",
    "Optional only when Committee records post qualifying unused excess from the immediately preceding biennium into this biennium. At most 10 hours may count. License Lantern never copies credit automatically; use the actual prior-biennium date, attach evidence, and do not use a carried record to satisfy the current-period opioid or other topic requirements.",
    NJ_LPC_ACTIVITY_SOURCE_GROUP,
    3,
  ],
  [
    NJ_LPC_GENERAL_ACTIVITY_CATEGORY_ID,
    NJ_LPC_RULE_SET_ID,
    "Other Qualifying CE Activity",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Activity-source catchall for countable CE not claimed as a refereed article or a new course or program presentation. Classify every credited time block once in this source group. Graduate coursework earns 15 hours per semester credit, and first-time teaching of a graduate course earns 15 hours per semester credit taught.",
    NJ_LPC_ACTIVITY_SOURCE_GROUP,
    4,
  ],
  [
    "nj-lpc-standard-renewal-2026-refereed-articles",
    NJ_LPC_RULE_SET_ID,
    "Refereed Articles",
    8,
    "maximum",
    "independent",
    null,
    "optional",
    "A refereed article earns four CE hours, with no more than eight article hours allowed in one biennium. Select this activity-source classifier instead of Other Qualifying CE Activity for those hours.",
    NJ_LPC_ACTIVITY_SOURCE_GROUP,
    5,
  ],
  [
    "nj-lpc-standard-renewal-2026-new-course-program-presentation",
    NJ_LPC_RULE_SET_ID,
    "New Course or Program Presentation",
    9,
    "maximum",
    "independent",
    null,
    "optional",
    "A new course or program presentation earns one and one-half CE hours per presentation hour, with no more than nine presentation hours allowed in one biennium. Select this activity-source classifier instead of Other Qualifying CE Activity for those hours.",
    NJ_LPC_ACTIVITY_SOURCE_GROUP,
    6,
  ],
  [
    "pa-lpc-standard-renewal-2026-ethics",
    PA_LPC_RULE_SET_ID,
    "Ethics",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete three ethics hours within the 30-hour full-biennium total.",
    null,
    0,
  ],
  [
    "pa-lpc-standard-renewal-2026-child-abuse",
    PA_LPC_RULE_SET_ID,
    "Child Abuse Recognition and Reporting",
    2,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete two hours of Board-approved Act 31 child-abuse recognition and reporting training within the 30-hour total. The approved provider reports completion electronically.",
    null,
    1,
  ],
  [
    "pa-lpc-standard-renewal-2026-suicide-prevention",
    PA_LPC_RULE_SET_ID,
    "Suicide Prevention",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete one hour of Board-approved suicide-prevention continuing education within the 30-hour total.",
    null,
    2,
  ],
  [
    FL_ETHICS_PHASE_GENERAL_CATEGORY_ID,
    FL_ETHICS_PHASE_RULE_SET_ID,
    "General CE",
    25,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate 25 of the 30 hours to General CE. Use a nested General topic leaf instead of this parent for Laws and Rules, Domestic Violence, or Qualified Supervisor Training hours. The same time block cannot also be allocated to Medical Errors or Ethics and Boundaries.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    0,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-medical-errors",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Prevention of Medical Errors",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate two hours from a Board-approved Medical Errors provider. These hours are a separate bucket and do not also count toward General CE or Ethics and Boundaries.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    1,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-ethics-boundaries",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Ethics and Boundaries",
    3,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate three hours to the Ethics and Boundaries phase selected only after confirmation in CE Broker or with the Board. These hours are a separate bucket and do not also count toward General CE or Medical Errors.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    2,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-laws-rules",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Laws and Rules — every third biennium",
    3,
    "minimum",
    "nested",
    FL_ETHICS_PHASE_GENERAL_CATEGORY_ID,
    "conditional",
    "Confirm the licensee's individual CE Broker phase. When this is the applicable every-third biennium, complete three Laws and Rules hours as part of—not in addition to—the 25 General hours. Select this leaf instead of the General parent and do not allocate the same time to another credit bucket.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    3,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-domestic-violence",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Domestic Violence — every third biennium",
    2,
    "minimum",
    "nested",
    FL_ETHICS_PHASE_GENERAL_CATEGORY_ID,
    "conditional",
    "Confirm the licensee's individual CE Broker phase. When this is the applicable every-third biennium, complete two Domestic Violence hours as part of—not in addition to—the 25 General hours. Select this leaf instead of the General parent and do not allocate the same time to another credit bucket.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    4,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-supervisor-training",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Qualified Supervisor Training — every third biennium",
    4,
    "minimum",
    "nested",
    FL_ETHICS_PHASE_GENERAL_CATEGORY_ID,
    "conditional",
    "Applies only when the licensee is a Board-qualified supervisor and CE Broker confirms the applicable every-third biennium. Complete four supervisor-training hours as part of—not in addition to—the 25 General hours. Select this leaf instead of the General parent and do not allocate the same time to another credit bucket.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    5,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-clinical-other-content",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Clinical or Other Qualifying Content",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Content-type catchall for qualifying credit that is not administrative, office-management, or nonclinical-skills education. Classify every credited time block once in this content-type group; the selected top-level credit bucket and activity source may overlap this classifier.",
    FL_MENTAL_HEALTH_CONTENT_TYPE_GROUP,
    6,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-administrative-nonclinical",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Administrative, Office-Management, or Nonclinical Skills",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than six of the required 30 hours may be in administrative, office-management, or nonclinical skills. Select this content-type classifier instead of Clinical or Other Qualifying Content for those hours.",
    FL_MENTAL_HEALTH_CONTENT_TYPE_GROUP,
    7,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-other-qualifying-activity",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Other Qualifying CE Activity",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Activity-source catchall for qualifying CE not claimed for presenting, moderating, or attending a disciplinary Board meeting. Classify every credited time block once in this activity-source group; the selected credit bucket and content type may overlap this classifier.",
    FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP,
    8,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-presenter-moderator",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Presenter or Moderator",
    10,
    "maximum",
    "independent",
    null,
    "optional",
    "At most 10 hours per biennium may be claimed for qualifying presenter or moderator service. The program may be claimed only once, and the licensee must attend the entire program and retain the required certificate. Select this activity-source classifier instead of Other Qualifying CE Activity.",
    FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP,
    9,
  ],
  [
    "fl-lcsw-lmft-lmhc-ethics-boundaries-phase-2026-disciplinary-board-meeting",
    FL_ETHICS_PHASE_RULE_SET_ID,
    "Disciplinary Board Meeting",
    3,
    "maximum",
    "independent",
    null,
    "optional",
    "Full attendance at one qualifying disciplinary Board meeting earns three risk-management CE hours once per biennium. Record the three-hour award once, including the required sign-in and sign-out evidence, and select this activity-source classifier instead of Other Qualifying CE Activity.",
    FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP,
    10,
  ],
  [
    FL_TELEHEALTH_PHASE_GENERAL_CATEGORY_ID,
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "General CE",
    25,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate 25 of the 30 hours to General CE. Use a nested General topic leaf instead of this parent for Laws and Rules, Domestic Violence, or Qualified Supervisor Training hours. The same time block cannot also be allocated to Medical Errors or Telehealth.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    0,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-medical-errors",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Prevention of Medical Errors",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate two hours from a Board-approved Medical Errors provider. These hours are a separate bucket and do not also count toward General CE or Telehealth.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    1,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-telehealth",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Telehealth",
    3,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate three hours to the Telehealth phase selected only after confirmation in CE Broker or with the Board. These hours are a separate bucket and do not also count toward General CE or Medical Errors.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    2,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-laws-rules",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Laws and Rules — every third biennium",
    3,
    "minimum",
    "nested",
    FL_TELEHEALTH_PHASE_GENERAL_CATEGORY_ID,
    "conditional",
    "Confirm the licensee's individual CE Broker phase. When this is the applicable every-third biennium, complete three Laws and Rules hours as part of—not in addition to—the 25 General hours. Select this leaf instead of the General parent and do not allocate the same time to another credit bucket.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    3,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-domestic-violence",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Domestic Violence — every third biennium",
    2,
    "minimum",
    "nested",
    FL_TELEHEALTH_PHASE_GENERAL_CATEGORY_ID,
    "conditional",
    "Confirm the licensee's individual CE Broker phase. When this is the applicable every-third biennium, complete two Domestic Violence hours as part of—not in addition to—the 25 General hours. Select this leaf instead of the General parent and do not allocate the same time to another credit bucket.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    4,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-supervisor-training",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Qualified Supervisor Training — every third biennium",
    4,
    "minimum",
    "nested",
    FL_TELEHEALTH_PHASE_GENERAL_CATEGORY_ID,
    "conditional",
    "Applies only when the licensee is a Board-qualified supervisor and CE Broker confirms the applicable every-third biennium. Complete four supervisor-training hours as part of—not in addition to—the 25 General hours. Select this leaf instead of the General parent and do not allocate the same time to another credit bucket.",
    FL_MENTAL_HEALTH_CREDIT_BUCKET_GROUP,
    5,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-clinical-other-content",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Clinical or Other Qualifying Content",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Content-type catchall for qualifying credit that is not administrative, office-management, or nonclinical-skills education. Classify every credited time block once in this content-type group; the selected top-level credit bucket and activity source may overlap this classifier.",
    FL_MENTAL_HEALTH_CONTENT_TYPE_GROUP,
    6,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-administrative-nonclinical",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Administrative, Office-Management, or Nonclinical Skills",
    6,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than six of the required 30 hours may be in administrative, office-management, or nonclinical skills. Select this content-type classifier instead of Clinical or Other Qualifying Content for those hours.",
    FL_MENTAL_HEALTH_CONTENT_TYPE_GROUP,
    7,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-other-qualifying-activity",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Other Qualifying CE Activity",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Activity-source catchall for qualifying CE not claimed for presenting, moderating, or attending a disciplinary Board meeting. Classify every credited time block once in this activity-source group; the selected credit bucket and content type may overlap this classifier.",
    FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP,
    8,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-presenter-moderator",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Presenter or Moderator",
    10,
    "maximum",
    "independent",
    null,
    "optional",
    "At most 10 hours per biennium may be claimed for qualifying presenter or moderator service. The program may be claimed only once, and the licensee must attend the entire program and retain the required certificate. Select this activity-source classifier instead of Other Qualifying CE Activity.",
    FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP,
    9,
  ],
  [
    "fl-lcsw-lmft-lmhc-telehealth-phase-2026-disciplinary-board-meeting",
    FL_TELEHEALTH_PHASE_RULE_SET_ID,
    "Disciplinary Board Meeting",
    3,
    "maximum",
    "independent",
    null,
    "optional",
    "Full attendance at one qualifying disciplinary Board meeting earns three risk-management CE hours once per biennium. Record the three-hour award once, including the required sign-in and sign-out evidence, and select this activity-source classifier instead of Other Qualifying CE Activity.",
    FL_MENTAL_HEALTH_ACTIVITY_SOURCE_GROUP,
    10,
  ],
] as const satisfies readonly CategorySeedBinding[];

export const MENTAL_HEALTH_MAXIMUM_CLASSIFICATION_RULE_SET_IDS = [
  CA_BBS_RULE_SET_ID,
  TX_LPC_RULE_SET_ID,
  NY_SOCIAL_WORK_RULE_SET_ID,
  NJ_LPC_RULE_SET_ID,
  FL_ETHICS_PHASE_RULE_SET_ID,
  FL_TELEHEALTH_PHASE_RULE_SET_ID,
] as const;
