type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum",
  relation: "independent",
  parentCategoryId: null,
  applicability: "always",
  conditionNote: string,
  exclusiveGroup: string,
  sortOrder: number,
];

const NCCP_2025_MODEL_URL =
  "https://public.powerdms.com/Nat9346/documents/2703086";
const IMPORTANT_DATES_URL =
  "https://www.nremt.org/Handbooks/Recertification/Important-Dates-Time-Periods";
const RBE_URL =
  "https://www.nremt.org/Handbooks/Recertification/Recertification-by-Examination-%28RBE%29";
const DISTRIBUTIVE_EDUCATION_URL =
  "https://www.nremt.org/News/National-Registry-Board-Makes-Distributive-Educati";
const LAST_VERIFIED_AT = "2026-07-26";

function standardSourceNote({
  level,
  total,
  national,
  local,
  individual,
  expirationDate,
  reinstatementWindow,
  lapseDate,
  rbeApplicationDeadline,
  transitionDate,
  additionalNote = "",
}: {
  level: string;
  total: number;
  national: number;
  local: number;
  individual: number;
  expirationDate: string;
  reinstatementWindow: string;
  lapseDate: string;
  rbeApplicationDeadline: string;
  transitionDate: string;
  additionalNote?: string;
}) {
  return `National Registry ${level} continuing-education path under the 2025 NCCP model: ${total} total credits, classified once as ${national} National, ${local} Local/State, and ${individual} Individual credits. Official model: ${NCCP_2025_MODEL_URL}. The 2025 model applies to cycles assigned under the transition beginning ${transitionDate}; use the exact model, cycle start, and expiration displayed in the National Registry account. This template records a nominal 24-month cycle, but an initial certification can receive a two- or three-year future expiration, and an early continuing-education approval starts the next rolling cycle the following day without moving the fixed expiration. Credits must be completed inside the assigned cycle and by ${expirationDate}. If all education was completed by that date but the application was not submitted, the current late reinstatement window is ${reinstatementWindow}; education dated during reinstatement is not accepted, acceptance is not guaranteed, and certification lapses ${lapseDate}. Recertification by Examination is a separate one-attempt alternative, not an education category: apply by ${rbeApplicationDeadline}, pass by ${expirationDate}, and do not apply a reinstatement window to RBE. Official deadlines: ${IMPORTANT_DATES_URL}. Official RBE guide: ${RBE_URL}. There is no cross-cycle credit carryover; early rolling approval merely opens the new cycle for education completed afterward. Online/distributive education has no National Registry percentage cap when otherwise accepted; official removal: ${DISTRIBUTIVE_EDUCATION_URL}. This national-certification template does not infer compliance with any state EMS license. State expiration dates, mandatory Local topics, skills, BLS/CPR or ACLS conditions, reporting, and renewal rules must be tracked separately from official state and agency requirements.${additionalNote}`;
}

export const NREMT_RULE_SET_SEED_BINDINGS = [
  [
    "nremt-emr-nccp-ce-2025-v1",
    "nremt-emr-nccp-ce",
    1,
    "Emergency Medical Services",
    "Emergency Medical Responder (NREMR) — NCCP continuing-education path",
    "United States",
    "National Registry of Emergency Medical Technicians",
    16,
    "CE credits",
    24,
    "https://www.nremt.org/EMR/Recertification",
    standardSourceNote({
      level: "Emergency Medical Responder",
      total: 16,
      national: 8,
      local: 4,
      individual: 4,
      expirationDate: "September 30",
      reinstatementWindow: "October 1 through October 31",
      lapseDate: "November 1",
      rbeApplicationDeadline: "September 24",
      transitionDate: "October 1, 2025",
      additionalNote:
        " The current Important Dates page appears to contain an editorial error that labels September 30 itself as reinstatement; the level page and National Registry FAQ consistently identify September 30 as the normal deadline and October 1-31 as reinstatement, which is the cautious interpretation used here. A portal-assigned legacy 2016 EMR cycle ending September 30, 2026 must remain on its displayed model rather than being migrated to this template.",
    }),
    "2025-10-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nremt-emt-nccp-ce-2025-v1",
    "nremt-emt-nccp-ce",
    1,
    "Emergency Medical Services",
    "Emergency Medical Technician (NREMT) — NCCP continuing-education path",
    "United States",
    "National Registry of Emergency Medical Technicians",
    40,
    "CE credits",
    24,
    "https://www.nremt.org/EMT/Recertification",
    standardSourceNote({
      level: "Emergency Medical Technician",
      total: 40,
      national: 20,
      local: 10,
      individual: 10,
      expirationDate: "March 31",
      reinstatementWindow: "April 1 through April 30",
      lapseDate: "May 1",
      rbeApplicationDeadline: "March 25",
      transitionDate: "April 1, 2025",
    }),
    "2025-04-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nremt-aemt-nccp-ce-2025-v1",
    "nremt-aemt-nccp-ce",
    1,
    "Emergency Medical Services",
    "Advanced Emergency Medical Technician (NRAEMT) — NCCP continuing-education path",
    "United States",
    "National Registry of Emergency Medical Technicians",
    50,
    "CE credits",
    24,
    "https://www.nremt.org/AEMT/Recertification",
    standardSourceNote({
      level: "Advanced Emergency Medical Technician",
      total: 50,
      national: 25,
      local: 12.5,
      individual: 12.5,
      expirationDate: "March 31",
      reinstatementWindow: "April 1 through April 30",
      lapseDate: "May 1",
      rbeApplicationDeadline: "March 25",
      transitionDate: "April 1, 2025",
    }),
    "2025-04-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nremt-paramedic-nccp-ce-2025-v1",
    "nremt-paramedic-nccp-ce",
    1,
    "Emergency Medical Services",
    "Paramedic (NRP) — NCCP continuing-education path",
    "United States",
    "National Registry of Emergency Medical Technicians",
    60,
    "CE credits",
    24,
    "https://www.nremt.org/Paramedic/Recertification",
    standardSourceNote({
      level: "Paramedic",
      total: 60,
      national: 30,
      local: 15,
      individual: 15,
      expirationDate: "March 31",
      reinstatementWindow: "April 1 through April 30",
      lapseDate: "May 1",
      rbeApplicationDeadline: "March 25",
      transitionDate: "April 1, 2025",
    }),
    "2025-04-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

export const NREMT_CATEGORY_SEED_BINDINGS = [
  [
    "nremt-emr-nccp-ce-2025-national",
    "nremt-emr-nccp-ce-2025-v1",
    "National Component",
    8,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 8 National credits: Airway 1.5, Cardiology 2, Trauma 1, Medical 2.5, and Operations 1. At least 0.8 of the same National credits must contain pediatric content; pediatric is an overlapping content constraint, not an additional sixth bucket.",
    "nremt-emr-nccp-ce-2025-component",
    0,
  ],
  [
    "nremt-emr-nccp-ce-2025-local",
    "nremt-emr-nccp-ce-2025-v1",
    "Local/State Component",
    4,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 4 Local/State credits. A state, region, or agency may prescribe the topics; absent a prescription, accepted direct-patient-care EMS education is flexible. Do not also classify the same credited time as National or Individual.",
    "nremt-emr-nccp-ce-2025-component",
    1,
  ],
  [
    "nremt-emr-nccp-ce-2025-individual",
    "nremt-emr-nccp-ce-2025-v1",
    "Individual Component",
    4,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 4 flexible Individual credits using otherwise accepted EMS-related education. Do not also classify the same credited time as National or Local/State.",
    "nremt-emr-nccp-ce-2025-component",
    2,
  ],
  [
    "nremt-emt-nccp-ce-2025-national",
    "nremt-emt-nccp-ce-2025-v1",
    "National Component",
    20,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 20 National credits: Airway 4, Cardiology 5, Trauma 3, Medical 6, and Operations 2. At least 2 of the same National credits must contain pediatric content; pediatric is an overlapping content constraint, not an additional sixth bucket.",
    "nremt-emt-nccp-ce-2025-component",
    0,
  ],
  [
    "nremt-emt-nccp-ce-2025-local",
    "nremt-emt-nccp-ce-2025-v1",
    "Local/State Component",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 10 Local/State credits. A state, region, or agency may prescribe the topics; absent a prescription, accepted direct-patient-care EMS education is flexible. Do not also classify the same credited time as National or Individual.",
    "nremt-emt-nccp-ce-2025-component",
    1,
  ],
  [
    "nremt-emt-nccp-ce-2025-individual",
    "nremt-emt-nccp-ce-2025-v1",
    "Individual Component",
    10,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 10 flexible Individual credits using otherwise accepted EMS-related education. Do not also classify the same credited time as National or Local/State.",
    "nremt-emt-nccp-ce-2025-component",
    2,
  ],
  [
    "nremt-aemt-nccp-ce-2025-national",
    "nremt-aemt-nccp-ce-2025-v1",
    "National Component",
    25,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 25 National credits: Airway 5, Cardiology 6, Trauma 4, Medical 7, and Operations 3. At least 2.5 of the same National credits must contain pediatric content; pediatric is an overlapping content constraint, not an additional sixth bucket.",
    "nremt-aemt-nccp-ce-2025-component",
    0,
  ],
  [
    "nremt-aemt-nccp-ce-2025-local",
    "nremt-aemt-nccp-ce-2025-v1",
    "Local/State Component",
    12.5,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 12.5 Local/State credits. A state, region, or agency may prescribe the topics; absent a prescription, accepted direct-patient-care EMS education is flexible. Do not also classify the same credited time as National or Individual.",
    "nremt-aemt-nccp-ce-2025-component",
    1,
  ],
  [
    "nremt-aemt-nccp-ce-2025-individual",
    "nremt-aemt-nccp-ce-2025-v1",
    "Individual Component",
    12.5,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 12.5 flexible Individual credits using otherwise accepted EMS-related education. Do not also classify the same credited time as National or Local/State.",
    "nremt-aemt-nccp-ce-2025-component",
    2,
  ],
  [
    "nremt-paramedic-nccp-ce-2025-national",
    "nremt-paramedic-nccp-ce-2025-v1",
    "National Component",
    30,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 30 National credits: Airway 6, Cardiology 7, Trauma 5, Medical 8, and Operations 4. At least 3 of the same National credits must contain pediatric content; pediatric is an overlapping content constraint, not an additional sixth bucket.",
    "nremt-paramedic-nccp-ce-2025-component",
    0,
  ],
  [
    "nremt-paramedic-nccp-ce-2025-local",
    "nremt-paramedic-nccp-ce-2025-v1",
    "Local/State Component",
    15,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 15 Local/State credits. A state, region, or agency may prescribe the topics; absent a prescription, accepted direct-patient-care EMS education is flexible. Do not also classify the same credited time as National or Individual.",
    "nremt-paramedic-nccp-ce-2025-component",
    1,
  ],
  [
    "nremt-paramedic-nccp-ce-2025-individual",
    "nremt-paramedic-nccp-ce-2025-v1",
    "Individual Component",
    15,
    "minimum",
    "independent",
    null,
    "always",
    "Complete 15 flexible Individual credits using otherwise accepted EMS-related education. Do not also classify the same credited time as National or Local/State.",
    "nremt-paramedic-nccp-ce-2025-component",
    2,
  ],
] as const satisfies readonly CategorySeedBinding[];
