type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

const LAST_VERIFIED_AT = "2026-07-26";

const CA_RN_URL = "https://www.rn.ca.gov/licensees/ce-renewal.shtml";
const CA_LVN_URL =
  "https://www.bvnpt.ca.gov/licensees/renewal_application_form.shtml";
const FL_RN_URL = "https://floridasnursing.gov/registered-nurse-renewal/";
const FL_LPN_URL =
  "https://floridasnursing.gov/licensed-practical-nurse-renewal/";
const NJ_NURSING_URL =
  "https://www.njconsumeraffairs.gov/nur/pages/continuing-education-faq.aspx";
const NY_RN_URL =
  "https://www.op.nysed.gov/professions/registered-professional-nursing/license-requirements";
const NY_LPN_URL =
  "https://www.op.nysed.gov/professions/licensed-practical-nurses/license-requirements";
const PA_RN_URL =
  "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/nursing/registered-nurses-licensure-snapshot";
const PA_LPN_URL =
  "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/nursing/licensed-practical-nurses-licensure-snapshot";
const TX_NURSING_URL =
  "https://www.bon.texas.gov/education_continuing_education.asp.html";

export const NURSING_RULE_SET_SEED_BINDINGS = [
  [
    "ca-rn-2026-v1",
    "ca-rn",
    1,
    "Nursing",
    "Registered Nurse — standard active renewal",
    "California",
    "California Board of Registered Nursing",
    30,
    "contact hours",
    24,
    CA_RN_URL,
    "California Board of Registered Nursing continuing-education and renewal guidance for a standard active biennial renewal. Complete 30 Board-accepted contact hours during the preceding renewal period and keep certificates or grade slips for four years for possible audit. Hours do not carry forward. A nurse initially licensed by passing the national examination within the prior two years is exempt from the 30-hour first-renewal total, but the direct-participation implicit-bias requirement still applies during the first two years; endorsement alone does not create that examination exemption. Inactive status and the Board's overseas, federal or military, and hardship exceptions require separate review. The six-hour gerontology condition shown here is an advanced-practice overlay for a nurse practitioner providing primary care when more than 25% of patients are age 65 or older, not a universal RN requirement. Use the exact BreEZe license dates.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ca-lvn-2026-v1",
    "ca-lvn",
    1,
    "Nursing",
    "Licensed Vocational Nurse — standard active renewal",
    "California",
    "California Board of Vocational Nursing and Psychiatric Technicians",
    30,
    "contact hours",
    24,
    CA_LVN_URL,
    "California Board of Vocational Nursing and Psychiatric Technicians renewal guidance for a standard active LVN renewal. Complete 30 approved contact hours in the two years preceding renewal, retain original records for four years, and provide copies only if audited. The first renewal is exempt, although a license delinquent for more than one complete 24-month cycle can owe CE. Inactive status does not require CE but does not permit practice. Hours belong to the current renewal window and do not carry forward. The California BRN implicit-bias renewal rule applies to BRN licensees and is not imported into this LVN template. Use the exact BreEZe license dates and confirm any delinquent, inactive, or hardship pathway with BVNPT.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-rn-2026-v1",
    "fl-rn",
    1,
    "Nursing",
    "Registered Nurse — standard full biennium",
    "Florida",
    "Florida Board of Nursing",
    24,
    "CE hours",
    24,
    FL_RN_URL,
    "Florida Board of Nursing RN renewal guidance, CE FAQ, Rule 64B9-5.002, and sections 456.031, 456.033, and 464.013, Florida Statutes, for a standard full biennium. Complete 24 hours, including two hours each in prevention of medical errors, Florida laws and rules, and human trafficking; recognizing impairment is due every other renewal. Domestic violence is two additional hours every third biennium, making 26 rather than 24 hours when due; confirm the cadence in CE Broker and activate that condition so iTrack raises this plan to 26. The one-hour HIV/AIDS course is due no later than the first renewal, whose total and proration rules are materially different and outside this standard template. An eligible NCCA- or ABSNC-accredited specialty certification exempts the general and mandatory nursing CE requirements for an RN except the two-hour Human Trafficking course; report the certification exemption in CE Broker. No CE carries forward. Florida Board-approved providers report completions, but the nurse must self-report credits from national organizations or any other missing CE and verify the CE Broker transcript before renewing through MQA. The current renewal also includes any applicable fingerprint or background-screening step.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-lpn-2026-v1",
    "fl-lpn",
    1,
    "Nursing",
    "Licensed Practical Nurse — standard full biennium",
    "Florida",
    "Florida Board of Nursing",
    24,
    "CE hours",
    24,
    FL_LPN_URL,
    "Florida Board of Nursing LPN renewal guidance, CE FAQ, Rule 64B9-5.002, and sections 456.031, 456.033, and 464.013, Florida Statutes, for a standard full biennium. Complete 24 hours, including two hours each in prevention of medical errors, Florida laws and rules, and human trafficking; recognizing impairment is due every other renewal. Domestic violence is two additional hours every third biennium, making 26 rather than 24 hours when due; confirm the cadence in CE Broker and activate that condition so iTrack raises this plan to 26. The one-hour HIV/AIDS course is due no later than the first renewal, whose total and proration rules are materially different and outside this standard template. An eligible NCCA- or ABSNC-accredited specialty certification exempts the general and mandatory nursing CE requirements for an LPN except the two-hour Human Trafficking course; report the certification exemption in CE Broker. No CE carries forward. Florida Board-approved providers report completions, but the nurse must self-report credits from national organizations or any other missing CE and verify the CE Broker transcript before renewing through MQA. The current renewal also includes any applicable fingerprint or background-screening step.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-rn-2026-v1",
    "nj-rn",
    1,
    "Nursing",
    "Registered Nurse — standard active biennial renewal",
    "New Jersey",
    "New Jersey Board of Nursing",
    30,
    "contact hours",
    24,
    NJ_NURSING_URL,
    "New Jersey Board of Nursing continuing-education guidance and N.J.A.C. 13:37 for an active biennial RN renewal. Complete 30 contact hours in the two years preceding renewal, including one hour on prescription opioids, alternatives, pain management, and the risks and signs of abuse, addiction, and diversion. An RN providing perinatal treatment or care to pregnant persons must complete one hour of evidence-based explicit- and implicit-bias CE at the first biennial renewal after July 7, 2026; it is within the 30. Up to 15 eligible excess hours may carry only to the immediately following biennium. iTrack does not copy them automatically: record the actual prior-period date only after confirming eligibility and retain evidence. Attest at renewal and keep records for at least four years; the Board FAQ recommends five. An active license still requires CE when the nurse is retired from work or practices outside New Jersey. Inactive status and a Board-granted hardship waiver are separate paths.",
    "2025-07-07",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-lpn-2026-v1",
    "nj-lpn",
    1,
    "Nursing",
    "Licensed Practical Nurse — standard active biennial renewal",
    "New Jersey",
    "New Jersey Board of Nursing",
    30,
    "contact hours",
    24,
    NJ_NURSING_URL,
    "New Jersey Board of Nursing continuing-education guidance and N.J.A.C. 13:37 for an active biennial LPN renewal. Complete 30 contact hours in the two years preceding renewal, including one hour on prescription opioids, alternatives, pain management, and the risks and signs of abuse, addiction, and diversion. An LPN providing perinatal treatment or care to pregnant persons must complete one hour of evidence-based explicit- and implicit-bias CE at the first biennial renewal after July 7, 2026; it is within the 30. Up to 15 eligible excess hours may carry only to the immediately following biennium. iTrack does not copy them automatically: record the actual prior-period date only after confirming eligibility and retain evidence. Attest at renewal and keep records for at least four years; the Board FAQ recommends five. An active license still requires CE when the nurse is retired from work or practices outside New Jersey. Inactive status and a Board-granted hardship waiver are separate paths.",
    "2025-07-07",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-rn-2026-v1",
    "ny-rn-registration-training",
    1,
    "Nursing",
    "Registered Professional Nurse — registration and mandated training",
    "New York",
    "New York State Education Department",
    0,
    "training hours",
    36,
    NY_RN_URL,
    "New York licenses nurses for life and registers authority to practice in approximately three-year periods; NYSED does not impose a broad recurring numeric CE-hour total on RNs. This zero-total template tracks mandated training without fabricating hours. Under Education Law §6505-b, an RN practicing in New York completes approved training appropriate to practice every four years, including infection-control instruction on sepsis and barrier precautions to prevent transmission of HIV, HBV, HCV, and infections that could lead to sepsis, unless NYSED accepts equivalent recent training or grants a nature-of-practice exemption. Course length varies, so the checklist rather than an invented hour value controls. Attest to infection-control compliance at initial licensure or registration and every later registration, retain the certificate, and provide it only if NYSED requests it. RNs also have a one-time two-hour child-abuse identification and reporting duty unless education or a practice-based exemption applies. All mandated reporters, including previously trained RNs, must complete the updated child-abuse curriculum by November 17, 2026; training from November 1, 2022 through August 31, 2025 may be supplemented with the official 15-minute addendum. Submit the authorized child-abuse Certification of Completion to NYSED; a current licensee may upload it. Re-register online, complete the RN workforce survey, and use the exact NYSED dates. The separate BSN-in-10 education milestone is not CE, but this template includes a conditional checkpoint so an affected RN can track the degree deadline without converting it into hours.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-lpn-2026-v1",
    "ny-lpn-registration-training",
    1,
    "Nursing",
    "Licensed Practical Nurse — registration and mandated training",
    "New York",
    "New York State Education Department",
    0,
    "training hours",
    36,
    NY_LPN_URL,
    "New York licenses nurses for life and registers authority to practice in approximately three-year periods; NYSED does not impose a broad recurring numeric CE-hour total on LPNs. This zero-total template tracks mandated training without fabricating hours. Under Education Law §6505-b, an LPN practicing in New York completes approved training appropriate to practice every four years, including infection-control instruction on sepsis and barrier precautions to prevent transmission of HIV, HBV, HCV, and infections that could lead to sepsis, unless NYSED accepts equivalent recent training or grants a nature-of-practice exemption. A nurse not currently practicing in New York must complete the training within 90 days after resuming New York practice. Provider course length varies, so the checklist rather than an invented hour value controls. LPN licensure alone is not one of the child-abuse mandated-reporter categories listed by NYSED, but an LPN may still be covered through employment or another statutory role and should activate the conditional child-abuse checkpoint only when applicable. Attest and re-register online, retain certificates, complete the required LPN workforce survey at renewal, and use the exact NYSED registration dates.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "pa-rn-2026-v1",
    "pa-rn",
    1,
    "Nursing",
    "Registered Nurse — standard biennial renewal",
    "Pennsylvania",
    "Pennsylvania State Board of Nursing",
    30,
    "CE hours",
    24,
    PA_RN_URL,
    "Pennsylvania State Board of Nursing RN guidance and 49 Pa. Code §21.131 for a standard biennial renewal. Complete 30 hours in the immediately preceding biennium, including two hours of Board-approved child-abuse recognition and reporting. The one-time two-hour organ- and tissue-donation and recovery course applies beginning May 1, 2026 and remains within the 30: an RN licensed before that date completes it within five years of the applicable renewal anchor, an RN initially licensed on or after that date within five years of initial licensure, and an RN reactivated on or after that date within five years of reactivation. The first renewal is exempt from the 30-hour total but not from the recurring child-abuse course, so it requires a custom two-hour plan rather than this standard template. No CE carries forward. Attest in PALS, retain records for five years, and rely on the approved child-abuse provider's electronic report. A Board waiver for serious illness, military service, or demonstrated hardship is cycle-specific.",
    "2026-05-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "pa-lpn-2026-v1",
    "pa-lpn",
    1,
    "Nursing",
    "Licensed Practical Nurse — biennial mandated training",
    "Pennsylvania",
    "Pennsylvania State Board of Nursing",
    2,
    "training hours",
    24,
    PA_LPN_URL,
    "Pennsylvania State Board of Nursing LPN guidance. Pennsylvania imposes no general recurring CE-hour total on an LPN renewal, but two hours of Board-approved child-abuse recognition and reporting are required every biennium. The approved provider reports completion electronically and the nurse renews through PALS. The RN organ- and tissue-donation course is not imported into this LPN template. The training is cycle-specific and does not carry forward. Use the exact PALS dates and confirm any inactive, reactivation, disciplinary, or Board-adjusted path separately.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-rn-2026-v1",
    "tx-rn",
    1,
    "Nursing",
    "Registered Nurse — standard 20-hour CNE path",
    "Texas",
    "Texas Board of Nursing",
    20,
    "CNE contact hours",
    24,
    TX_NURSING_URL,
    "Texas Board of Nursing continuing-competency guidance for a standard non-initial RN renewal using the 20-hour CNE path. Complete 20 Board-acceptable contact hours in the nurse's area of practice during the licensing period. A specifically Board-approved national nursing certification is an alternative path and should not be represented as 20 locally inferred hours. Complete two hours of nursing jurisprudence and ethics at any point within each three-cycle, approximately six-year window; mark this condition applicable only if completing or still owing it in the current period, and do not repeat it if already completed earlier in the same window. Certification cannot replace it. Practice with older adults or geriatric populations triggers two hours each period, subject to the Board's certification alternative. A nurse providing direct patient care completes an HHSC-approved human-trafficking-prevention course every period; the Board does not fix its duration, and it counts toward 20 only if the selected course separately awards acceptable CNE. Emergency-room employment triggers a one-time two-hour forensic-evidence course within two years after initial ER employment. Separately, any nurse who performs a forensic examination on a sexual-assault survivor must have basic forensic-evidence-collection training or equivalent before the examination; qualifying training may satisfy both duties. A timely first renewal is generally exempt from continuing competency except applicable forensic training. No hours carry forward. Through August 31, 2026 renewal uses attestation and possible audit; beginning September 1, 2026, upload every required certificate in the Texas Nurse Portal. Keep ordinary records for three licensing periods or six years and forensic evidence indefinitely.",
    "2026-09-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-lvn-2026-v1",
    "tx-lvn",
    1,
    "Nursing",
    "Licensed Vocational Nurse — standard 20-hour CNE path",
    "Texas",
    "Texas Board of Nursing",
    20,
    "CNE contact hours",
    24,
    TX_NURSING_URL,
    "Texas Board of Nursing continuing-competency guidance for a standard non-initial LVN renewal using the 20-hour CNE path. Complete 20 Board-acceptable contact hours in the nurse's area of practice during the licensing period. A specifically Board-approved national nursing certification is an alternative path and should not be represented as 20 locally inferred hours. Complete two hours of nursing jurisprudence and ethics at any point within each three-cycle, approximately six-year window; mark this condition applicable only if completing or still owing it in the current period, and do not repeat it if already completed earlier in the same window. Certification cannot replace it. Practice with older adults or geriatric populations triggers two hours each period, subject to the Board's certification alternative. A nurse providing direct patient care completes an HHSC-approved human-trafficking-prevention course every period; the Board does not fix its duration, and it counts toward 20 only if the selected course separately awards acceptable CNE. Emergency-room employment triggers a one-time two-hour forensic-evidence course within two years after initial ER employment. Separately, any nurse who performs a forensic examination on a sexual-assault survivor must have basic forensic-evidence-collection training or equivalent before the examination; qualifying training may satisfy both duties. A timely first renewal is generally exempt from continuing competency except applicable forensic training. No hours carry forward. Through August 31, 2026 renewal uses attestation and possible audit; beginning September 1, 2026, upload every required certificate in the Texas Nurse Portal. Keep ordinary records for three licensing periods or six years and forensic evidence indefinitely.",
    "2026-09-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

const FL_TOPIC_GROUP = "Florida nursing CE topic";
const NJ_CREDIT_SOURCE_GROUP = "New Jersey nursing period source";

function floridaCategories(
  prefix: "fl-rn-2026" | "fl-lpn-2026",
  ruleSetId: "fl-rn-2026-v1" | "fl-lpn-2026-v1",
): readonly CategorySeedBinding[] {
  return [
    [
      `${prefix}-medical-errors`,
      ruleSetId,
      "Prevention of Medical Errors",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two Board-approved hours every renewal within the 24-hour standard total.",
      FL_TOPIC_GROUP,
      0,
    ],
    [
      `${prefix}-laws-rules`,
      ruleSetId,
      "Florida Laws and Rules",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two Board-approved hours every renewal within the 24-hour standard total.",
      FL_TOPIC_GROUP,
      1,
    ],
    [
      `${prefix}-human-trafficking`,
      ruleSetId,
      "Human Trafficking",
      2,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete two hours every biennium in a course meeting section 464.013(3)(c), Florida Statutes. The course does not have to be offered by a Florida Board of Nursing-approved provider. This duty remains required under the specialty-certification exemption.",
      FL_TOPIC_GROUP,
      2,
    ],
    [
      `${prefix}-workplace-impairment`,
      ruleSetId,
      "Recognizing Impairment in the Workplace",
      2,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Required every other renewal within the 24-hour standard total. Confirm the assigned cadence in CE Broker.",
      FL_TOPIC_GROUP,
      3,
    ],
    [
      `${prefix}-domestic-violence`,
      ruleSetId,
      "Domestic Violence — additional two hours",
      2,
      "minimum",
      "independent",
      null,
      "conditional",
      "Required every third biennium in addition to the standard 24 hours. Activating this condition raises the credential total to 26; complete two Board-approved hours and verify them in CE Broker.",
      null,
      4,
    ],
    [
      `${prefix}-hiv-aids`,
      ruleSetId,
      "HIV/AIDS — first-renewal checkpoint",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "One Board-approved hour is due no later than first renewal. The first-renewal total and proration rules differ from this full-biennium template, so use a custom official total when this applies.",
      null,
      5,
    ],
  ];
}

function newJerseyCategories(
  prefix: "nj-rn-2026" | "nj-lpn-2026",
  ruleSetId: "nj-rn-2026-v1" | "nj-lpn-2026-v1",
): readonly CategorySeedBinding[] {
  // The RN identifier predates this managed module. Keeping it stable preserves
  // active-cycle allocations and submitted historical snapshots during refresh.
  const opioidCategoryId =
    ruleSetId === "nj-rn-2026-v1"
      ? "nj-rn-2026-opioids"
      : `${prefix}-prescription-opioids`;
  return [
    [
      `${prefix}-current-period`,
      ruleSetId,
      "Current-Period Eligible Nursing CE",
      0,
      "informational",
      "independent",
      null,
      "always",
      "Use this period-source classifier for eligible hours completed during the current biennium. Select any applicable opioid or perinatal-bias topic separately.",
      NJ_CREDIT_SOURCE_GROUP,
      0,
    ],
    [
      `${prefix}-confirmed-carryover`,
      ruleSetId,
      "Board-Eligible Confirmed Carryover",
      15,
      "maximum",
      "independent",
      null,
      "conditional",
      "At most 15 eligible excess hours may carry from the immediately preceding biennium. Record only a Board-eligible amount, retain evidence, and use the actual prior-period completion date; iTrack never copies credit automatically.",
      NJ_CREDIT_SOURCE_GROUP,
      1,
    ],
    [
      opioidCategoryId,
      ruleSetId,
      "Prescription Opioids",
      1,
      "minimum",
      "overlapping",
      null,
      "always",
      "Complete one hour every biennium covering prescription opioids, including non-opioid alternatives, pain management, and risks or signs of abuse, addiction, and diversion.",
      null,
      2,
    ],
    [
      `${prefix}-perinatal-bias`,
      ruleSetId,
      "Perinatal Explicit and Implicit Bias",
      1,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Applies to a nurse providing perinatal treatment or care to pregnant persons at the first biennial renewal after July 7, 2026. This hour remains within the 30-hour total.",
      null,
      3,
    ],
  ];
}

function newYorkCategories(
  prefix: "ny-rn-2026" | "ny-lpn-2026",
  ruleSetId: "ny-rn-2026-v1" | "ny-lpn-2026-v1",
  isRegisteredNurse: boolean,
): readonly CategorySeedBinding[] {
  const infectionControl: CategorySeedBinding = [
    `${prefix}-infection-control`,
    ruleSetId,
    "Infection Control, Barrier Precautions, and Sepsis — four-year training",
    0,
    "informational",
    "independent",
    null,
    "conditional",
    "Every four years while practicing in New York, complete NYSED-approved training appropriate to practice, including infection-control instruction on sepsis and barrier precautions to prevent transmission of HIV, HBV, HCV, and infections that could lead to sepsis, unless NYSED accepts equivalent recent training or grants a nature-of-practice exemption. Provider length varies; completion and the certificate—not a fabricated hour value—control.",
    null,
    0,
  ];
  if (isRegisteredNurse) {
    return [
      infectionControl,
      [
        `${prefix}-child-abuse`,
        ruleSetId,
        "Child Abuse Identification and Reporting — one-time RN training",
        2,
        "minimum",
        "independent",
        null,
        "conditional",
        "One-time two-hour requirement unless NYSED already records completion through an approved New York program or provider, or a practice-based exemption applies. Submit the authorized Certification of Completion to NYSED; a current licensee may upload it.",
        null,
        1,
      ],
      [
        `${prefix}-updated-mandated-reporter`,
        ruleSetId,
        "Child Abuse Reporting — 2026 updated curriculum",
        0,
        "informational",
        "overlapping",
        null,
        "conditional",
        "Mandated reporters must complete the updated curriculum by November 17, 2026. Eligible training completed from November 1, 2022 through August 31, 2025 may use the official 15-minute addendum; a full updated course may also satisfy an otherwise outstanding one-time RN requirement.",
        null,
        2,
      ],
      [
        `${prefix}-bsn-in-10`,
        ruleSetId,
        "BSN-in-10 Registration Milestone",
        0,
        "informational",
        "independent",
        null,
        "conditional",
        "Track only for a nonexempt RN first licensed in New York after June 18, 2020. Anchor the degree deadline to the nurse's individual ten-year anniversary of initial New York licensure and the first registration beginning after that anniversary. Confirm a qualifying nursing bachelor's or higher degree, conditional registration, or temporary educational exemption with NYSED. This is not CE and carries no invented hour value.",
        null,
        3,
      ],
    ];
  }
  return [
    infectionControl,
    [
      `${prefix}-updated-mandated-reporter`,
      ruleSetId,
      "Child Abuse Reporting — employment or role-based checkpoint",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "LPN licensure alone is not listed as a mandated-reporter category, but employment or another statutory role may trigger the updated curriculum due November 17, 2026. Confirm the role before activating this checkpoint.",
      null,
      1,
    ],
  ];
}

function texasCategories(
  prefix: "tx-rn-2026" | "tx-lvn-2026",
  ruleSetId: "tx-rn-2026-v1" | "tx-lvn-2026-v1",
): readonly CategorySeedBinding[] {
  return [
    [
      `${prefix}-jurisprudence-ethics`,
      ruleSetId,
      "Nursing Jurisprudence and Ethics — three-cycle window",
      2,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Complete once at any point within each three-cycle, approximately six-year window. Mark Applies only when completing or still owing it in this period; if it was completed in an earlier period of the same window, mark Not this cycle. These hours remain within the 20-hour CNE total and a national certification cannot substitute for them.",
      null,
      0,
    ],
    [
      `${prefix}-older-adult-geriatric`,
      ruleSetId,
      "Older Adult or Geriatric Care",
      2,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "Applies each licensing period when the nurse's practice includes older adults or geriatric populations. An approved geriatric certification may satisfy this targeted duty.",
      null,
      1,
    ],
    [
      `${prefix}-human-trafficking`,
      ruleSetId,
      "HHSC-Approved Human Trafficking Prevention Course",
      0,
      "informational",
      "overlapping",
      null,
      "conditional",
      "Applies each licensing period to a nurse providing direct patient care. The Board fixes no numeric duration; count hours toward the 20 only when the selected HHSC-approved course separately awards acceptable CNE.",
      null,
      2,
    ],
    [
      `${prefix}-forensic-evidence`,
      ruleSetId,
      "Forensic Evidence Collection — Emergency-Room Employment",
      2,
      "minimum",
      "overlapping",
      null,
      "conditional",
      "One-time: a nurse employed in an emergency-room setting must complete at least two contact hours within two years after initial ER employment. This includes home-unit, float or scheduled-shift, contractual, temporary, per-diem, agency, and traveling ER work.",
      null,
      3,
    ],
    [
      `${prefix}-forensic-exam-training`,
      ruleSetId,
      "Forensic Evidence Collection — Before Performing an Examination",
      0,
      "informational",
      "overlapping",
      null,
      "conditional",
      "One-time: any nurse who performs a forensic examination on a sexual-assault survivor must complete basic forensic-evidence-collection training or equivalent before the examination. Qualifying training may satisfy both forensic requirements.",
      null,
      4,
    ],
    [
      `${prefix}-sb25-nutrition-rule-refresh`,
      ruleSetId,
      "Nutrition and Metabolic Health — 2027 rule refresh",
      0,
      "informational",
      "independent",
      null,
      "conditional",
      "For every renewal application filed on or after January 1, 2027, this checkpoint applies: refresh the plan against the current Texas Board rule before relying on it. Senate Bill 25 requires nutrition and metabolic-health content, but the Board had not yet prescribed the hours or course content when this template was verified; adopted hours and content must replace this zero-value placeholder. iTrack does not invent a number.",
      null,
      5,
    ],
  ];
}

export const NURSING_CATEGORY_SEED_BINDINGS = [
  [
    "ca-rn-2026-implicit-bias",
    "ca-rn-2026-v1",
    "Implicit Bias",
    1,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Complete one hour through direct participation within the first two years after initial licensure. It remains due even when the examination-based first-renewal 30-hour total is waived.",
    null,
    0,
  ],
  [
    "ca-rn-2026-gerontology",
    "ca-rn-2026-v1",
    "Gerontology and Care of Older Patients",
    6,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Advanced-practice overlay only: applies to a nurse practitioner providing primary care when more than 25% of the patient population is age 65 or older; the six hours remain within the 30-hour total.",
    null,
    1,
  ],
  ...floridaCategories("fl-rn-2026", "fl-rn-2026-v1"),
  ...floridaCategories("fl-lpn-2026", "fl-lpn-2026-v1"),
  ...newJerseyCategories("nj-rn-2026", "nj-rn-2026-v1"),
  ...newJerseyCategories("nj-lpn-2026", "nj-lpn-2026-v1"),
  ...newYorkCategories("ny-rn-2026", "ny-rn-2026-v1", true),
  ...newYorkCategories("ny-lpn-2026", "ny-lpn-2026-v1", false),
  [
    "pa-rn-2026-child-abuse",
    "pa-rn-2026-v1",
    "Child Abuse Recognition and Reporting",
    2,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete two hours through a Pennsylvania Board-approved provider every biennium. The provider reports completion electronically.",
    null,
    0,
  ],
  [
    "pa-rn-2026-organ-tissue-donation",
    "pa-rn-2026-v1",
    "Organ and Tissue Donation and Recovery",
    2,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "One-time requirement applicable beginning May 1, 2026. If licensed before that date, complete it within five years of the applicable renewal anchor; if initially licensed on or after that date, within five years of initial licensure; if reactivated on or after that date, within five years of reactivation. It remains within the 30-hour standard total.",
    null,
    1,
  ],
  [
    "pa-lpn-2026-child-abuse",
    "pa-lpn-2026-v1",
    "Child Abuse Recognition and Reporting",
    2,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete two hours through a Pennsylvania Board-approved provider every biennium. The provider reports completion electronically.",
    null,
    0,
  ],
  ...texasCategories("tx-rn-2026", "tx-rn-2026-v1"),
  ...texasCategories("tx-lvn-2026", "tx-lvn-2026-v1"),
] as const satisfies readonly CategorySeedBinding[];

export const NURSING_MAXIMUM_CLASSIFICATION_RULE_SET_IDS = [
  "nj-rn-2026-v1",
  "nj-lpn-2026-v1",
] as const;

export const NURSING_RENEWAL_TASK_COPY_BINDINGS = [
  [
    "ca-rn-2026-v1",
    "Confirm BreEZe dates, first-renewal status, and any advanced-practice gerontology condition",
    "Complete 30 Board-accepted hours and retain every certificate for audit",
    "Renew through BreEZe and save the updated California RN license record",
  ],
  [
    "ca-lvn-2026-v1",
    "Confirm BreEZe dates and any first, delinquent, inactive, or hardship status",
    "Complete 30 BVNPT-approved hours and retain the originals for four years",
    "Renew through BreEZe and save the updated California LVN license record",
  ],
  [
    "fl-rn-2026-v1",
    "Confirm MQA and CE Broker dates, impairment cadence, domestic-violence cycle, and fingerprints",
    "Complete and verify every applicable Florida nursing topic in CE Broker",
    "Renew through MQA and save the updated RN license and CE Broker record",
  ],
  [
    "fl-lpn-2026-v1",
    "Confirm MQA and CE Broker dates, impairment cadence, domestic-violence cycle, and fingerprints",
    "Complete and verify every applicable Florida nursing topic in CE Broker",
    "Renew through MQA and save the updated LPN license and CE Broker record",
  ],
  [
    "nj-rn-2026-v1",
    "Confirm Board dates, perinatal-care status, and any immediately-prior carryover",
    "Complete 30 hours, including opioids and any applicable perinatal-bias course",
    "Attest and renew, then save the updated New Jersey RN license record",
  ],
  [
    "nj-lpn-2026-v1",
    "Confirm Board dates, perinatal-care status, and any immediately-prior carryover",
    "Complete 30 hours, including opioids and any applicable perinatal-bias course",
    "Attest and renew, then save the updated New Jersey LPN license record",
  ],
  [
    "ny-rn-2026-v1",
    "Confirm NYSED dates, New York practice, exemptions, child-abuse status, and any BSN-in-10 milestone",
    "Complete due infection-control and mandated-reporter training; track any BSN-in-10 milestone separately without treating it as CE",
    "Re-register with NYSED, complete the RN workforce survey, and save confirmation",
  ],
  [
    "ny-lpn-2026-v1",
    "Confirm NYSED registration dates, New York practice, and any role-based reporter duty",
    "Complete due infection-control and any employment-based reporter training",
    "Re-register with NYSED, complete the LPN workforce survey, and save confirmation",
  ],
  [
    "pa-rn-2026-v1",
    "Confirm PALS dates, first-renewal status, and the correct licensure, renewal, or reactivation anchor for the one-time organ-donation window",
    "Complete 30 hours and verify the approved provider reported Act 31 training",
    "Renew through PALS and save the updated Pennsylvania RN license record",
  ],
  [
    "pa-lpn-2026-v1",
    "Confirm the PALS biennium and approved Act 31 provider",
    "Complete two hours of child-abuse recognition and verify electronic reporting",
    "Renew through PALS and save the updated Pennsylvania LPN license record",
  ],
  [
    "tx-rn-2026-v1",
    "Confirm the standard 20-hour CNE path (not the certification alternative), Nurse Portal dates, practice topics, the jurisprudence and ethics six-year window, and any 2027 nutrition-rule update",
    "Complete 20 CNE hours and every applicable targeted competency course",
    "Follow the date-specific Nurse Portal verification step, renew, and save confirmation",
  ],
  [
    "tx-lvn-2026-v1",
    "Confirm the standard 20-hour CNE path (not the certification alternative), Nurse Portal dates, practice topics, the jurisprudence and ethics six-year window, and any 2027 nutrition-rule update",
    "Complete 20 CNE hours and every applicable targeted competency course",
    "Follow the date-specific Nurse Portal verification step, renew, and save confirmation",
  ],
] as const;
