type RuleSetSeedBinding = readonly [
  id: string,
  stableKey: string,
  version: number,
  profession: string,
  credentialName: string,
  jurisdiction: string,
  issuer: string,
  totalUnits: number,
  unitLabel: string,
  cycleMonths: number,
  sourceUrl: string,
  sourceTitle: string,
  effectiveDate: string | null,
  lastVerifiedAt: string,
  reviewStatus: "source_linked_check_conditions",
  isCurrent: 1,
];

type CategorySeedBinding = readonly [
  id: string,
  ruleSetId: string,
  name: string,
  requiredUnits: number,
  kind: "minimum" | "maximum" | "informational",
  relation: "independent" | "nested" | "overlapping",
  parentCategoryId: string | null,
  applicability: "always" | "conditional" | "optional",
  conditionNote: string | null,
  exclusiveGroup: string | null,
  sortOrder: number,
];

const LAST_VERIFIED_AT = "2026-07-26";

const CA_PHARMACIST_URL =
  "https://www.pharmacy.ca.gov/licensees/personal/ce.shtml";
const TX_PHARMACIST_URL =
  "https://www.pharmacy.texas.gov/licensees/ce-pharmacist-faq.asp";
const FL_PHARMACIST_URL =
  "https://floridaspharmacy.gov/pharmacist-renewal/";
const NY_PHARMACIST_URL =
  "https://www.op.nysed.gov/professions/pharmacist/continuing-education";
const NJ_PHARMACIST_URL =
  "https://www.njconsumeraffairs.gov/phar/Pages/FAQ.aspx";
const PA_PHARMACIST_URL =
  "https://www.pacodeandbulletin.gov/secure/pacode/data/049/chapter27/s27.32.html";

export const PHARMACY_RULE_SET_SEED_BINDINGS = [
  [
    "ca-pharmacist-2026-v1",
    "ca-pharmacist-standard",
    1,
    "Pharmacy",
    "Pharmacist — standard active renewal",
    "California",
    "California State Board of Pharmacy",
    30,
    "CE hours",
    24,
    CA_PHARMACIST_URL,
    "California Board of Pharmacy continuing-education guidance and 16 CCR §1732.5 (https://govt.westlaw.com/calregs/Document/I7C278470591311EFB135D2440742D05A). Use the exact Board license dates for an active, second-or-later standard pharmacist renewal. Complete 30 hours during the two years immediately before expiration, including the Board-provided one-hour law webinar, the Board-provided one-hour ethics webinar, and one hour of cultural-competency CE. The first pharmacist renewal is exempt from all CE. Advanced Practice Pharmacist renewal requires 10 additional hours relevant to the APP scope and is outside this standard template; inactive status, hardship waivers, and student exemptions also require separate Board review. Keep completion certificates for four years. The Board does not rely on NABP CPE Monitor for audits, and its own webinars may not appear there, so retain the Board certificates. Hours belong to the applicable renewal window and License Lantern does not carry surplus forward.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "tx-pharmacist-2026-v1",
    "tx-pharmacist-standard-full-cycle",
    1,
    "Pharmacy",
    "Pharmacist — standard non-initial active renewal",
    "Texas",
    "Texas State Board of Pharmacy",
    30,
    "approved CE hours",
    24,
    TX_PHARMACIST_URL,
    "Texas State Board of Pharmacy pharmacist CE FAQ for a regular, non-initial active renewal. Use the exact birth-month expiration and assigned two-year period in the TSBP account. Complete 30 approved hours, including at least one hour of Texas-specific pharmacy laws or rules, plus one HHSC-approved human-trafficking-prevention course each renewal. TSBP does not prescribe a numeric duration for the trafficking course, and whether its hours count toward the 30 depends on the course's qualifying accreditation, so it is a checklist condition rather than a fabricated hourly category. The initial 30-day renewal and the later first-license period have materially different exemptions and controlled-substance training duties and are outside this template. Sterile-compounding, immunizer, preceptor, and drug-therapy-management certifications can add separate CE conditions; confirm every held authorization in the TSBP account. No CE carries forward. Keep certificates for three years after reporting and produce them if audited. TSBP's amended electronic-tracking provisions take effect September 1, 2026, so follow the Board's current reporting instructions for any cycle crossing that date (https://www.pharmacy.texas.gov/files_pdf/pharmacist_CE_breakdown.pdf).",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "fl-pharmacist-2026-v1",
    "fl-pharmacist-standard-full-biennium",
    1,
    "Pharmacy",
    "Pharmacist — standard full-biennium active renewal",
    "Florida",
    "Florida Board of Pharmacy",
    30,
    "CE hours",
    24,
    FL_PHARMACIST_URL,
    "Florida Board of Pharmacy renewal guidance and current Rule 64B16-26.103 (https://flrules.org/gateway/ruleNo.asp?id=64B16-26.103) for a standard full biennium after the first renewal. Use the exact MQA license dates. Allocate the 30 hours into 26 General, two Board-approved Controlled Substances, and two Board-approved Medication Errors hours; the current Board page does not impose the stale 10-hour live-course minimum found in older summaries. First renewals have reduced totals and an HIV/AIDS requirement and must not use this template. A certified immunizer needs three hours within the 30; a collaborative-practice certificate generally needs eight within the 30, subject to the Board's less-than-12-month exception; and a test-and-treat certificate needs three within the 30. Confirm each held certification in CE Broker. Board-meeting attendance, Board service, and indigent-care volunteer credit have separate caps modeled here; enter only the amount the Board accepts. The historical human-trafficking CE deadline was a one-time 2021 obligation, not a recurring biennial bucket. CE must be reported through CE Broker, and renewal now also requires the applicable background screening or fingerprint-retention step. Delinquent, inactive, retired, reactivation, consultant-pharmacist, and nuclear-pharmacist paths are outside this template. License Lantern never treats reported CE or a submitted application as proof that MQA renewed the license.",
    "2025-05-22",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "ny-pharmacist-2026-v1",
    "ny-pharmacist-standard-registration",
    1,
    "Pharmacy",
    "Pharmacist — full triennial registration period",
    "New York",
    "New York State Education Department",
    45,
    "contact hours",
    36,
    NY_PHARMACIST_URL,
    "New York State Education Department pharmacist CE guidance and Part 63 (https://www.op.nysed.gov/title8/regulations-commissioner-education/part-63) for a full 36-month registration period. Use the exact NYSED registration dates. Complete 45 contact hours, including at least 23 through live or interactive instruction because no more than 22 may be self-study, at least three hours in medication or prescription-error reduction, and at least three hours in pharmaceutical compounding for periods beginning on or after January 1, 2023. Unlike many states, New York includes the first registration period; however, a period shorter than 36 months is calculated at 1.25 hours per month with a majority live and must use a custom NYSED total instead of this full-cycle template. A pharmacist participating in collaborative drug-therapy management must complete five non-self-study hours related to the protocol, subject to the current statutory program. No credit carries forward. The pharmacist attests at registration, providers do not report completion to NYSED, and records must be kept for six years from the program date. CPR, BLS, ACLS, and EMT credit has course and cycle limits; record only the NYSED-eligible amount. Inactive practice, conditional registration, adjustments, and exemptions require separate NYSED review.",
    "2023-01-01",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "nj-pharmacist-2026-v1",
    "nj-pharmacist-established-biennial-renewal",
    1,
    "Pharmacy",
    "Pharmacist — established full biennial renewal",
    "New Jersey",
    "New Jersey Board of Pharmacy",
    30,
    "CE credits",
    24,
    NJ_PHARMACIST_URL,
    "New Jersey Board of Pharmacy FAQ and current N.J.A.C. 13:39 rules (https://www.njconsumeraffairs.gov/regulations/Chapter-39-State-Board-of-Pharmacy.pdf) for an established full biennial cycle. Use the Board-assigned dates. Complete 30 credits, including at least 10 didactic credits with live interaction, three credits in New Jersey pharmacy law, and one credit related to prescription opioids. The opioid credit may not carry forward. A pharmacist authorized to immunize needs two immunization-related credits within the 30. A collaborative drug-therapy-management participant needs 10 credits in each covered disease or condition; coexisting or interrelated conditions may share one 10-credit total, but multiple unrelated protocols require Board-specific tracking beyond this single conditional category. The first renewal is exempt unless the pharmacist was licensed by reciprocity, so first-cycle status must be confirmed before using this template. Up to 10 eligible excess credits earned during the final six months of the immediately preceding cycle may carry only when supported by Board-compliant evidence; License Lantern never copies them automatically. Classify every activity by delivery mode and by current-period versus confirmed-carryover source. Renewal attestation, audits, inactive status, late renewal, and reinstatement remain separate Board processes.",
    null,
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
  [
    "pa-pharmacist-2026-v1",
    "pa-pharmacist-standard-biennial-renewal",
    1,
    "Pharmacy",
    "Pharmacist — standard biennial renewal",
    "Pennsylvania",
    "Pennsylvania State Board of Pharmacy",
    30,
    "contact hours",
    24,
    PA_PHARMACIST_URL,
    "Pennsylvania State Board of Pharmacy continuing-education rule, 49 Pa. Code §27.32, for a standard biennial renewal. Use the exact PALS license dates and Board-approved or ACPE pharmacist-targeted credit. Complete 30 contact hours, including two hours in ACPE-designated Patient Safety and two hours of Board-approved child-abuse recognition and reporting. A pharmacist who holds authority to administer injectable medications, biologicals, or immunizations needs two related hours within the 30. A pharmacist who has a current DEA registration, or prescribes controlled substances using another person or entity's DEA number, also needs two hours in pain management, identification of addiction, or opioid prescribing or dispensing under the ABC-MAP requirement (https://www.pa.gov/content/dam/copapwp-pagov/en/dos/department-and-offices/bpoa/pharmacy/Clarification%20of%20Opioid%20Continuing%20Education%20Requirement%20Under%20ABC-MAP.pdf). No hours carry forward. Newly graduated pharmacists are generally exempt at the first renewal except for child-abuse training, while reciprocal licensees can have a quarterly prorated requirement; those paths must use a custom Board-confirmed total. Certify compliance in PALS and retain certificates for two years after renewal for possible audit. Disciplinary education and inactive or reactivation requirements are outside this template.",
    "2026-04-11",
    LAST_VERIFIED_AT,
    "source_linked_check_conditions",
    1,
  ],
] as const satisfies readonly RuleSetSeedBinding[];

const CA_MANDATORY_COURSE_GROUP = "California pharmacist mandatory course";
const FL_CREDIT_BUCKET_GROUP = "Florida pharmacist credit bucket";
const FL_CREDIT_SOURCE_GROUP = "Florida pharmacist credit source";
const NY_DELIVERY_GROUP = "New York pharmacist delivery mode";
const NJ_DELIVERY_GROUP = "New Jersey pharmacist delivery mode";
const NJ_PERIOD_SOURCE_GROUP = "New Jersey pharmacist period source";

export const PHARMACY_CATEGORY_SEED_BINDINGS = [
  [
    "ca-pharmacist-2026-law-webinar",
    "ca-pharmacist-2026-v1",
    "Board-Provided Law Webinar",
    1,
    "minimum",
    "independent",
    null,
    "always",
    "Complete at least one hour through the California Board-provided law webinar during this renewal period and retain the Board certificate.",
    CA_MANDATORY_COURSE_GROUP,
    0,
  ],
  [
    "ca-pharmacist-2026-ethics-webinar",
    "ca-pharmacist-2026-v1",
    "Board-Provided Ethics Webinar",
    1,
    "minimum",
    "independent",
    null,
    "always",
    "Complete at least one hour through the California Board-provided ethics webinar during this renewal period and retain the Board certificate.",
    CA_MANDATORY_COURSE_GROUP,
    1,
  ],
  [
    "ca-pharmacist-2026-cultural-competency",
    "ca-pharmacist-2026-v1",
    "Cultural Competency",
    1,
    "minimum",
    "independent",
    null,
    "always",
    "Complete at least one hour of approved cultural-competency continuing education during this renewal period.",
    CA_MANDATORY_COURSE_GROUP,
    2,
  ],
  [
    "tx-pharmacist-2026-texas-law-rules",
    "tx-pharmacist-2026-v1",
    "Texas-Specific Pharmacy Laws or Rules",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one hour covering Texas-specific pharmacy laws or rules during this renewal period. The separate HHSC-approved human-trafficking-prevention course is a nonnumeric checklist condition.",
    null,
    0,
  ],
  [
    "fl-pharmacist-2026-general",
    "fl-pharmacist-2026-v1",
    "General Pharmacy CE",
    26,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate 26 approved hours to General Pharmacy CE. The same time block cannot also be allocated to the separate Controlled Substances or Medication Errors bucket.",
    FL_CREDIT_BUCKET_GROUP,
    0,
  ],
  [
    "fl-pharmacist-2026-controlled-substances",
    "fl-pharmacist-2026-v1",
    "Controlled Substances",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate two hours from a Florida Board-approved Controlled Substances course. These hours are separate from General Pharmacy CE and Medication Errors.",
    FL_CREDIT_BUCKET_GROUP,
    1,
  ],
  [
    "fl-pharmacist-2026-medication-errors",
    "fl-pharmacist-2026-v1",
    "Medication Errors",
    2,
    "minimum",
    "independent",
    null,
    "always",
    "Allocate two hours from a Florida Board-approved Medication Errors course. These hours are separate from General Pharmacy CE and Controlled Substances.",
    FL_CREDIT_BUCKET_GROUP,
    2,
  ],
  [
    "fl-pharmacist-2026-standard-approved-ce",
    "fl-pharmacist-2026-v1",
    "Standard ACPE or Board-Approved CE",
    0,
    "informational",
    "overlapping",
    null,
    "always",
    "Select this credit-source classifier for ordinary ACPE or Florida Board-approved pharmacist CE that is not claimed as Board-meeting attendance, Board service, or indigent-care volunteer credit.",
    FL_CREDIT_SOURCE_GROUP,
    3,
  ],
  [
    "fl-pharmacist-2026-board-meeting-attendance",
    "fl-pharmacist-2026-v1",
    "Board of Pharmacy Meeting Attendance",
    10,
    "maximum",
    "overlapping",
    null,
    "optional",
    "Florida awards five hours per qualifying Board meeting attended, with no more than 10 hours from meeting attendance in one biennium.",
    FL_CREDIT_SOURCE_GROUP,
    4,
  ],
  [
    "fl-pharmacist-2026-board-service",
    "fl-pharmacist-2026-v1",
    "Board of Pharmacy Member Service",
    10,
    "maximum",
    "overlapping",
    null,
    "optional",
    "Florida awards five hours for qualifying service as a Board of Pharmacy member, with no more than 10 service hours in one biennium.",
    FL_CREDIT_SOURCE_GROUP,
    5,
  ],
  [
    "fl-pharmacist-2026-indigent-care-volunteer",
    "fl-pharmacist-2026-v1",
    "Qualifying Indigent-Care Volunteer Service",
    5,
    "maximum",
    "overlapping",
    null,
    "optional",
    "No more than five hours may count for volunteer services to the indigent under section 456.013(9), Florida Statutes. Retain evidence of the Board-accepted value.",
    FL_CREDIT_SOURCE_GROUP,
    6,
  ],
  [
    "fl-pharmacist-2026-immunizer",
    "fl-pharmacist-2026-v1",
    "Immunization Administration",
    3,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the pharmacist is certified to administer vaccines or epinephrine autoinjection. Complete the required three-hour statewide-physician-association-approved course within—not in addition to—the 30-hour total.",
    null,
    7,
  ],
  [
    "fl-pharmacist-2026-collaborative-practice",
    "fl-pharmacist-2026-v1",
    "Collaborative Practice",
    8,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the pharmacist holds a collaborative-practice certification, unless the Board's less-than-12-month certification exception applies for this renewal. Complete eight Board-approved hours within the 30-hour total.",
    null,
    8,
  ],
  [
    "fl-pharmacist-2026-test-and-treat",
    "fl-pharmacist-2026-v1",
    "Test and Treat",
    3,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the pharmacist holds a test-and-treat certification. Complete three Board-approved hours within—not in addition to—the 30-hour total.",
    null,
    9,
  ],
  [
    "ny-pharmacist-2026-live-interactive",
    "ny-pharmacist-2026-v1",
    "Live or Interactive CE — derived minimum 23",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify live, in-person, or otherwise NYSED-qualifying interactive instruction here. With every hour classified and Self-Study capped at 22, a 45-hour cycle necessarily contains at least 23 live or interactive hours.",
    NY_DELIVERY_GROUP,
    0,
  ],
  [
    "ny-pharmacist-2026-self-study",
    "ny-pharmacist-2026-v1",
    "Self-Study CE",
    22,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 22 of the 45 contact hours may be self-study. Classify every activity by delivery mode; collaborative drug-therapy-management protocol hours cannot be self-study.",
    NY_DELIVERY_GROUP,
    1,
  ],
  [
    "ny-pharmacist-2026-medication-errors",
    "ny-pharmacist-2026-v1",
    "Medication or Prescription Error Reduction",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least three contact hours addressing strategies and techniques to reduce medication and prescription errors.",
    null,
    2,
  ],
  [
    "ny-pharmacist-2026-compounding",
    "ny-pharmacist-2026-v1",
    "Pharmaceutical Compounding",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "For registration periods beginning on or after January 1, 2023, complete at least three contact hours in pharmaceutical compounding.",
    null,
    3,
  ],
  [
    "ny-pharmacist-2026-cdtm",
    "ny-pharmacist-2026-v1",
    "Collaborative Drug-Therapy-Management Protocol Practice",
    5,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies to a pharmacist participating in collaborative drug-therapy management. Complete five hours related to the pharmacist's protocol; NYSED states these hours may not be self-study.",
    null,
    4,
  ],
  [
    "nj-pharmacist-2026-didactic-live",
    "nj-pharmacist-2026-v1",
    "Didactic CE With Live Interaction — derived minimum 10",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify qualifying didactic education with live interaction here. With every credit classified and Non-Didactic CE capped at 20, a 30-credit cycle necessarily contains at least 10 didactic credits.",
    NJ_DELIVERY_GROUP,
    0,
  ],
  [
    "nj-pharmacist-2026-non-didactic",
    "nj-pharmacist-2026-v1",
    "Non-Didactic CE",
    20,
    "maximum",
    "independent",
    null,
    "optional",
    "No more than 20 of the 30 credits may be non-didactic. Videotaped programs and other programs without live interaction are not didactic.",
    NJ_DELIVERY_GROUP,
    1,
  ],
  [
    "nj-pharmacist-2026-current-period",
    "nj-pharmacist-2026-v1",
    "Current-Period CE",
    0,
    "informational",
    "independent",
    null,
    "always",
    "Classify qualifying education completed in the current biennial period here unless it is supported, Board-eligible carryover from the immediately preceding cycle.",
    NJ_PERIOD_SOURCE_GROUP,
    2,
  ],
  [
    "nj-pharmacist-2026-confirmed-carryover",
    "nj-pharmacist-2026-v1",
    "Board-Eligible Confirmed Carryover",
    10,
    "maximum",
    "independent",
    null,
    "conditional",
    "Record only evidence-backed carryover eligible under the Board rule: no more than 10 excess credits earned in the final six months of the immediately preceding biennium and not previously used. Prescription-opioid credit cannot carry.",
    NJ_PERIOD_SOURCE_GROUP,
    3,
  ],
  [
    "nj-pharmacist-2026-law",
    "nj-pharmacist-2026-v1",
    "New Jersey Pharmacy Law",
    3,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least three credits in New Jersey pharmacy law during the biennial period.",
    null,
    4,
  ],
  [
    "nj-pharmacist-2026-prescription-opioids",
    "nj-pharmacist-2026-v1",
    "Prescription Opioids",
    1,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least one credit related to prescription opioids in the current biennium. The Board expressly prohibits carrying this credit from a prior cycle.",
    null,
    5,
  ],
  [
    "nj-pharmacist-2026-immunizer",
    "nj-pharmacist-2026-v1",
    "Immunization Practice",
    2,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the pharmacist is authorized to administer vaccines. Complete at least two credits related to immunization practice within the 30-credit total.",
    null,
    6,
  ],
  [
    "nj-pharmacist-2026-cdtm",
    "nj-pharmacist-2026-v1",
    "Collaborative Drug-Therapy Management",
    10,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies to collaborative drug-therapy-management participation. Complete 10 credits in each disease or condition covered; coexisting or interrelated conditions may share one 10-credit total. If multiple unrelated protocols apply, create an additional custom requirement for every additional Board-required 10-credit group.",
    null,
    7,
  ],
  [
    "pa-pharmacist-2026-patient-safety",
    "pa-pharmacist-2026-v1",
    "Patient Safety",
    2,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least two hours in an ACPE activity carrying the Patient Safety topic designator.",
    null,
    0,
  ],
  [
    "pa-pharmacist-2026-child-abuse",
    "pa-pharmacist-2026-v1",
    "Child-Abuse Recognition and Reporting",
    2,
    "minimum",
    "overlapping",
    null,
    "always",
    "Complete at least two hours of Pennsylvania-approved child-abuse recognition and reporting training and ensure the approved provider reports completion as required.",
    null,
    1,
  ],
  [
    "pa-pharmacist-2026-injectables-immunizations",
    "pa-pharmacist-2026-v1",
    "Injectables, Biologicals, and Immunizations",
    2,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the pharmacist holds authority to administer injectable medications, biologicals, or immunizations. Complete at least two related hours within the 30-hour total.",
    null,
    2,
  ],
  [
    "pa-pharmacist-2026-opioid-practice",
    "pa-pharmacist-2026-v1",
    "Pain, Addiction, and Opioid Practice",
    2,
    "minimum",
    "overlapping",
    null,
    "conditional",
    "Applies when the pharmacist has a current DEA registration or prescribes controlled substances using another person or entity's DEA number. Complete at least two hours in pain management, identification of addiction, or opioid prescribing or dispensing.",
    null,
    3,
  ],
] as const satisfies readonly CategorySeedBinding[];

export const PHARMACY_MAXIMUM_CLASSIFICATION_RULE_SET_IDS = [
  "fl-pharmacist-2026-v1",
  "ny-pharmacist-2026-v1",
  "nj-pharmacist-2026-v1",
] as const;
